/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   protocol_section.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *
 *
 * Author:
 * -------
 *
 *
 *==============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef _PROTOCOL_SECTION_H
#define _PROTOCOL_SECTION_H

typedef enum /* Global Protocol Section ID */
{
  PROTOCOL_SECTION__GAN_TCP = 100,
  PROTOCOL_SECTION__GAN_UDP,

  PROTOCOL_SECTION__GSM_RLCMAC_DL = 200,
  PROTOCOL_SECTION__GSM_RLCMAC_UL,
  
  PROTOCOL_SECTION__LLC = 300,

  PROTOCOL_SECTION__NAS = 400,
  PROTOCOL_SECTION__NAS_MM_UL,
  PROTOCOL_SECTION__NAS_MM_DL,
  PROTOCOL_SECTION__NAS_GMM_UL,
  PROTOCOL_SECTION__NAS_GMM_DL,
  PROTOCOL_SECTION__NAS_SMS_RPDU,                                                           // 405
  PROTOCOL_SECTION__NAS_SMS_TPDU,
  PROTOCOL_SECTION__NAS_SMS_TPDU_DELIVER = PROTOCOL_SECTION__NAS_SMS_TPDU,
  PROTOCOL_SECTION__NAS_SMS_TPDU_DELIVER_REPORT_ACK,
  PROTOCOL_SECTION__NAS_SMS_TPDU_DELIVER_REPORT_NACK,
  PROTOCOL_SECTION__NAS_SMS_TPDU_STATUS_REPORT,
  PROTOCOL_SECTION__NAS_SMS_TPDU_COMMAND,                                                   // 410
  PROTOCOL_SECTION__NAS_SMS_TPDU_SUBMIT,
  PROTOCOL_SECTION__NAS_SMS_TPDU_SUBMIT_REPORT_ACK,
  PROTOCOL_SECTION__NAS_SMS_TPDU_SUBMIT_REPORT_NACK,
  PROTOCOL_SECTION__NAS_SMS_TPDU_END = PROTOCOL_SECTION__NAS_SMS_TPDU_SUBMIT_REPORT_NACK,
  PROTOCOL_SECTION__NAS_CC_UL,
  PROTOCOL_SECTION__NAS_CC_DL,
  PROTOCOL_SECTION__NAS_SM,
  PROTOCOL_SECTION__NAS_END = PROTOCOL_SECTION__NAS_SM,

  /* "gsm_a_dtap" : for msg w/o pseudolength
     "gsm_a_ccch" : for msg w/ pseudolength
     "gsm_a_sacch": for short PD
   */
  PROTOCOL_SECTION__RR = 500,             /*"gsm_a_dtap"  */
  PROTOCOL_SECTION__RR_with_pseudolength, /*"gsm_a_ccch"  */
  PROTOCOL_SECTION__RR_short_PD,          /*"gsm_a_sacch" */

  PROTOCOL_SECTION__RR_dl_with_pseudolength, /*"gsm_a_ccch" */
  PROTOCOL_SECTION__RR_ul_with_pseudolength, /*"gsm_a_ccch" */

  PROTOCOL_SECTION__RR_end = PROTOCOL_SECTION__RR_ul_with_pseudolength,

  PROTOCOL_SECTION__SNDCP = 600,
  PROTOCOL_SECTION__SNDCPXID,
  
  PROTOCOL_SECTION__LTE_RRC_BCCH_BCH = 700,
  PROTOCOL_SECTION__LTE_RRC_BCCH_DL_SCH,
  PROTOCOL_SECTION__LTE_RRC_DL_CCCH,
  PROTOCOL_SECTION__LTE_RRC_DL_DCCH,
  PROTOCOL_SECTION__LTE_RRC_PCCH,
  PROTOCOL_SECTION__LTE_RRC_UL_CCCH,
  PROTOCOL_SECTION__LTE_RRC_UL_DCCH,
  
  PROTOCOL_SECTION__NAS_EPS = 800,
  PROTOCOL_SECTION__NAS_EPS_PLAIN,
  
  PROTOCOL_SECTION__RRC_BCCH_BCH = 900,
  PROTOCOL_SECTION__RRC_BCCH_FACH,
  PROTOCOL_SECTION__RRC_DL_CCCH,
  PROTOCOL_SECTION__RRC_DL_DCCH,
  PROTOCOL_SECTION__RRC_DL_SHCCH,
  PROTOCOL_SECTION__RRC_MCCH,
  PROTOCOL_SECTION__RRC_MSCH,
  PROTOCOL_SECTION__RRC_PCCH,
  PROTOCOL_SECTION__RRC_UL_CCCH,
  PROTOCOL_SECTION__RRC_UL_DCCH,
  PROTOCOL_SECTION__RRC_UL_SHCCH,
  PROTOCOL_SECTION__RRC_HANDOVER_TO_UTRAN_COMMAND,
  PROTOCOL_SECTION__RRC_IRAT_HO_INFO,
 
  PROTOCOL_SECTION__RRC_SI_MIB = 1000,
  PROTOCOL_SECTION__RRC_SI_SB1,
  PROTOCOL_SECTION__RRC_SI_SB2,
  PROTOCOL_SECTION__RRC_SI_SIB1,
  PROTOCOL_SECTION__RRC_SI_SIB2,
  PROTOCOL_SECTION__RRC_SI_SIB3,
  PROTOCOL_SECTION__RRC_SI_SIB4,
  PROTOCOL_SECTION__RRC_SI_SIB5,
  PROTOCOL_SECTION__RRC_SI_SIB5bis,
  PROTOCOL_SECTION__RRC_SI_SIB6,
  PROTOCOL_SECTION__RRC_SI_SIB7,
  PROTOCOL_SECTION__RRC_SI_SIB8,
  PROTOCOL_SECTION__RRC_SI_SIB9,
  PROTOCOL_SECTION__RRC_SI_SIB10,
  PROTOCOL_SECTION__RRC_SI_SIB11,
  PROTOCOL_SECTION__RRC_SI_SIB11bis,
  PROTOCOL_SECTION__RRC_SI_SIB12,
  PROTOCOL_SECTION__RRC_SI_SIB13,
  PROTOCOL_SECTION__RRC_SI_SIB13_1,
  PROTOCOL_SECTION__RRC_SI_SIB13_2,
  PROTOCOL_SECTION__RRC_SI_SIB13_3,
  PROTOCOL_SECTION__RRC_SI_SIB13_4,
  PROTOCOL_SECTION__RRC_SI_SIB14,
  PROTOCOL_SECTION__RRC_SI_SIB15,
  PROTOCOL_SECTION__RRC_SI_SIB15bis,
  PROTOCOL_SECTION__RRC_SI_SIB15_1,
  PROTOCOL_SECTION__RRC_SI_SIB15_1bis,
  PROTOCOL_SECTION__RRC_SI_SIB15_2,
  PROTOCOL_SECTION__RRC_SI_SIB15_2bis,
  PROTOCOL_SECTION__RRC_SI_SIB15_3,
  PROTOCOL_SECTION__RRC_SI_SIB15_3bis,
  PROTOCOL_SECTION__RRC_SI_SIB15_4,
  PROTOCOL_SECTION__RRC_SI_SIB15_5,
  PROTOCOL_SECTION__RRC_SI_SIB15_6,
  PROTOCOL_SECTION__RRC_SI_SIB15_7,
  PROTOCOL_SECTION__RRC_SI_SIB15_8,
  PROTOCOL_SECTION__RRC_SI_SIB16,  
  PROTOCOL_SECTION__RRC_SI_SIB17,
  PROTOCOL_SECTION__RRC_SI_SIB18,
  PROTOCOL_SECTION__RRC_SI_SIB19,
  PROTOCOL_SECTION__RRC_SI_SIB20,

  PROTOCOL_SECTION__LTE_LPP_UL = 1100,
  PROTOCOL_SECTION__LTE_LPP_DL,

  PROTOCOL_SECTION__UNKOWN = 2000
} PROTOCOL_SECTION;

#endif /* ~_PROTOCOL_SECTION_H */
