/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/****************************************************************************
 * PARTS OF THIS FILE ARE AUTOGENERATED
 * DO NOT EDIT EXCEPT BETWEEN LINES MARKED !BEGIN MANUAL CODE and !END MANUAL CODE
 *               Assignment :
 *               CONFIDENTIAL
 *               Copyright (c) 2000-2005, UbiNetics Ltd. All rights reserved.
 *               Cambridge Technology Centre
 *               Melbourn Royston
 *               Herts SG8 6DP UK
 *               Tel: +44 1763 262222
 *
 ****************************************************************************
 * !BEGIN MANUAL CODE! (HEADERS)
 *
 * COMPONENT:    (Insert Component Name)
 * MODULE:       $RCSfile: rsvas_utils.h,v $
 * VERSION:      $Revision: 1.0 $
 * DATED:        $Date: 2009/06/12 14:22:29 $
 * AUTHOR:
 * DESCRIPTION:  Check Header for full description
 *
 ****************************************************************************/
/* !END MANUAL CODE! (HEADERS) */
/*****************************************************************************
 * $Log:$
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 ****************************************************************************/

#if !defined(_RSVAS_UTILS_H)
#define _RSVAS_UTILS_H

#include "rsvas_enum.h"
#include "kal_general_types.h"
#include "kal_public_defs.h" //MSBB change #include "stack_config.h"
#include "kal_public_defs.h" //MSBB change #include "stack_msgs.h"


extern kal_bool rsvas_service_occupy(const module_type mod_src, const rsvas_id_enum id, const rsvas_service_type_enum service_type);

extern void rsvas_service_release(const module_type mod_src, const rsvas_id_enum id, const rsvas_service_type_enum service_type);

extern kal_bool rsvas_service_transfer(const module_type mod_src, const rsvas_id_enum new_id, const rsvas_service_type_enum reserve_domain_service_after_transfer);

extern rsvas_id_enum rsvas_service_query_as_owner(void);

extern rsvas_id_enum rsvas_idle_service_query_as_owner(void);


#ifdef __GEMINI_PREEMPT_PEER_SERVICE__
extern kal_bool is_rsvas_service_occupy_this_domain(const rsvas_service_type_enum service_type);

//extern kal_uint32 rsvas_service_occupy_count(const rsvas_service_type_enum service_type);
#endif /* __GEMINI_PREEMPT_PEER_SERVICE__ */

extern kal_bool is_rsvas_service_this_sim_occupy(const rsvas_sim_enum sim_index);

#ifdef __GEMINI_MONITOR_PAGE_DURING_TRANSFER__
/* Nicky Chou 2012/10/19: Request by GAS so that they can query whether other SIMs is in Virtual Mode. */
extern kal_bool is_rsvas_virtual_mode_query_by_sim(const rsvas_sim_enum sim_index);
#endif /* __GEMINI_MONITOR_PAGE_DURING_TRANSFER__ */

#if defined(__ETWS_SUPPORT__) || defined(__LTE_RAT__)
extern kal_bool rsvas_update_etws_channel_priority(const module_type mod_src, const rsvas_id_enum id, const kal_bool is_protect_req);

extern rsvas_id_enum rsvas_etws_owner_query(void);
#endif /* __ETWS_SUPPORT__ || __LTE_RAT__ */


/* Dennis Weng 2010/03/08: this function is used in RSVAS internel.
        other module should not use it. */
 /* Dennis Weng 2010/06/30: it should use ALLOC_SEND_ILM proposed by system service */
#if 0
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif
extern void rsvas_alloc_send_ilm(const module_type mod_src, const module_type mod_dest, const sap_type sap, const msg_type msg, void const * local_para_ptr);

#endif /* _RSVAS_UTILS_H */
