/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * ephy_rf_custom_data.c
 *
 * Project:
 * --------
 * MT6290
 *
 * Description:
 * ------------
 * EL1 RF Custom Data
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *----------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *----------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/*===============================================================================*/

#include "kal_general_types.h"
#include "kal_public_api.h"

#include "el1_rf_public.h"
#include "el1_rf_common.h"

#include "ephy_rf_custom_data.h"
#include "lte_custom_mipi.h"
#include "lte_custom_drdi.h"   // for DRDI feature
#include "lte_custom_rf.h"

/*===============================================================================*/

kal_uint8 num_pa_mode = NUM_PA_MODE;

kal_uint8 num_hysteresis = NUM_HYSTERESIS;

#if defined(IS_MIPI_FRONT_END_ENABLE)
kal_uint16 LTE_MIPI_ENABLE = IS_MIPI_FRONT_END_ENABLE;
#else
kal_uint16 LTE_MIPI_ENABLE = 0;
#endif

#if defined(IS_DISABLE_BAND_INFO_ENABLE)
kal_uint16 DISABLE_BAND_INFO_ENABLE = IS_DISABLE_BAND_INFO_ENABLE;
#else
kal_uint16 DISABLE_BAND_INFO_ENABLE = 0;
#endif

/* DRDI feature ENABLE/DISABLE */
/**
 * @brief DRDI status for debuging
 * 
 * bit[0] : EL1_CUSTOM_DYNAMIC_INIT_ENABLE
 * bit[15]: NVRAM updated indicator: if DRDI has been executed and NVRAM has been updated, 
 *          set bit15 = 1
 */
#if EL1_CUSTOM_DYNAMIC_INIT_ENABLE
kal_uint16 LTE_DRDI_STATUS      = 0x1;
#else
kal_uint16 LTE_DRDI_STATUS      = 0x0;
#endif


/* Single ANT Feature */
ERf_RX_PATH_CONFIG_T LTE_RF_RX_PATH_CONFIG_DEFAULT = {1/*RXP0EN*/, 1/*RXP1EN*/};

/* DSDA Dual Talk feature usage */
kal_uint8  is_dsda_provide_rx_status_to_gsm_enable = IS_DSDA_PROVIDE_RX_STATUS_TO_GSM_ENABLE;
kal_uint8  is_dsda_lte_tx_filter_path_switch_enable = IS_DSDA_LTE_TX_FILTER_PATH_SWITCH_ENABLE;
/*** MIPI BYPASS FEATURE ***/
#if defined(IS_MIPI_BYPASS_FEATURE_ENABLE)
kal_uint16 LTE_MIPI_BYPASS_FEATURE_ENABLE = IS_MIPI_BYPASS_FEATURE_ENABLE;
#else
kal_uint16 LTE_MIPI_BYPASS_FEATURE_ENABLE = 0;
#endif

#if IS_4G_TX_POWER_OFFSET_SUPPORT
ERf_TPO_SETTING LTE_TPO_CUSTOM_INPUT_DATA =
{
   /* Tx power offset */
   {
      TPO_4G_ENABLE,
      TPO_4G_META_ENABLE,
      TPO_4G_TABLE_ON_MASK,
      {
         TPO_4G_BIT_NUM_FOR_TABLE_0,
         TPO_4G_BIT_NUM_FOR_TABLE_1
      }
   },	
};
#endif

LTE_Band LTE_MIPI_BYPASS_BandIndArray[LTE_MIPI_BYPASS_MAX_SUPPORT_BAND_NUM] =
{
   LTE_MIPI_BYPASS_BAND_INDICATOR1,
   LTE_MIPI_BYPASS_BAND_INDICATOR2,
   LTE_MIPI_BYPASS_BAND_INDICATOR3,
   LTE_MIPI_BYPASS_BAND_INDICATOR4,
   LTE_MIPI_BYPASS_BAND_INDICATOR5,
};
kal_int16 LTE_MIPI_BYPASS_PowerCompArray[LTE_MIPI_BYPASS_MAX_SUPPORT_BAND_NUM] =
{
   LTE_MIPI_BYPASS_BAND_INDICATOR1_POWER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR2_POWER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR3_POWER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR4_POWER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR5_POWER_COMP,
};
kal_int16 LTE_MIPI_BYPASS_CouplerCompArray[LTE_MIPI_BYPASS_MAX_SUPPORT_BAND_NUM] =
{
   LTE_MIPI_BYPASS_BAND_INDICATOR1_COUPLER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR2_COUPLER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR3_COUPLER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR4_COUPLER_COMP,
   LTE_MIPI_BYPASS_BAND_INDICATOR5_COUPLER_COMP,
};

/*===============================================================================*/
LTE_Band lteBandIndArray[LTE_AUGMENTED_BAND_ARRAY_NUM] =
{
   LTE_BandNone,
   BAND_INDICATOR1,
   BAND_INDICATOR2,
   BAND_INDICATOR3,
   BAND_INDICATOR4,
   BAND_INDICATOR5,
   BAND_INDICATOR6,
   BAND_INDICATOR7,
   BAND_INDICATOR8,
   BAND_INDICATOR9,
   BAND_INDICATOR10,
   BAND_INDICATOR11,
   BAND_INDICATOR12,
   BAND_INDICATOR13,
   BAND_INDICATOR14,
};

/*===============================================================================*/

ERF_RXON_BSIOFFSET_T ERF_RXON_BSIOFFSET_TABLE =
{
   TC_FSR0,
   TC_FSR1,
   TC_FSR2,
   TC_TSR0,
   TC_TSR2,
   TC_SR2G,
   TC_SR2S,
   TC_SR2F,
};

ERF_RXOFF_BSIOFFSET_T ERF_RXOFF_BSIOFFSET_TABLE =
{
   TC_FSR3,
   TC_TSR3,
};

ERF_TXON_BSIOFFSET_T ERF_TXON_BSIOFFSET_TABLE =
{
   TC_FST0,
   TC_FST1,
   TC_FST2,
   TC_TST2,
   TC_ST2S,
   TC_ST2F,
};


ERF_TXOFF_BSIOFFSET_T ERF_TXOFF_BSIOFFSET_TABLE =
{
   TC_FST3,
   TC_TST3,
};

ERF_SXCTRL_OFFSET_T ERF_SXCTRL_OFFSET_TABLE =
{
   TC_STX1,
   TC_STX3,
   TC_SRX1,
   TC_SRX3,
};

ERF_TPC_OFFSET_T ERF_TPC_OFFSET_TABLE =
{
   TC_STPC0,
   TC_STPC1,
   TC_SPTPC0,
   TC_SPTPC1,
   TC_SMTPC0,
   TC_SMTPC1,
   TC_PTPC0,
   TC_PTPC1,
};


//////////////////////////////////////////////

ERF_RXON_BPIOFFSET_T ERF_RXON_BPIOFFSET =
{
   TC_FPR0,
   TC_FPR1,
   TC_FPR2,
   TC_TPR0,
   TC_TPR1,
   TC_TPR2,  
};

ERF_TXON_BPIOFFSET_T ERF_TXON_BPIOFFSET =
{
   TC_FPT0,
   TC_FPT1,
   TC_FPT2,
   TC_FPR3B,
   TC_TPT0,
   TC_TPT1,
   TC_TPT2,
   TC_TPR3B,
};

ERF_RXOFF_BPIOFFSET_T ERF_RXOFF_BPIOFFSET =
{
   TC_FPR3,
   TC_TPR3,
   TC_FPR3C,
   TC_TPR3C,
};

ERF_TXOFF_BPIOFFSET_T ERF_TXOFF_BPIOFFSET =
{
   TC_FPT3,
   TC_TPT3,
};


//////////////////////////////////////////////


ERF_RX_PDATABASE_T ERF_RX_PDATABASE[LTE_TARGET_MAX_SUPPORT_BAND_NUM] = 
{
   {  BAND_INDICATOR1, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR1))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR1))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR1))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR2, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR2))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR2))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR2))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR3, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR3))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR3))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR3))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR4, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR4))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR4))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR4))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR5, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR5))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR5))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR5))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR6, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR6))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR6))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR6))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR7, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR7))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR7))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR7))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR8, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR8))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR8))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR8))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR9, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR9))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR9))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR9))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR10, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR10))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR10))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR10))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR11, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR11))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR11))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR11))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR12, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR12))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR12))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR12))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR13, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR13))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR13))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR13))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   {  BAND_INDICATOR14, 
      {
         {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
         {GET_16H((LTE_PDATA_PR1(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PR1(BAND_INDICATOR14))) },
         {GET_16H((LTE_PDATA_PR2(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PR2(BAND_INDICATOR14))) },
         {GET_16H((LTE_PDATA_PR3(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PR3(BAND_INDICATOR14))) },
         {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
         {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
      }
   },
   //End of PDATA table
   //{  LTE_BandNone, {{0,0}, {0,0}, {0,0}, {0,0}, {0,0}} }                  
};


ERF_TX_PDATABASE_T ERF_TX_PDATABASE[LTE_TARGET_MAX_SUPPORT_BAND_NUM] = 
{
   {  BAND_INDICATOR1, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR1))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR1))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR1))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR1))) }
      }
   },
   {  BAND_INDICATOR2, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR2))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR2))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR2))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR2))) }
      }
   },
   {  BAND_INDICATOR3, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR3))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR3))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR3))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR3))) }
      }
   },
   {  BAND_INDICATOR4, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR4))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR4))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR4))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR4))) }
      }
   },
   {  BAND_INDICATOR5, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR5))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR5))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR5))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR5))) }
      }
   },
   {  BAND_INDICATOR6, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR6))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR6))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR6))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR6))) }
      }
   },
   {  BAND_INDICATOR7, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR7))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR7))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR7))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR7))) }
      }
   },
   {  BAND_INDICATOR8, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR8))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR8))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR8))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR8))) }
      }
   },
   {  BAND_INDICATOR9, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR9))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR9))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR9))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR9))) }
      }
   },
   {  BAND_INDICATOR10, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR10))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR10))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR10))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR10))) }
      }
   },
   {  BAND_INDICATOR11, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR11))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR11))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR11))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR11))) }
      }
   },
   {  BAND_INDICATOR12, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR12))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR12))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR12))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR12))) }
      }
   },
   {  BAND_INDICATOR13, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR13))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR13))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR13))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR13))) }
      }
   },
   {  BAND_INDICATOR14, 
      {
         {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
         {GET_16H((LTE_PDATA_PT1(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PT1(BAND_INDICATOR14))) },
         {GET_16H((LTE_PDATA_PT2(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PT2(BAND_INDICATOR14))) },
         {GET_16H((LTE_PDATA_PT3(BAND_INDICATOR14))), GET_16L((LTE_PDATA_PT3(BAND_INDICATOR14))) }
      }
   },
   //End of PDATA table
   //{  LTE_BandNone, {{0,0}, {0,0}, {0,0}, {0,0}} }                  
};

ERF_IOBASE_T ERF_RF_IOBASE[LTE_TARGET_MAX_SUPPORT_BAND_NUM] = 
{
   { BAND_INDICATOR1 , (LTE_RX_IO(BAND_INDICATOR1)) ,  (LTE_RXD_IO(BAND_INDICATOR1)) ,  (LTE_TX_IO(BAND_INDICATOR1)) ,  },
   { BAND_INDICATOR2 , (LTE_RX_IO(BAND_INDICATOR2)) ,  (LTE_RXD_IO(BAND_INDICATOR2)) ,  (LTE_TX_IO(BAND_INDICATOR2)) ,  },
   { BAND_INDICATOR3 , (LTE_RX_IO(BAND_INDICATOR3)) ,  (LTE_RXD_IO(BAND_INDICATOR3)) ,  (LTE_TX_IO(BAND_INDICATOR3)) ,  },
   { BAND_INDICATOR4 , (LTE_RX_IO(BAND_INDICATOR4)) ,  (LTE_RXD_IO(BAND_INDICATOR4)) ,  (LTE_TX_IO(BAND_INDICATOR4)) ,  },
   { BAND_INDICATOR5 , (LTE_RX_IO(BAND_INDICATOR5)) ,  (LTE_RXD_IO(BAND_INDICATOR5)) ,  (LTE_TX_IO(BAND_INDICATOR5)) ,  },
   { BAND_INDICATOR6 , (LTE_RX_IO(BAND_INDICATOR6)) ,  (LTE_RXD_IO(BAND_INDICATOR6)) ,  (LTE_TX_IO(BAND_INDICATOR6)) ,  },
   { BAND_INDICATOR7 , (LTE_RX_IO(BAND_INDICATOR7)) ,  (LTE_RXD_IO(BAND_INDICATOR7)) ,  (LTE_TX_IO(BAND_INDICATOR7)) ,  },
   { BAND_INDICATOR8 , (LTE_RX_IO(BAND_INDICATOR8)) ,  (LTE_RXD_IO(BAND_INDICATOR8)) ,  (LTE_TX_IO(BAND_INDICATOR8)) ,  },
   { BAND_INDICATOR9 , (LTE_RX_IO(BAND_INDICATOR9)) ,  (LTE_RXD_IO(BAND_INDICATOR9)) ,  (LTE_TX_IO(BAND_INDICATOR9)) ,  },
   { BAND_INDICATOR10, (LTE_RX_IO(BAND_INDICATOR10)),  (LTE_RXD_IO(BAND_INDICATOR10)),  (LTE_TX_IO(BAND_INDICATOR10)),  },
   { BAND_INDICATOR11, (LTE_RX_IO(BAND_INDICATOR11)),  (LTE_RXD_IO(BAND_INDICATOR11)),  (LTE_TX_IO(BAND_INDICATOR11)),  },
   { BAND_INDICATOR12, (LTE_RX_IO(BAND_INDICATOR12)),  (LTE_RXD_IO(BAND_INDICATOR12)),  (LTE_TX_IO(BAND_INDICATOR12)),  },
   { BAND_INDICATOR13, (LTE_RX_IO(BAND_INDICATOR13)),  (LTE_RXD_IO(BAND_INDICATOR13)),  (LTE_TX_IO(BAND_INDICATOR13)),  },
   { BAND_INDICATOR14, (LTE_RX_IO(BAND_INDICATOR14)),  (LTE_RXD_IO(BAND_INDICATOR14)),  (LTE_TX_IO(BAND_INDICATOR14)),  },

};

ERF_SPLIT_BAND_IND_T LTE_SPLIT_BAND_IND[LTE_ERF_SPLIT_BAND] = 
{
   {  //Band28
      BAND_SPLIT_INDICATOR1, BAND_SPLIT_INDICATOR1_NUM,
      {  BAND_SPLIT_INDICATOR1_DL_END1, BAND_SPLIT_INDICATOR1_DL_END2, BAND_SPLIT_INDICATOR1_DL_END3  }, //DL, Uint: 100KHz
      {  BAND_SPLIT_INDICATOR1_UL_END1, BAND_SPLIT_INDICATOR1_UL_END2, BAND_SPLIT_INDICATOR1_UL_END3  }, //UL, Uint: 100KHz
      BAND_INDICATOR1_POWER_COMP,                                                                        //power compensation, Unit: S(6,8) dB
      BAND_INDICATOR1_COUPLER_COMP,                                                                      //coupler compensation, Unit: S(6,8) dB
   },
   {  //Band41
      BAND_SPLIT_INDICATOR2, BAND_SPLIT_INDICATOR2_NUM,
      {  BAND_SPLIT_INDICATOR2_DL_END1, BAND_SPLIT_INDICATOR2_DL_END2, BAND_SPLIT_INDICATOR2_DL_END3  }, //DL, Uint: 100KHz
      {  BAND_SPLIT_INDICATOR2_UL_END1, BAND_SPLIT_INDICATOR2_UL_END2, BAND_SPLIT_INDICATOR2_UL_END3  }, //UL, Uint: 100KHz
      BAND_INDICATOR2_POWER_COMP,                                                                        //power compensation, Unit: S(6,8) dB
      BAND_INDICATOR2_COUPLER_COMP,                                                                      //coupler compensation, Unit: S(6,8) dB
   },
   {  //Reserved
      BAND_SPLIT_INDICATOR3, BAND_SPLIT_INDICATOR3_NUM,
      {  BAND_SPLIT_INDICATOR3_DL_END1, BAND_SPLIT_INDICATOR3_DL_END2, BAND_SPLIT_INDICATOR3_DL_END3  }, //DL, Uint: 100KHz
      {  BAND_SPLIT_INDICATOR3_UL_END1, BAND_SPLIT_INDICATOR3_UL_END2, BAND_SPLIT_INDICATOR3_UL_END3  }, //UL, Uint: 100KHz
      BAND_INDICATOR3_POWER_COMP,                                                                        //power compensation, Unit: S(6,8) dB
      BAND_INDICATOR3_COUPLER_COMP,                                                                      //coupler compensation, Unit: S(6,8) dB
   },
   {  //Reserved
      BAND_SPLIT_INDICATOR4, BAND_SPLIT_INDICATOR4_NUM,
      {  BAND_SPLIT_INDICATOR4_DL_END1, BAND_SPLIT_INDICATOR4_DL_END2, BAND_SPLIT_INDICATOR4_DL_END3  }, //DL, Uint: 100KHz
      {  BAND_SPLIT_INDICATOR4_UL_END1, BAND_SPLIT_INDICATOR4_UL_END2, BAND_SPLIT_INDICATOR4_UL_END3  }, //UL, Uint: 100KHz
      BAND_INDICATOR4_POWER_COMP,                                                                        //power compensation, Unit: S(6,8) dB
      BAND_INDICATOR4_COUPLER_COMP,                                                                      //coupler compensation, Unit: S(6,8) dB
   },
   {  //Reserved
      BAND_SPLIT_INDICATOR5, BAND_SPLIT_INDICATOR5_NUM,
      {  BAND_SPLIT_INDICATOR5_DL_END1, BAND_SPLIT_INDICATOR5_DL_END2, BAND_SPLIT_INDICATOR5_DL_END3  }, //DL, Uint: 100KHz
      {  BAND_SPLIT_INDICATOR5_UL_END1, BAND_SPLIT_INDICATOR5_UL_END2, BAND_SPLIT_INDICATOR5_UL_END3  }, //UL, Uint: 100KHz
      BAND_INDICATOR5_POWER_COMP,                                                                        //power compensation, Unit: S(6,8) dB
      BAND_INDICATOR5_COUPLER_COMP,                                                                      //coupler compensation, Unit: S(6,8) dB
   },
};

ERF_SPLIT_RFDATABASE_T ERF_SPLIT_RFDATABASE[LTE_ERF_SPLIT_NUM] = 
{
   {  BAND_SPLIT_INDICATOR1,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR1)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR1)))},
         (kal_uint16)(((LTE_RXD_2_IO(BAND_SPLIT_INDICATOR1))<<8)|(LTE_RX_2_IO(BAND_SPLIT_INDICATOR1))),
         (kal_uint16)(LTE_TX_2_IO(BAND_SPLIT_INDICATOR1))
      },
   },
   {  BAND_SPLIT_INDICATOR1,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR1)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR1)))},
         (kal_uint16)(((LTE_RXD_3_IO(BAND_SPLIT_INDICATOR1))<<8)|(LTE_RX_3_IO(BAND_SPLIT_INDICATOR1))),
         (kal_uint16)(LTE_TX_3_IO(BAND_SPLIT_INDICATOR1))
      },
   },
   {  BAND_SPLIT_INDICATOR1,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                           GET_16L(PDATA_LTE_BANDX_PR0)                          },
         {GET_16H((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR1)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                          GET_16L(PDATA_LTE_BANDX_PR3B)                         },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                          GET_16L(PDATA_LTE_BANDX_PR3C)                         },
         {GET_16H(PDATA_LTE_BANDX_PT0),                           GET_16L(PDATA_LTE_BANDX_PT0)                          },
         {GET_16H((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR1)))},
         {GET_16H((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR1))), GET_16L((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR1)))},
         (kal_uint16)(((LTE_RXD_BYPASS_IO(BAND_SPLIT_INDICATOR1))<<8)|(LTE_RX_BYPASS_IO(BAND_SPLIT_INDICATOR1))),
         (kal_uint16)(LTE_TX_BYPASS_IO(BAND_SPLIT_INDICATOR1))
      },
   },
   {  BAND_SPLIT_INDICATOR2,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR2)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR2)))},
         (kal_uint16)(((LTE_RXD_2_IO(BAND_SPLIT_INDICATOR2))<<8)|(LTE_RX_2_IO(BAND_SPLIT_INDICATOR2))),
         (kal_uint16)(LTE_TX_2_IO(BAND_SPLIT_INDICATOR2))
      },
   },
   {  BAND_SPLIT_INDICATOR2,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR2)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR2)))},
         (kal_uint16)(((LTE_RXD_3_IO(BAND_SPLIT_INDICATOR2))<<8)|(LTE_RX_3_IO(BAND_SPLIT_INDICATOR2))),
         (kal_uint16)(LTE_TX_3_IO(BAND_SPLIT_INDICATOR2))
      },
   },
   {  BAND_SPLIT_INDICATOR2,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                           GET_16L(PDATA_LTE_BANDX_PR0)                          },
         {GET_16H((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR2)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                          GET_16L(PDATA_LTE_BANDX_PR3B)                         },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                          GET_16L(PDATA_LTE_BANDX_PR3C)                         },
         {GET_16H(PDATA_LTE_BANDX_PT0),                           GET_16L(PDATA_LTE_BANDX_PT0)                          },
         {GET_16H((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR2)))},
         {GET_16H((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR2))), GET_16L((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR2)))},
         (kal_uint16)(((LTE_RXD_BYPASS_IO(BAND_SPLIT_INDICATOR2))<<8)|(LTE_RX_BYPASS_IO(BAND_SPLIT_INDICATOR2))),
         (kal_uint16)(LTE_TX_BYPASS_IO(BAND_SPLIT_INDICATOR2))
      },
   },
   {  BAND_SPLIT_INDICATOR3,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR3)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR3)))},
         (kal_uint16)(((LTE_RXD_2_IO(BAND_SPLIT_INDICATOR3))<<8)|(LTE_RX_2_IO(BAND_SPLIT_INDICATOR3))),
         (kal_uint16)(LTE_TX_2_IO(BAND_SPLIT_INDICATOR3))
      },
   },
   {  BAND_SPLIT_INDICATOR3,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR3)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR3)))},
         (kal_uint16)(((LTE_RXD_3_IO(BAND_SPLIT_INDICATOR3))<<8)|(LTE_RX_3_IO(BAND_SPLIT_INDICATOR3))),
         (kal_uint16)(LTE_TX_3_IO(BAND_SPLIT_INDICATOR3))
      },
   },
   {  BAND_SPLIT_INDICATOR3,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                           GET_16L(PDATA_LTE_BANDX_PR0)                          },
         {GET_16H((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR3)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                          GET_16L(PDATA_LTE_BANDX_PR3B)                         },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                          GET_16L(PDATA_LTE_BANDX_PR3C)                         },
         {GET_16H(PDATA_LTE_BANDX_PT0),                           GET_16L(PDATA_LTE_BANDX_PT0)                          },
         {GET_16H((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR3)))},
         {GET_16H((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR3))), GET_16L((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR3)))},
         (kal_uint16)(((LTE_RXD_BYPASS_IO(BAND_SPLIT_INDICATOR3))<<8)|(LTE_RX_BYPASS_IO(BAND_SPLIT_INDICATOR3))),
         (kal_uint16)(LTE_TX_BYPASS_IO(BAND_SPLIT_INDICATOR3))
      },
   },
   {  BAND_SPLIT_INDICATOR4,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR4)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR4)))},
         (kal_uint16)(((LTE_RXD_2_IO(BAND_SPLIT_INDICATOR4))<<8)|(LTE_RX_2_IO(BAND_SPLIT_INDICATOR4))),
         (kal_uint16)(LTE_TX_2_IO(BAND_SPLIT_INDICATOR4))
      },
   },
   {  BAND_SPLIT_INDICATOR4,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR4)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR4)))},
         (kal_uint16)(((LTE_RXD_3_IO(BAND_SPLIT_INDICATOR4))<<8)|(LTE_RX_3_IO(BAND_SPLIT_INDICATOR4))),
         (kal_uint16)(LTE_TX_3_IO(BAND_SPLIT_INDICATOR4))
      },
   },
   {  BAND_SPLIT_INDICATOR4,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                           GET_16L(PDATA_LTE_BANDX_PR0)                          },
         {GET_16H((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR4)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                          GET_16L(PDATA_LTE_BANDX_PR3B)                         },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                          GET_16L(PDATA_LTE_BANDX_PR3C)                         },
         {GET_16H(PDATA_LTE_BANDX_PT0),                           GET_16L(PDATA_LTE_BANDX_PT0)                          },
         {GET_16H((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR4)))},
         {GET_16H((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR4))), GET_16L((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR4)))},
         (kal_uint16)(((LTE_RXD_BYPASS_IO(BAND_SPLIT_INDICATOR4))<<8)|(LTE_RX_BYPASS_IO(BAND_SPLIT_INDICATOR4))),
         (kal_uint16)(LTE_TX_BYPASS_IO(BAND_SPLIT_INDICATOR4))
      },
   },
   {  BAND_SPLIT_INDICATOR5,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR1_2(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR2_2(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR3_2(BAND_SPLIT_INDICATOR5)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT1_2(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT2_2(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT3_2(BAND_SPLIT_INDICATOR5)))},
         (kal_uint16)(((LTE_RXD_2_IO(BAND_SPLIT_INDICATOR5))<<8)|(LTE_RX_2_IO(BAND_SPLIT_INDICATOR5))),
         (kal_uint16)(LTE_TX_2_IO(BAND_SPLIT_INDICATOR5))
      },
   },
   {  BAND_SPLIT_INDICATOR5,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                      GET_16L(PDATA_LTE_BANDX_PR0)                     },
         {GET_16H((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR1_3(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR2_3(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR3_3(BAND_SPLIT_INDICATOR5)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                     GET_16L(PDATA_LTE_BANDX_PR3B)                    },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                     GET_16L(PDATA_LTE_BANDX_PR3C)                    },
         {GET_16H(PDATA_LTE_BANDX_PT0),                      GET_16L(PDATA_LTE_BANDX_PT0)                     },
         {GET_16H((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT1_3(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT2_3(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT3_3(BAND_SPLIT_INDICATOR5)))},
         (kal_uint16)(((LTE_RXD_3_IO(BAND_SPLIT_INDICATOR5))<<8)|(LTE_RX_3_IO(BAND_SPLIT_INDICATOR5))),
         (kal_uint16)(LTE_TX_3_IO(BAND_SPLIT_INDICATOR5))
      },
   },
   {  BAND_SPLIT_INDICATOR5,
      {
         {GET_16H(PDATA_LTE_BANDX_PR0),                           GET_16L(PDATA_LTE_BANDX_PR0)                          },
         {GET_16H((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR1_BYPASS(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR2_BYPASS(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PR3_BYPASS(BAND_SPLIT_INDICATOR5)))},
         {GET_16H(PDATA_LTE_BANDX_PR3B),                          GET_16L(PDATA_LTE_BANDX_PR3B)                         },
         {GET_16H(PDATA_LTE_BANDX_PR3C),                          GET_16L(PDATA_LTE_BANDX_PR3C)                         },
         {GET_16H(PDATA_LTE_BANDX_PT0),                           GET_16L(PDATA_LTE_BANDX_PT0)                          },
         {GET_16H((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT1_BYPASS(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT2_BYPASS(BAND_SPLIT_INDICATOR5)))},
         {GET_16H((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR5))), GET_16L((LTE_PDATA_PT3_BYPASS(BAND_SPLIT_INDICATOR5)))},
         (kal_uint16)(((LTE_RXD_BYPASS_IO(BAND_SPLIT_INDICATOR5))<<8)|(LTE_RX_BYPASS_IO(BAND_SPLIT_INDICATOR5))),
         (kal_uint16)(LTE_TX_BYPASS_IO(BAND_SPLIT_INDICATOR5))
      },
   },
};

EL1_TAS_PARAMETER EL1_TAS_PARAMETER_TABLE =
{
   {  // ERF_TAS_BAND_IND_T
      LTE_TAS_ENA,
      LTE_TAS_WITH_TEST_SIM_ENA,
      GET_16H(LTE_TAS_MASK),
      GET_16L(LTE_TAS_MASK),
      LTE_TAS_INIT_ANT,
      LTE_FORCE_TX_ANTENNA_ENABLE,
      LTE_FORCE_TX_ANTENNA_IDX,
      {
         BAND_TAS_INDICATOR1,
         BAND_TAS_INDICATOR2,
         BAND_TAS_INDICATOR3,
         BAND_TAS_INDICATOR4,
         BAND_TAS_INDICATOR5,
         BAND_TAS_INDICATOR6,
         BAND_TAS_INDICATOR7,
         BAND_TAS_INDICATOR8,
         BAND_TAS_INDICATOR9,
         BAND_TAS_INDICATOR10,
         BAND_TAS_INDICATOR11,
         BAND_TAS_INDICATOR12,
         BAND_TAS_INDICATOR13,
         BAND_TAS_INDICATOR14,
      },
   },
   {  // ERF_TAS_RFDATA_T
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR1))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR1))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR2))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR2))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR3))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR3))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR4))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR4))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR5))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR5))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR6))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR6))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR7))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR7))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR8))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR8))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR9))),  GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR9))) },
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR10))), GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR10)))},
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR11))), GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR11)))},
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR12))), GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR12)))},
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR13))), GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR13)))},
      {GET_16H((LTE_PDATA_TAS1(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS1(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS2(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS2(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS3(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS3(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS4(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS4(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS5(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS5(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS6(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS6(BAND_TAS_INDICATOR14)))},
      {GET_16H((LTE_PDATA_TAS7(BAND_TAS_INDICATOR14))), GET_16L((LTE_PDATA_TAS7(BAND_TAS_INDICATOR14)))},
   },
};

/* Define _BandNone for dummy BandNone setting */
const ERF_RX_PDATABASE_T ERF_RX_PDATABASE_BandNone = 
{
   LTE_BandNone, 
   {
      {GET_16H(PDATA_LTE_BANDX_PR0), GET_16L(PDATA_LTE_BANDX_PR0) },
      {GET_16H((LTE_PDATA_PR1(LTE_BandNone))), GET_16L((LTE_PDATA_PR1(LTE_BandNone))) },
      {GET_16H((LTE_PDATA_PR2(LTE_BandNone))), GET_16L((LTE_PDATA_PR2(LTE_BandNone))) },
      {GET_16H((LTE_PDATA_PR3(LTE_BandNone))), GET_16L((LTE_PDATA_PR3(LTE_BandNone))) },
      {GET_16H(PDATA_LTE_BANDX_PR3B),GET_16L(PDATA_LTE_BANDX_PR3B)},
      {GET_16H(PDATA_LTE_BANDX_PR3C),GET_16L(PDATA_LTE_BANDX_PR3C)},
   }
};

const ERF_TX_PDATABASE_T ERF_TX_PDATABASE_BandNone = 
{
   LTE_BandNone, 
   {
      {GET_16H(PDATA_LTE_BANDX_PT0), GET_16L(PDATA_LTE_BANDX_PT0) },
      {GET_16H((LTE_PDATA_PT1(LTE_BandNone))), GET_16L((LTE_PDATA_PT1(LTE_BandNone))) },
      {GET_16H((LTE_PDATA_PT2(LTE_BandNone))), GET_16L((LTE_PDATA_PT2(LTE_BandNone))) },
      {GET_16H((LTE_PDATA_PT3(LTE_BandNone))), GET_16L((LTE_PDATA_PT3(LTE_BandNone))) }
   }
};

const ERF_IOBASE_T ERF_RF_IOBASE_BandNone = 
{
   LTE_BandNone, (LTE_RX_IO(LTE_BandNone)),  (LTE_RXD_IO(LTE_BandNone)),  (LTE_TX_IO(LTE_BandNone))
};



/******************************************************************************
 * Dynamic Radio-setting Dedicated Image
 *
 * Description: Initialize global variables for EPHY calculation
 ******************************************************************************/
kal_uint8  el1_custom_debug_enable                   = EL1_CUSTOM_DEBUG_ENABLE;
kal_uint8  el1_custom_gpio_set_nums                  = EL1_CUSTOM_GPIO_SET_NUMS;            
kal_uint8  el1_custom_adc_set_nums                   = EL1_CUSTOM_ADC_SET_NUMS;             
kal_uint8  el1_custom_nvram_barcode_set_nums         = EL1_CUSTOM_BARCODE_SET_NUMS;   
kal_uint8  el1_custom_gpio_nums_in_calc              = EL1_CUSTOM_GPIO_NUMS_IN_CALC;
kal_uint8  el1_custom_ADC_nums_in_calc               = EL1_CUSTOM_ADC_NUMS_IN_CALC;
kal_uint8  el1_custom_barcode_nums_in_calc           = EL1_CUSTOM_BARCODE_NUMS_IN_CALC;
kal_uint8  el1_custom_first_index                    = EL1_CUSTOM_FIRST_INDEX;
kal_uint8  el1_custom_second_index                   = EL1_CUSTOM_SECOND_INDEX;
kal_uint8  el1_custom_third_index                    = EL1_CUSTOM_THIRD_INDEX;
kal_uint8  el1_custom_first_index_base               = EL1_CUSTOM_FIRST_INDEX_BASE;
kal_uint8  el1_custom_gpio_num_of_detect_pins_in_use = EL1_CUSTOM_GPIO_NUM_OF_DETECT_PINS_IN_USE;
kal_uint8  el1_custom_adc_level_total                = EL1_CUSTOM_ADC_LEVEL_TOTAL;
kal_uint8  el1_custom_barcode_read_digit_num         = EL1_CUSTOM_BARCODE_READ_DIGIT_NUM;
kal_uint8  el1_custom_barcode_digit_value_1          = EL1_CUSTOM_BARCODE_DIGIT_VALUE_1;
kal_uint8  el1_custom_barcode_digit_value_2          = EL1_CUSTOM_BARCODE_DIGIT_VALUE_2;
kal_uint8  el1_custom_barcode_digit_value_3          = EL1_CUSTOM_BARCODE_DIGIT_VALUE_3;
kal_uint8  el1_custom_max_rf_support_band_num        = EL1_CUSTOM_MAX_RF_SUPPORT_BAND_NUM;
kal_uint8  el1_custom_adc_calibrate_enable           = EL1_CUSTOM_ADC_CALIBRATE_ENABLE;
kal_uint8  el1_custom_adc_bits                       = EL1_CUSTOM_ADC_BITS;
kal_uint16 el1_custom_adc_meas_count_2_order         = EL1_CUSTOM_ADC_MEAS_COUNT_2_ORDER;
kal_uint16 el1_custom_total_set_nums                 = EL1_CUSTOM_TOTAL_SET_NUMS;
kal_uint32 el1_custom_adc_max_input_voltage          = EL1_CUSTOM_ADC_MAX_INPUT_VOLTAGE;
/*------------- Dynamic Radio-setting Dedicated Image -------------*/


/******************************************************************************
 * MPR   Table: refer to 36.101 6.2.3 6.2.5
 * A-MPR Table: refer to 36.101 6.2.4 6.2.5
 * Description: record MPR and A-MPR value for each band
 ******************************************************************************/
LTE_MPRAdjust_T LTE_MPRAdjustTbl[LTE_TARGET_MAX_SUPPORT_BAND_NUM] = 
{
    { BAND_INDICATOR1,  LTE_MPR_QPSK1(BAND_INDICATOR1), LTE_MPR_16QAM0(BAND_INDICATOR1), LTE_MPR_16QAM1(BAND_INDICATOR1),
                        LTE_DELTA_TC0(BAND_INDICATOR1), LTE_DELTA_TC1(BAND_INDICATOR1)  },
    { BAND_INDICATOR2,  LTE_MPR_QPSK1(BAND_INDICATOR2), LTE_MPR_16QAM0(BAND_INDICATOR2), LTE_MPR_16QAM1(BAND_INDICATOR2),
                        LTE_DELTA_TC0(BAND_INDICATOR2), LTE_DELTA_TC1(BAND_INDICATOR2)  },
    { BAND_INDICATOR3,  LTE_MPR_QPSK1(BAND_INDICATOR3), LTE_MPR_16QAM0(BAND_INDICATOR3), LTE_MPR_16QAM1(BAND_INDICATOR3),
                        LTE_DELTA_TC0(BAND_INDICATOR3), LTE_DELTA_TC1(BAND_INDICATOR3)  },
    { BAND_INDICATOR4,  LTE_MPR_QPSK1(BAND_INDICATOR4), LTE_MPR_16QAM0(BAND_INDICATOR4), LTE_MPR_16QAM1(BAND_INDICATOR4),
                        LTE_DELTA_TC0(BAND_INDICATOR4), LTE_DELTA_TC1(BAND_INDICATOR4)  },
    { BAND_INDICATOR5,  LTE_MPR_QPSK1(BAND_INDICATOR5), LTE_MPR_16QAM0(BAND_INDICATOR5), LTE_MPR_16QAM1(BAND_INDICATOR5),
                        LTE_DELTA_TC0(BAND_INDICATOR5), LTE_DELTA_TC1(BAND_INDICATOR5)  },
    { BAND_INDICATOR6,  LTE_MPR_QPSK1(BAND_INDICATOR6), LTE_MPR_16QAM0(BAND_INDICATOR6), LTE_MPR_16QAM1(BAND_INDICATOR6),
                        LTE_DELTA_TC0(BAND_INDICATOR6), LTE_DELTA_TC1(BAND_INDICATOR6)  },
    { BAND_INDICATOR7,  LTE_MPR_QPSK1(BAND_INDICATOR7), LTE_MPR_16QAM0(BAND_INDICATOR7), LTE_MPR_16QAM1(BAND_INDICATOR7),
                        LTE_DELTA_TC0(BAND_INDICATOR7), LTE_DELTA_TC1(BAND_INDICATOR7)  },
    { BAND_INDICATOR8,  LTE_MPR_QPSK1(BAND_INDICATOR8), LTE_MPR_16QAM0(BAND_INDICATOR8), LTE_MPR_16QAM1(BAND_INDICATOR8),
                        LTE_DELTA_TC0(BAND_INDICATOR8), LTE_DELTA_TC1(BAND_INDICATOR8)  },
    { BAND_INDICATOR9,  LTE_MPR_QPSK1(BAND_INDICATOR9), LTE_MPR_16QAM0(BAND_INDICATOR9), LTE_MPR_16QAM1(BAND_INDICATOR9),
                        LTE_DELTA_TC0(BAND_INDICATOR9), LTE_DELTA_TC1(BAND_INDICATOR9)  },
    { BAND_INDICATOR10, LTE_MPR_QPSK1(BAND_INDICATOR10),LTE_MPR_16QAM0(BAND_INDICATOR10),LTE_MPR_16QAM1(BAND_INDICATOR10),
                        LTE_DELTA_TC0(BAND_INDICATOR10),LTE_DELTA_TC1(BAND_INDICATOR10) },
    { BAND_INDICATOR11, LTE_MPR_QPSK1(BAND_INDICATOR11),LTE_MPR_16QAM0(BAND_INDICATOR11),LTE_MPR_16QAM1(BAND_INDICATOR11),
                        LTE_DELTA_TC0(BAND_INDICATOR11),LTE_DELTA_TC1(BAND_INDICATOR11) },
    { BAND_INDICATOR12, LTE_MPR_QPSK1(BAND_INDICATOR12),LTE_MPR_16QAM0(BAND_INDICATOR12),LTE_MPR_16QAM1(BAND_INDICATOR12),
                        LTE_DELTA_TC0(BAND_INDICATOR12),LTE_DELTA_TC1(BAND_INDICATOR12) },
    { BAND_INDICATOR13, LTE_MPR_QPSK1(BAND_INDICATOR13),LTE_MPR_16QAM0(BAND_INDICATOR13),LTE_MPR_16QAM1(BAND_INDICATOR13),
                        LTE_DELTA_TC0(BAND_INDICATOR13),LTE_DELTA_TC1(BAND_INDICATOR13) },
    { BAND_INDICATOR14, LTE_MPR_QPSK1(BAND_INDICATOR14),LTE_MPR_16QAM0(BAND_INDICATOR14),LTE_MPR_16QAM1(BAND_INDICATOR14),
                        LTE_DELTA_TC0(BAND_INDICATOR14),LTE_DELTA_TC1(BAND_INDICATOR14) },
};

#define LTE_AMPR_NS_DEFINE  (LTE_AMPR_NS_DEF(BAND_INDICATOR1) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR2) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR3) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR4) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR5) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR6) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR7) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR8) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR9) || \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR10)|| \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR11)|| \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR12)|| \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR13)|| \
                             LTE_AMPR_NS_DEF(BAND_INDICATOR14))

LTE_AMPRAdjust_T LTE_AMPRAdjustTbl[LTE_TARGET_MAX_SUPPORT_BAND_NUM] = 
{
#if LTE_AMPR_NS_DEFINE
    LTE_AMPR_NS(BAND_INDICATOR1)
    LTE_AMPR_NS(BAND_INDICATOR2)
    LTE_AMPR_NS(BAND_INDICATOR3)
    LTE_AMPR_NS(BAND_INDICATOR4)
    LTE_AMPR_NS(BAND_INDICATOR5)
    LTE_AMPR_NS(BAND_INDICATOR6)
    LTE_AMPR_NS(BAND_INDICATOR7)
    LTE_AMPR_NS(BAND_INDICATOR8)
    LTE_AMPR_NS(BAND_INDICATOR9)
    LTE_AMPR_NS(BAND_INDICATOR10)
    LTE_AMPR_NS(BAND_INDICATOR11)
    LTE_AMPR_NS(BAND_INDICATOR12)
    LTE_AMPR_NS(BAND_INDICATOR13)
    LTE_AMPR_NS(BAND_INDICATOR14)
#else
    0
#endif
};

/******************************************************************************
 * MPR_ALL   Table: Collect all Band MPR data
 * A-MPR_ALL Table: Collect all Band AMPR data
 * Description: record MPR and A-MPR value for DRDI handling
 ******************************************************************************/
 
const LTE_MPRAdjust_T LTE_MPRAdjustTbl_All[] = 
{	
    { LTE_Band1    , LTE_Band1_MPR_QPSK1 , LTE_Band1_MPR_16QAM0 , LTE_Band1_MPR_16QAM1 ,  LTE_Band1_DELTA_TC0 , LTE_Band1_DELTA_TC1  },
    { LTE_Band2    , LTE_Band2_MPR_QPSK1 , LTE_Band2_MPR_16QAM0 , LTE_Band2_MPR_16QAM1 ,  LTE_Band2_DELTA_TC0 , LTE_Band2_DELTA_TC1  },                    
    { LTE_Band3    , LTE_Band3_MPR_QPSK1 , LTE_Band3_MPR_16QAM0 , LTE_Band3_MPR_16QAM1 ,  LTE_Band3_DELTA_TC0 , LTE_Band3_DELTA_TC1  },
    { LTE_Band4    , LTE_Band4_MPR_QPSK1 , LTE_Band4_MPR_16QAM0 , LTE_Band4_MPR_16QAM1 ,  LTE_Band4_DELTA_TC0 , LTE_Band4_DELTA_TC1  },
    { LTE_Band5    , LTE_Band5_MPR_QPSK1 , LTE_Band5_MPR_16QAM0 , LTE_Band5_MPR_16QAM1 ,  LTE_Band5_DELTA_TC0 , LTE_Band5_DELTA_TC1  },
    { LTE_Band6    , LTE_Band6_MPR_QPSK1 , LTE_Band6_MPR_16QAM0 , LTE_Band6_MPR_16QAM1 ,  LTE_Band6_DELTA_TC0 , LTE_Band6_DELTA_TC1  },
    { LTE_Band7    , LTE_Band7_MPR_QPSK1 , LTE_Band7_MPR_16QAM0 , LTE_Band7_MPR_16QAM1 ,  LTE_Band7_DELTA_TC0 , LTE_Band7_DELTA_TC1  },
    { LTE_Band8    , LTE_Band8_MPR_QPSK1 , LTE_Band8_MPR_16QAM0 , LTE_Band8_MPR_16QAM1 ,  LTE_Band8_DELTA_TC0 , LTE_Band8_DELTA_TC1  },    
    { LTE_Band9    , LTE_Band9_MPR_QPSK1 , LTE_Band9_MPR_16QAM0 , LTE_Band9_MPR_16QAM1 ,  LTE_Band9_DELTA_TC0 , LTE_Band9_DELTA_TC1  },
    { LTE_Band11   , LTE_Band11_MPR_QPSK1, LTE_Band11_MPR_16QAM0, LTE_Band11_MPR_16QAM1,  LTE_Band11_DELTA_TC0, LTE_Band11_DELTA_TC1 },                    
    { LTE_Band12   , LTE_Band12_MPR_QPSK1, LTE_Band12_MPR_16QAM0, LTE_Band12_MPR_16QAM1,  LTE_Band12_DELTA_TC0, LTE_Band12_DELTA_TC1 },
    { LTE_Band13   , LTE_Band13_MPR_QPSK1, LTE_Band13_MPR_16QAM0, LTE_Band13_MPR_16QAM1,  LTE_Band13_DELTA_TC0, LTE_Band13_DELTA_TC1 },
    { LTE_Band14   , LTE_Band14_MPR_QPSK1, LTE_Band14_MPR_16QAM0, LTE_Band14_MPR_16QAM1,  LTE_Band14_DELTA_TC0, LTE_Band14_DELTA_TC1 },
    { LTE_Band17   , LTE_Band17_MPR_QPSK1, LTE_Band17_MPR_16QAM0, LTE_Band17_MPR_16QAM1,  LTE_Band17_DELTA_TC0, LTE_Band17_DELTA_TC1 },
    { LTE_Band18   , LTE_Band18_MPR_QPSK1, LTE_Band18_MPR_16QAM0, LTE_Band18_MPR_16QAM1,  LTE_Band18_DELTA_TC0, LTE_Band18_DELTA_TC1 },
    { LTE_Band19   , LTE_Band19_MPR_QPSK1, LTE_Band19_MPR_16QAM0, LTE_Band19_MPR_16QAM1,  LTE_Band19_DELTA_TC0, LTE_Band19_DELTA_TC1 },    
    { LTE_Band20   , LTE_Band20_MPR_QPSK1, LTE_Band20_MPR_16QAM0, LTE_Band20_MPR_16QAM1,  LTE_Band20_DELTA_TC0, LTE_Band20_DELTA_TC1 },
    { LTE_Band21   , LTE_Band21_MPR_QPSK1, LTE_Band21_MPR_16QAM0, LTE_Band21_MPR_16QAM1,  LTE_Band21_DELTA_TC0, LTE_Band21_DELTA_TC1 },                    
    { LTE_Band26   , LTE_Band26_MPR_QPSK1, LTE_Band26_MPR_16QAM0, LTE_Band26_MPR_16QAM1,  LTE_Band26_DELTA_TC0, LTE_Band26_DELTA_TC1 },
    { LTE_Band28   , LTE_Band28_MPR_QPSK1, LTE_Band28_MPR_16QAM0, LTE_Band28_MPR_16QAM1,  LTE_Band28_DELTA_TC0, LTE_Band28_DELTA_TC1 },
    { LTE_Band34   , LTE_Band34_MPR_QPSK1, LTE_Band34_MPR_16QAM0, LTE_Band34_MPR_16QAM1,  LTE_Band34_DELTA_TC0, LTE_Band34_DELTA_TC1 },
    { LTE_Band38   , LTE_Band38_MPR_QPSK1, LTE_Band38_MPR_16QAM0, LTE_Band38_MPR_16QAM1,  LTE_Band38_DELTA_TC0, LTE_Band38_DELTA_TC1 },
    { LTE_Band39   , LTE_Band39_MPR_QPSK1, LTE_Band39_MPR_16QAM0, LTE_Band39_MPR_16QAM1,  LTE_Band39_DELTA_TC0, LTE_Band39_DELTA_TC1 },
    { LTE_Band40   , LTE_Band40_MPR_QPSK1, LTE_Band40_MPR_16QAM0, LTE_Band40_MPR_16QAM1,  LTE_Band40_DELTA_TC0, LTE_Band40_DELTA_TC1 },
    { LTE_Band41   , LTE_Band41_MPR_QPSK1, LTE_Band41_MPR_16QAM0, LTE_Band41_MPR_16QAM1,  LTE_Band41_DELTA_TC0, LTE_Band41_DELTA_TC1 },    
    // LTE_BandMax setting must be in the end and can't be removed
    { LTE_BandMax  , LTE_BandNone_MPR_QPSK1, LTE_BandNone_MPR_16QAM0, LTE_BandNone_MPR_16QAM1, LTE_BandNone_DELTA_TC0, LTE_BandNone_DELTA_TC1 },
};

const LTE_AMPRAdjust_T LTE_AMPRAdjustTbl_All[] = 
{
    LTE_Band1_AMPR_NS
    LTE_Band2_AMPR_NS
    LTE_Band3_AMPR_NS
    LTE_Band4_AMPR_NS
    LTE_Band5_AMPR_NS
    LTE_Band6_AMPR_NS
    LTE_Band7_AMPR_NS
    LTE_Band8_AMPR_NS
    LTE_Band9_AMPR_NS
    LTE_Band10_AMPR_NS
    LTE_Band11_AMPR_NS
    LTE_Band12_AMPR_NS
    LTE_Band13_AMPR_NS
    LTE_Band14_AMPR_NS
    LTE_Band15_AMPR_NS
    LTE_Band16_AMPR_NS
    LTE_Band17_AMPR_NS
    LTE_Band18_AMPR_NS
    LTE_Band19_AMPR_NS
    LTE_Band20_AMPR_NS
    LTE_Band21_AMPR_NS
    LTE_Band22_AMPR_NS
    LTE_Band23_AMPR_NS
    LTE_Band24_AMPR_NS
    LTE_Band25_AMPR_NS
    LTE_Band26_AMPR_NS
    LTE_Band27_AMPR_NS
    LTE_Band28_AMPR_NS
    LTE_Band29_AMPR_NS
    LTE_Band30_AMPR_NS
    LTE_Band31_AMPR_NS
    LTE_Band33_AMPR_NS
    LTE_Band34_AMPR_NS
    LTE_Band35_AMPR_NS
    LTE_Band36_AMPR_NS
    LTE_Band37_AMPR_NS
    LTE_Band38_AMPR_NS
    LTE_Band39_AMPR_NS
    LTE_Band40_AMPR_NS
    LTE_Band41_AMPR_NS
    LTE_Band42_AMPR_NS
    LTE_Band43_AMPR_NS
    LTE_Band44_AMPR_NS
    // LTE_BandMax_AMPR_NS must be in the end and can't be removed
    LTE_BandMax_AMPR_NS
};  

