/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*  A. Patent Notice:
*  The software delivered hereunder, including any and all updates and upgrades,
*  might be subject to patent rights of standard-setting organizations, patent pools
*  or their respective patent owners, that will be necessarily infringed by the use
*  and distribution of the products incorporating all or part of this software.
*  According to the licensing terms of these patent holders, it is your sole
*  obligation to obtain the necessary patent licenses from these patent holders
*  before you can use or distribute the products incorporating all or part of this
*  software. MediaTek shall not be liable for your failure to obtain or maintain such
*  licenses.
*
*    As a courtesy to our customers, the following are some of the software that might
*    contain such patent licenses, but MediaTek does not warrant the accuracy or
*    completeness of the information below.
*    (1) MPEG4/AAC/AACPLUS/AACVPLUSV2: essential patents license must be obtained
*        from Via Licensing: <www.vialicensing.com>
*    (2) WAP/MMS security RC5 algorithm belongs to RSA Data Security:
*        <www.rsasecurity.com>
*    Notice: Please contact RSA to get this license before shipping the products to
*    USA which include RC5 security algorithm.
*
*  B. In addition, customers must contact the respective licensors to obtain
*  necessary software licenses before it can use or distribute the licensed
*  products.
*
*    As a courtesy to our customers, the following are some of the software licensers
*    and the notice or disclaimer required by their licenses, but MediaTek does not
*    warrant the accuracy or completeness of the information below.
*    (1) Microsoft Windows Media (WMA software):
*        Microsoft: <www.microsoft.com>
*        Approved OEM Manufacturers: <wmlicense.smdisp.net/oem_approved/>
*        Sample Windows Media Licensing Agreements:
*        <www.microsoft.com/windows/windowsmedia/licensing/agreements.aspx>
*    Notice in header or documentation: "This product is protected by certain
*    intellectual property rights of Microsoft and cannot be used or further
*    distributed without a license from Microsoft."
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   usb_debug_tool.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *  This file intends for usb common driver debug buffer definitions
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef USB_DEBUG_TOOL_H
#define USB_DEBUG_TOOL_H


#include "kal_general_types.h"



/***********************************************
	implement definition
************************************************/

#if defined(__LOW_COST_SUPPORT_ULC__)
#define USB_DBG_DATA_SIZE   64
#elif (__LOW_COST_SUPPORT_COMMON__)
#define USB_DBG_DATA_SIZE   256
#else
#define USB_DBG_DATA_SIZE   512
#endif


typedef enum
{
	USB_EP0_SET_CONFIGURATION = 1,
	USB_RESET,
	USB_SUSPEND,
	USB_RESUME,
	USB_DISCONN,
	USB_RELEASE_TYPE,
	USB_DBG_CABLE_PLUG_IN,
	USB_DBG_CABLE_PLUG_OUT,
	USB_DMA_LISR,
	USB_DBG_HISR,
	USB_DBG_HISR_ERROR_REASON,
	USB_DBG_IN_HOST_MODE,
	USB_DBG_DMA_CALLBACK,
	USB_HISR_ERROR,
	USB_HISR_SUSPEND_AND_CONN_ISR,
	USB_UNEXPECTED_RX_HISR,
	USB_DBG_HISR_STALL_INTR,
	USB_UPDATE_EP0_STATE_CLEAR_SENT_STALL,
	USB_UPDATE_EP0_STATE_SEND_STALL,
	USB_EPN_CLEAR_SENT_STALL_RX,
	USB_EPN_CLEAR_SENT_STALL_TX,
	USB_EPN_SEND_STALL_RX,
	USB_EPN_SEND_STALL_TX,
	USB_HISR_DMA_CALLBACK_1,
	USB_HISR_DMA_CALLBACK_2,
	USB_DBG_DMA_CALLBACK_2,
	USB_HISR_DMA_CALLBACK_FAST_1,
	USB_HISR_DMA_CALLBACK_FAST_2,
	USB_HISR_EP0_TX,
	USB_HISR_EP0_RX,
	USB_EPN_CTRL_STALL,
	USB_CLEAR_TX_EP_FIFO,
	USB_CLEAR_RX_EP_FIFO,
	USB_EPN_UNEXPECTED_TX_HISR,
	USB_EPN_UNEXPECTED_RX_HISR,
	USB_UPDATE_EP0_STATE_READ_END,
	USB_UPDATE_EP0_STATE_WRITE_RDY,
	USB_EP0_SET_ADDRESS,
	USB_EP0_GET_DESCRIPTOR,
	USB_EP0_SET_INTERFACE,
	USB_EP0_GET_CONFIGURATION,
	USB_EP0_GET_INTERFACE,
	USB_EP0_CLEAR_FEATURE,
	USB_EP0_SET_FEATURE,
	USB_EP0_GET_STATUS_TX,
	USB_EP0_GET_STATUS_RX,
	USB_MS_STOP_DMA_0,
	USB_MS_STOP_DMA_1,
	USB_MS_STOP_DMA_2,
	USB_MS_STOP_DMA_3,
	USB_SET_PDN_FLAG_TRUE,
	USB_SET_PDN_FLAG_FALSE,
	USB_TASK_UNMASK_EINT,
	USB_USBCFG_REQ,
	USB_DBG_SET_TXPKTREADY,
	USB_TXCSR_STAT,
	USB_RXCSR_STAT,
	USB_MASK_IRQ,
	USB_UNMASK_IRQ,
	USB_MEMORY_GET,	
	USB_MEMORY_FREE,	
#ifdef __USB_MASS_STORAGE_ENABLE__
	USB_MS_BUILD_DMA_TX,
	USB_MS_BUILD_DMA_TX_CALLBACK,
	USB_MS_BUILD_DMA_RX,
	USB_MS_BUILD_DMA_RX_CALLBACK,
	USB_MS_FIFO_RX_HDLR,
	USB_MS_FIFO_RX_WITH_WRONG_CBW_SIZE,
//	USB_MS_BUILD_DMA_RX_START_TIMER,
//	USB_MS_BUILD_DMA_RX_STOP_TIMER,
//	USB_MS_BUILD_DMA_RX_TIMEOUT,
	USB_MS_ERROR_CMD,
	USB_MS_EP0_RESET,
	USB_MS_RESET_MSG,
	USB_MS_RECEIVE_RESET_MSG,
	USB_MS_SWITCH_TO_FIFO_RX_BY_USB_CONFIG,
	USB_MS_GET_MAX_LUN,
	USB_MS_CMD_CBW_IS_NOT_VALID,
	USB_MS_CMD_TESTUNITREADY,
	USB_MS_CMD_INQUIRY,
	USB_MS_CMD_PREVALLOW_MEDIA_REMOVL,
	USB_MS_CMD_USBMS_WRITE10,
	USB_MS_CMD_USBMS_USB_END,
	USB_MS_CMD_USBMS_MSDC,
	USB_MS_CMD_USBMS_WRITE12,
	USB_MS_CMD_USBMS_READ10,
	USB_MS_CMD_USBMS_READ12,
	USB_MS_CMD_READ_CAPACITY,
	USB_MS_CMD_READ_FORMATCAPACITY,
	USB_MS_CMD_REQUESTSENSE,
	USB_MS_CMD_USBMS_VERIFY,
	USB_MS_CMD_MODE_SENSE,
	USB_MS_CMD_MODE_SENSE6,
	USB_MS_CMD_START_STOP_UNIT,
	USB_MS_CMD_SYNCHRONIZE_CACHE_10,
	USB_MS_CMD_READ_TOC,
	USB_MS_CMD_VENDOR,
	USB_MS_LOCKFAT,
	USB_MS_UNLOCKFAT,
	USB_MS_LOCKFAT_FAIL,
	USB_MS_READ_FAIL_HANDLER,
#endif
	USB_ACM_DMA_SETUP,
	USB_ACM_DMA_SETUP_1,
	USB_ACM_DMA_SETUP_2,
	USB_ACM_DMA_SETUP_3,
	USB_ACM_DMA_SETUP_4,
	USB_ACM_DMA_CALLBACK,
	USB_ACM_SEND_INTERRUPT,
	USB_ACM_SEND_INTERRUPT1,
	USB_ACM_SEND_INTERRUPT2,
	USB_ACM_INTERRUPT_HANDLER,
	USB_ACM_INTERRUPT_RESET,
	USB_ACM_TIMEOUT,
	USB_ACM_ESCAPE_CHAR,
	USB_ACM_USB2UART_RNDIS_Intr,
	USB_ACM_USB2UART_RNDIS_Error,	
	USB_ACM_USB2UART_RNDIS_Busy,	
	USB_ACM_USB2UART_PutUARTBytes,
	USB_ACM_USB2UART_PutUARTByte,
	USB_ACM_USB2UART_GetUARTByte,
	USB_ACM_USB2UART_CtrlDCD,
	USB_ACM_USB2UART_SendISRData,
	USB_ACM_USB2UART_PutISRBytes,
	USB_ACM_USB2UART_PutBytes,
	USB_ACM_USB2UART_ClrTxBuffer,
	USB_ACM_USB2UART_ClrRxBuffer,
	USB_ACM_USB2UART_EP_DISABLE,
	USB_ACM_USB2UART_EP_ENABLE,
	USB_ACM_USB2UART_Clear_Tx_ISR_Buffer,
	USB_ACM_USB2UART_Clear_Rx_ISR_Buffer,
	USB_ACM_USB2UART_Clear_Tx_Buffer,
	USB_ACM_USB2UART_Switch_port,
	USB_ACM_SEND_SHORT_PKT,
	USB_ACM_DMA_SEND_SHORT_PKT,
	USB_ACM_RX_PKT,
	USB_ACM_RX_PKT_LENGTH,
	USB_ACM_RX_FLC_PKT_LENGTH,	
	USB_ACM_RX_NEXT_PKT_LENGTH,
	USB_ACM_SEND_READY_TO_WRITE,
	USB_ACM_SEND_READY_TO_READ,
	USB_ACM_HIGH_SPEED_IF_ENABLE,
	USB_ACM_HIGH_SPEED_IF_DISABLE,
	USB_ACM_HIGHSPEED_PUTBYTES,
	USB_ACM_HIGHSPEED_GETBYTES,
	USB_ACM_HIGHSPEED_GET_FRAME,
	USB_ACM_HIGHSPEED_PUTBYTES_SETUP_DMA,
	USB_ACM_HIGHSPEED_MOVE_RC_INDEX,
	USB_ACM_HIGHSPEED_MOVE_R_INDEX,
	USB_ACM_HIGHSPEED_MOVE_W_INDEX,
	USB_ACM_HIGHSPEED_RX_IS_EMPTY,
	USB_ACM_HIGHSPEED_RX_BUF_COUNT,
	USB_ACM_EP0_PUTBYTES,
	USB_ACM_EP0_GETBYTES,
	USB_ACM_EP0_MOVE_RC_INDEX,
	USB_ACM_EP0_MOVE_R_INDEX,
	USB_ACM_EP0_MOVE_W_INDEX,
	USB_ACM_EP0_RX_IS_EMPTY,
	USB_ACM_EP0_RX_BUF_COUNT,	
#ifdef PICTBRIDGE_SUPPORT
	USB_DBG_PTP_GET_DEVICE_INFO,
	USB_DBG_PTP_OPEN_SESSION,
	USB_DBG_PTP_CLOSE_SESSION,
	USB_DBG_PTP_GET_STORAGE_IDS,
	USB_DBG_PTP_GET_STORAGE_INFO,
	USB_DBG_PTP_GET_NUM_OBJECTS,
	USB_DBG_PTP_GET_OBJECT_HANDLES,
	USB_DBG_PTP_GET_OBJECT_INFO,
	USB_DBG_PTP_GET_OBJECT,
	USB_DBG_PTP_GET_THUMB,
	USB_DBG_PTP_GET_PARTIAL_OBJECT,
	USB_DBG_PTP_SEND_OBJECT_INFO,
	USB_DBG_PTP_SEND_OBJECT,
	USB_DBG_DPS_HREQUEST_CONF,
	USB_DBG_DPS_HREQUEST_CONF_CANCEL,
	USB_DBG_DPS_HRESPONSE_CONF,
	USB_DBG_DPS_DREQUEST_REQ,
	USB_DBG_DPS_2_DREQUEST_REQ_WARNING,
	USB_DBG_DPS_DRESPONSE_REQ,
	USB_DBG_DPS_START_JOB_REQ,
	USB_DBG_DPS_CLOSE_JOB_REQ,
	USB_DBG_PTP_CLOSE_FS_ERROR,
#endif
#ifdef __USB_IMAGE_CLASS__
	USB_IMAGE_NULL_PKT_TIME_OUT,
	USB_IMAGE_SEND_RESET_MSG,
	USB_IMAGE_DEVICE_RESET,
	USB_IMAGE_CABLE_PLUG_OUT,
	USB_IMAGE_BUILD_DMA_TX,
	USB_IMAGE_BUILD_RETURN_DMA_TX,
	USB_IMAGE_BUILD_DMA_TX_CALLBACK,
	USB_IMAGE_BUILD_DMA_RX,
	USB_IMAGE_BUILD_DMA_RX_CALLBACK,
	USB_IMAGE_SEND_INTERRUPT,
	USB_IMAGE_SEND_INTERRUPT1,
	USB_IMAGE_SEND_INTERRUPT2,
	USB_IMAGE_SEND_INTERRUPT3,
	USB_IMAGE_INTERRUPT_PKT_FULL,
	USB_IMAGE_CANCEL_BY_DEVICE1,
	USB_IMAGE_CANCEL_BY_DEVICE2,
	USB_IMAGE_CANCEL_BY_DEVICE3,
	USB_IMAGE_EP0_RESET,
	USB_IMAGE_EP0_CANCEL,
	USB_IMAGE_EP0_GET_DEVICE_STATUS,
	USB_IMAGE_INTERRUPT_HANDLER,
	USB_IMAGE_SESSION_NOT_OPEN_ERROR,
	USB_IMAGE_EP0_CANCEL_WITH_WRONG_TRANSACTION_ID,
#endif
#ifdef __MTP_ENABLE__
	USB_MTP_GET_DEVICE_INFO,
	USB_MTP_OPEN_SESSION,
	USB_MTP_CLOSE_SESSION,
	USB_MTP_GET_STORAGE_IDS,
	USB_MTP_GET_STORAGE_INFO,
	USB_MTP_GET_NUM_OBJECTS,
	USB_MTP_GET_OBJECT_HANDLES,
	USB_MTP_GET_OBJECT_INFO,
	USB_MTP_GET_OBJECT,
	USB_MTP_DELETE_OBJECT,
	USB_MTP_SEND_OBJECT_INFO,
	USB_MTP_SEND_OBJECT,
	USB_MTP_GET_DEVICE_PROP_DESC,
	USB_MTP_GET_DEVICE_PROP_VALUE,
	USB_MTP_SET_DEVICE_PROP_VALUE,
	USB_MTP_GET_PARTIAL_OBJECT,
	USB_MTP_GET_OBJECT_PROPS_SUPPORTED,
	USB_MTP_GET_OBJECT_PROP_DESC,
	USB_MTP_GET_OBJECT_PROP_VALUE,
	USB_MTP_SET_OBJECT_PROP_VALUE,
	USB_MTP_GET_OBJECT_PROP_LIST,
	USB_MTP_GET_OBJECT_REFERENCES,
	USB_MTP_SET_OBJECT_REFERENCES,
	USB_MTP_SKIP,
	USB_MTP_OPEN_SESSION_RSP,
	USB_MTP_CLOSE_SESSION_RSP,
	USB_MTP_GET_STORAGE_IDS_RSP,
	USB_MTP_GET_STORAGE_INFO_RSP,
	USB_MTP_GET_NUM_OBJECTS_RSP,
	USB_MTP_GET_OBJECT_HANDLES_RSP,
	USB_MTP_GET_OBJECT_INFO_RSP,
	USB_MTP_GET_OBJECT_RSP,
	USB_MTP_DELETE_OBJECT_RSP,
	USB_MTP_SEND_OBJECT_INFO_RSP,
	USB_MTP_SEND_OBJECT_RSP,
	USB_MTP_GET_DEVICE_PROP_DESC_RSP,
	USB_MTP_GET_DEVICE_PROP_VALUE_RSP,
	USB_MTP_SET_DEVICE_PROP_VALUE_RSP,
	USB_MTP_GET_PARTIAL_OBJECT_RSP,
	USB_MTP_GET_OBJECT_PROPS_SUPPORTED_RSP,
	USB_MTP_GET_OBJECT_PROP_DESC_RSP,
	USB_MTP_GET_OBJECT_PROP_VALUE_RSP,
	USB_MTP_SET_OBJECT_PROP_VALUE_RSP,
	USB_MTP_GET_OBJECT_REFERENCES_RSP,
	USB_MTP_SET_OBJECT_REFERENCES_RSP,
	USB_MTP_SKIP_RSP,
	USB_MTP_RECEIVE_RSP_MSG,
	USB_MTP_NO_DATA_HDLR,
	USB_MTP_TX_DATA_HDLR,
	USB_MTP_TX_DATA_HDLR_1,
	USB_MTP_TX_DATA_HDLR_2,
	USB_MTP_TX_DATA_UNEXPECTED_ZERO_SIZE,
	USB_MTP_TX_DATA_UNVALID_MSG,
	USB_MTP_RX_DATA_UNVALID_MSG,
	USB_MTP_RX_DATA_HDLR_1,
	USB_MTP_TX_DMA_CALLBACK_HDLR,
	USB_MTP_RX_DATA_CALLBACK_HDLR,
	USB_MTP_RESPONSE_MSG_WITH_WRONG_STATE,
	USB_IMAGE_RELEASE_MTP,
	USB_IMAGE_PARSE_MTP_MSG,
	USB_IMAGE_PARSE_MTP_EVENT_MSG,
	USB_MTP_SEND_ENABLE_REQ_MSG,
	USB_MTP_SEND_DISABLE_REQ_MSG,
	USB_MTP_SEND_OP_REQ_MSG,
	USB_MTP_SEND_ABORT_EVENT_MSG,
	USB_MTP_IMAGE_OP_HDLR,
	USB_MTP_HOST_SEND_PACKET_IN_WRONG_STATE,
	USB_MTP_RECEIVE_ENABLE_RSP,
	USB_MTP_RECEIVE_DISABLE_RSP,
#endif
#ifdef WEBCAM_SUPPORT
	USB_VIDEO_PROBE_DONE,
	USB_VIDEO_PROBE_COMMIT_DONE,
	USB_VIDEO_PROBE_COMMIT_DONE_1,
	USB_VIDEO_PROBE_COMMIT_DONE_2,
	USB_VIDEO_PROBE_CONTROL_ERROR,
	USB_VIDEO_STILL_PROBE_NONE,
	USB_VIDEO_STILL_PROBE_DONE,
	USB_VIDEO_STILL_PROBE_COMMIT_DONE,
	USB_VIDEO_STILL_PROBE_CONTROL_ERROR,
	USB_VIDEO_GET_VIDEO_BUF_1,
	USB_VIDEO_GET_VIDEO_BUF_2,
	USB_VIDEO_COMPLETE_VIDEO_BUF_1,
	USB_VIDEO_COMPLETE_VIDEO_BUF_2,
	USB_VIDEO_COMPLETE_VIDEO_BUF_3,
	USB_VIDEO_COMPLETE_VIDEO_BUF_4,
	USB_VIDEO_GET_STILL_BUF,
	USB_VIDEO_COMPLETE_STILL_BUF,
	USB_VIDEO_DMA_DONE_HDLR_1,
	USB_VIDEO_DMA_DONE_HDLR_2,
	USB_VIDEO_DMA_DONE_HDLR_3,
	USB_VIDEO_STILL_DMA_DONE_HDLR,
	USB_VIDEO_SEND_VIDEO_1,
	USB_VIDEO_SEND_VIDEO_2,
	USB_VIDEO_SEND_INCALL_JPEG,
	USB_VIDEO_SEND_INCALL_JPEG_DMA_CALLBACK,
	USB_VIDEO_SEND_INCALL_JPEG_DMA_DONE,
	USB_VIDEO_SEND_INCALL_JPEG_DMA_DONE_HDLR_1,
	USB_VIDEO_SEND_INCALL_JPEG_DMA_DONE_HDLR_2,
	USB_VIDEO_INCALL_TIMEOUT_HDLR,
	USB_VIDEO_STOP_MSG,
#endif
#ifdef __USB_LOGGING__
	USBACM_LOGGING_INT,
	USBACM_LOGGING_START,
	USBACM_LOGGING_CONN,
	USBACM_LOGGING_DISCONN,
	USBACM_LOGGING_STOP,
	USBACM_LOGGING_DSP_HOST_HDLR,
	USBACM_LOGGING_DSP_SLAVE_HDLR,
	USBACM_LOGGING_DSP_HOST_BUF_INDEX,
	USBACM_LOGGING_DSP_SLAVE_BUF_INDEX,
	USBACM_LOGGING_CLEAR_BUF1,
	USBACM_LOGGING_CLEAR_BUF2,
	USBACM_LOGGING_DECIDE_BUF1,
	USBACM_LOGGING_DECIDE_BUF2,
	USBACM_LOGGING_DECIDE_BUF3,
	USBACM_LOGGING_DROP_PKT,
	USBACM_LOGGING_BUFF_EMPTY,
	USBACM_LOGGING_DSP_HOST_SET_DMA,
	USBACM_LOGGING_DSP_SLAVE_SET_DMA,
	USBACM_LOGGING_3G_HDLR,
	USBACM_LOGGING_3G_BUF_INDEX,
	USBACM_LOGGING_3G_SET_DMA,
	USBACM_LOGGING_DMA_SET_DMA,
	USBACM_LOGGING_BUFFERD,
#endif
#ifdef __OTG_ENABLE__
	USB_OTG_HISR,
	USB_OTG_SET_STATUS,
	USB_OTG_STATE_START,
	USB_OTG_STATE_A_IDLE,
	USB_OTG_STATE_A_WAIT_VRISE,
	USB_OTG_STATE_A_WAIT_BCON,
	USB_OTG_STATE_A_HOST,
	USB_OTG_STATE_A_SUSPEND,
	USB_OTG_STATE_A_PERIPHERALE,
	USB_OTG_STATE_A_WAIT_VFALL,
	USB_OTG_STATE_B_IDLE,
	USB_OTG_STATE_B_SRP_INIT,
	USB_OTG_STATE_B_PERIPHERAL,
	USB_OTG_STATE_B_WAIT_ACON,
	USB_OTG_STATE_B_HOST,
	USB_OTG_STATE_FROM_A_IDLE_TO_A_WAIT_BCON,
	USB_OTG_STATE_FROM_A_PERIPHERAL_TO_A_WAIT_BCON,
	USB_OTG_STATE_FROM_A_WAIT_BCON_TO_A_HOST,
	USB_OTG_STATE_FROM_A_HOST_TO_A_WAIT_BCON,
	USB_OTG_STATE_FROM_A_HOST_TO_A_SUSPEND,
	USB_OTG_STATE_FROM_A_SUSPEND_TO_A_WAIT_BCON,
	USB_OTG_STATE_FROM_A_SUSPEND_TO_A_PERIPHERAL,
	USB_OTG_STATE_FROM_A_SUSPEND_TO_A_HOST,
	USB_OTG_STATE_FROM_B_IDLE_TO_B_PERIPHERAL,
	USB_OTG_STATE_FROM_B_PERIPHERAL_TO_B_WAIT_ACON,
	USB_OTG_STATE_FROM_B_WAIT_ACON_TO_B_HOST,
	USB_OTG_STATE_FROM_B_WAIT_ACON_TO_B_PERIPHERAL,
	USB_OTG_STATE_FROM_B_HOST_TO_B_PERIPHERAL,
	USB_OTG_STATE_FROM_A_WAIT_VFAIL_TO_A_IDLE,
	USB_OTG_B_DEVICE_PENDING_DOWN_HDLR,
	USB_OTG_RESET,
	USB_OTG_SESSREQ,
	USB_OTG_RESUME,
	USB_OTG_SOF,
	USB_OTG_TIMEOUT_HDLR,
#endif	
#if defined(__OTG_ENABLE__)||defined(__IC_USB_ENABLE__)
	USB_HCD_UNMASK_HISR,
	USB_HCD_RESUME,
	USB_HCD_CONN,
	USB_HCD_DISCONN,
	USB_HCD_BABBLE,
	USB_HCD_DMA_CALLBACK,
	USB_HCD_DMA_TIMEOUT_ERROR,
	USB_HCD_EP0_INTR,
	USB_HCD_EPN_TX_INTR,
	USB_HCD_EPN_RX_INTR,
	USB_HCD_SEND_DATA_DONE,
	USB_HCD_EP0_Setup,
	USB_HCD_EP0_Data,
	USB_HCD_EP0_Status,
	USB_HCD_EP0_CSR0,
	USBD_EP0_CMD_TAKE_MUTEX,
	USBD_EP0_CMD_GIVE_MUTEX,
	USBD_EP0_CMD_SET_EVENT,
	USBD_EP0_CMD_REC_EVENT,
	USBD_CH9_CALLBACK_ERROR,
	USBD_CH9_CALLBACK_START,
	USBD_CH9_CALLBACK_DELAY_SET_ADDR,
	USBD_CH9_CALLBACK_TIME_OUT,
	USBD_CH9_CALLBACK_SET_ADDR,
	USBD_CH9_CALLBACK_GET_DEV_DESC_8,
	USBD_CH9_CALLBACK_GET_DEV_DESC,
	USBD_CH9_CALLBACK_GET_CONF_DESC_9,
	USBD_CH9_CALLBACK_GET_CONF_DESC,
	USBD_CH9_CALLBACK_SET_HNP_ENABLE,
	USBD_CH9_CALLBACK_SET_CONF,
	USBD_CH9_CALLBACK_SET_CONF_DONE,
	USBD_HOST_STOP_VBUS,
	USBD_RESUME,
	USBD_SUSPEND,
	USB_HOST_DEFAULT_STARTUP,
	USB_HOST_MS_ERROR_HLDR,
	USB_HOST_MS_CHECK_MEDIA,
	USB_HOST_MS_QUERY_MEDIA,
	USB_HOST_MS_RESET,
	USB_HOST_MS_EP0_GET_LUN,	
	USB_HOST_MS_EP0_RESET,	
	USB_HOST_SET_EVENT,
	USB_HOST_RETRIEVE_EVENT,
	USB_HOST_MS_REQUEST_SENSE_1,
	USB_HOST_MS_REQUEST_SENSE_2,
	USB_HOST_MS_REQUEST_SENSE_3,
	USB_HOST_MS_INQUIRY_1,
	USB_HOST_MS_INQUIRY_2,
	USB_HOST_MS_INQUIRY_3,
	USB_HOST_MS_READ_FORMAT_CAPACITY_1,
	USB_HOST_MS_READ_FORMAT_CAPACITY_2,
	USB_HOST_MS_READ_FORMAT_CAPACITY_3,
	USB_HOST_MS_READ_CAPACITY_1,
	USB_HOST_MS_READ_CAPACITY_2,
	USB_HOST_MS_READ_CAPACITY_3,
	USB_HOST_MS_READ_CAPACITY_ERROR,
	USB_HOST_MS_TEST_UNIT_READY_1,
	USB_HOST_MS_TEST_UNIT_READY_2,
	USB_HOST_MS_TEST_UNIT_READY_3,
	USB_HOST_MS_MODE_SENSE6_1,
	USB_HOST_MS_MODE_SENSE6_2,
	USB_HOST_MS_MODE_SENSE6_3,
	USB_HOST_MS_MODE_SENSE6_ALL_1,
	USB_HOST_MS_MODE_SENSE6_ALL_2,
	USB_HOST_MS_MODE_SENSE6_ALL_3,
	USB_HOST_MS_MODE_SENSE10_ALL_1,
	USB_HOST_MS_MODE_SENSE10_ALL_2,
	USB_HOST_MS_MODE_SENSE10_ALL_3,
	USB_HOST_MS_READ_1,
	USB_HOST_MS_READ_2,
	USB_HOST_MS_READ_3,
	USB_HOST_MS_WRITE_1,
	USB_HOST_MS_WRITE_2,
	USB_HOST_MS_WRITE_3,
	USB_HOST_MS_CTRL_EP_HDLR,
	USB_HOST_MS_BULK_EP_HDLR,
	USB_HOST_MS_HDLR,
	USB_HOST_MS_STATE_HDLR,
	USB_HOST_MS_STATE_HDLR_ERROR1,
	USB_HOST_MS_STATE_HDLR_ERROR2,
	USB_HOST_MS_BULK_EP_HDLR_ERROR1,
	USB_HOST_MS_BULK_EP_HDLR_ERROR2,
	USB_HOST_MS_CBW_HDLR,
	USB_HOST_MS_DATA_HDLR,
	USB_HOST_MS_CSW_HDLR,
	USB_HOST_MS_START_TIMER,
	USB_HOST_MS_STATE_MAIN_FALSE,
	USB_HOST_MS_TIME_OUT,
	USB_HOST_A_CABLE_PLUG_IN,
	USB_HOST_A_CABLE_PLUG_OUT,
	USB_HOST_EXCEPTIONS,
	USB_HOST_MS_READSECTORS_1,
	USB_HOST_MS_READSECTORS_2,
	USB_HOST_MS_READSECTORS_3,
	USB_HOST_MS_READSECTORS_4,
	USB_HOST_MS_READSECTORS_5,
	USB_HOST_MS_READSECTORS_6,
	USB_HOST_MS_WRITESECTORS_1,
	USB_HOST_MS_WRITESECTORS_2,
	USB_HOST_MS_WRITESECTORS_3,
	USB_HOST_MS_WRITESECTORS_4,
	USB_HOST_MS_WRITESECTORS_5,
	USB_HOST_MS_WRITESECTORS_6,
	USB_HOST_MS_MOUNTDEVICE_1,
	USB_HOST_MS_MOUNTDEVICE_2,
	USB_HOST_MS_MOUNTDEVICE_3,
	USB_HOST_MS_MOUNTDEVICE_4,
	USB_HOST_MS_MEDIACHANGE_1,
	USB_HOST_MS_MEDIACHANGE_2,
	USB_HOST_MS_MEDIACHANGE_3,
	USB_HOST_MS_MEDIACHANGE_4,
	USB_HOST_MS_MEDIACHANGE_5,
	USB_HOST_MS_GETDISKGEOMETRY_1,
	USB_HOST_MS_GETDISKGEOMETRY_2,
	USB_HOST_MS_GETDISKGEOMETRY_3,
	USB_HOST_MS_GETDISKGEOMETRY_4,
	USB_HOST_MS_GETDISKGEOMETRY_5,
	USB_HOST_MS_MESSAGEACK_1,
	USB_HOST_MS_MESSAGEACK_2,
	USB_HOST_MS_MESSAGEACK_3,
	USB_HOST_MS_MESSAGEACK_4,
	USB_HOST_MS_MESSAGEACK_5,
	USB_HOST_MS_REPORT_MEDIA_STATE,
	USB_HOST_MS_WRONG_EP_MAXPKT_SIZE,
	USB_OTG_MASK_HISR,
	USB_OTG_UNMASK_HISR,
	USB_OTG_STATE_A_WAIT_BCON_TURN_OFF_VBUS,
	USB_HCD_CONN_AND_DISCONN,
	USB_A_CABLE_OUT_BUT_NO_DISCONN,
	USB_HCD_UNEXPECTED_TX_INTR,
	USB_HCD_UNEXPECTED_RX_INTR,
	USB_HCD_UNEXPECTED_EP0_INTR,
	USB_OTG_MODE_SELECTION,
#endif

#ifdef __USB_STRESS_TEST__
	DBG_USB_ECHO_Build_TX,
	DBG_USB_ECHO_Build_RX,
	DBG_USB_ECHO_TX_DMA_Callback,
	DBG_USB_ECHO_RX_DMA_Callback,
#endif
	USB_EP_META_INIT,
	USB_CMD_SetFeature,
	USB_HCD_NAKTIMEOUT,
	USB_DBG_MAX
}USB_DBG_INFO;


/***********************************************
	Implement enum and structure
************************************************/

typedef struct
{
	USB_DBG_INFO	tag;
	kal_uint32      time;
	kal_uint32      data1;
	kal_uint32      data2;
}Usb_Dbg_Data;


typedef struct
{
	Usb_Dbg_Data	dbg_data[USB_DBG_DATA_SIZE];
	kal_uint16 	dbg_data_idx;
}Usb_Dbg_Struct;


/***********************************************
	function and global variable
************************************************/
extern void USB_Dbg_Trace(USB_DBG_INFO tag, kal_uint32 data1, kal_uint32 data2);


#endif /* USB_DEBUG_TOOL_H */

