copy /y .\interface\service\kal\kal_general_types.h %1
copy /y .\interface\service\config\middleWare_task_config.h %1
copy /y .\interface\service\config\modem_2g3g_task_config.h %1
copy /y .\interface\service\config\drv_task_config.h %1
copy /y .\interface\service\config\modem_4g_task_config.h %1
copy /y .\interface\sap\module_hisrid_range.h %1
copy /y .\interface\service\config\srv_task_config.h %1
copy /y .\interface\service\kal\kal_public_defs.h %1
copy /y .\interface\service\config\stack_config.h %1
copy /y .\interface\service\config\hisr_config_internal.h %1
copy /y .\interface\service\kal\clib.h %1
copy /y .\interface\service\kal\clib_list.h %1
copy /y .\interface\sap\module_id_range.h %1
copy /y .\interface\sap\hisr_modid.h %1
copy /y .\interface\sap\middleware_modid.h %1
copy /y .\interface\sap\modem_2g3g_modid.h %1
copy /y .\interface\sap\srv_modid.h %1
copy /y .\interface\sap\modem_4g_modid.h %1
copy /y .\interface\service\config\stack_msgs.h %1
copy /y .\interface\sap\drv_modid.h %1
copy /y .\interface\service\kal\kal_public_api.h %1
copy /y .\interface\service\dhl\dhl_trace.h %1
copy /y .\interface\driver\peripheral\dcl.h %1
copy /y .\interface\modem\general\ps_public_enum.h %1
copy /y .\interface\service\nvram\nvram_defs.h %1
copy /y .\interface\modem\general\ps_public_struct.h %1
copy /y .\interface\service\dhl\kal_trace.h %1
copy /y .\interface\service\nvram\nvram_enums.h %1
copy /y .\interface\common\global_def.h %1
copy /y .\modem\interface\l4misc\l3_inc_enums.h %1
copy /y .\driver\drv_def\drv_features_chip_select.h %1
copy /y .\driver\drv_def\drv_features_gpio.h %1
copy /y .\driver\devdrv\drv_def\drv_features_6290.h %1
copy /y .\interface\service\config\stack_buff_pool.h %1
copy /y .\modem\interface\general\irat_common_enums.h %1
copy /y .\interface\service\config\ctrl_buff_pool.h %1
copy /y .\interface\modem\general\sim_public_enum.h %1
copy /y .\custom\service\nvram\custom_nvram_sec.h %1
copy /y .\interface\modem\general\sim_ps_enum.h %1
copy /y .\interface\modem\lte\el1_rf_public.h %1
copy /y .\interface\service\config\hisr_config.h %1
copy /y .\interface\service\config\stack_types.h %1
copy /y .\interface\sap\module_msg_range.h %1
copy /y .\interface\sap\sap_range.h %1
copy /y .\interface\driver\peripheral\dcl_uart.h %1
copy /y .\interface\driver\peripheral\dcl_msdc.h %1
copy /y .\interface\driver\peripheral\dcl_gpt.h %1
copy /y .\interface\driver\peripheral\dcl_gpio.h %1
copy /y .\interface\driver\peripheral\dcl_wdt.h %1
copy /y .\interface\driver\peripheral\dcl_idc.h %1
copy /y .\interface\driver\peripheral\dcl_f32k_clk.h %1
copy /y .\interface\driver\peripheral\dcl_adc.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_usb_drv.h %1
copy /y .\interface\driver\peripheral\dcl_sts.h %1
copy /y .\interface\driver\peripheral\dcl_sim.h %1
copy /y .\interface\driver\peripheral\dcl_rtc.h %1
copy /y .\interface\driver\peripheral\DclS_kbd.h %1
copy /y .\interface\driver\peripheral\dcl_pw.h %1
copy /y .\interface\driver\peripheral\dcl_pfc.h %1
copy /y .\interface\driver\peripheral\DclH_kbd.h %1
copy /y .\interface\driver\peripheral\dcl_chr_det.h %1
copy /y .\interface\driver\peripheral\dcl_bmt.h %1
copy /y .\interface\driver\peripheral\dcl_sim_gpio.h %1
copy /y .\interface\driver\peripheral\dcl_pmu.h %1
copy /y .\interface\modem\general\cmux_vp_num.h %1
copy /y .\interface\modem\general\em_public_struct.h %1
copy /y .\driver\drv_def\drv_features_adc.h %1
copy /y .\driver\regbase\inc\reg_base_mt6290.h %1
copy /y .\driver\regbase\inc\reg_base.h %1
copy /y .\driver\drv_def\drv_features_sim.h %1
copy /y .\driver\drv_def\drv_features_rtc.h %1
copy /y .\interface\modem\general\ps_em_enum.h %1
copy /y .\interface\modem\l1\fdd\external\ul1d_rf_cid.h %1
copy /y .\interface\service\nvram\nvram_data_items.h %1
copy /y .\interface\service\stacklib\lcd_ip_cqueue.h %1
copy /y .\modem\interface\l4misc\l3_inc_local.h %1
copy /y .\driver\drv_def\drv_features_gpt.h %1
copy /y .\interface\modem\l1\gsm\external\mph_types.h %1
copy /y .\modem\interface\general\as_common.h %1
copy /y .\interface\service\config\kal_user_mem.h %1
copy /y .\interface\service\dhl\tst.h %1
copy /y .\interface\service\event_info\event_info_utility.h %1
copy /y .\interface\service\config\sysconf_statistics.h %1
copy /y .\modem\gl1\l1_dm\common\l1_const.h %1
copy /y .\modem\interface\general\irat_common_struct.h %1
copy /y .\interface\modem\mml1\mml1_rf_global.h %1
copy /y .\interface\sap\svc\sysservice_msgid.h %1
copy /y .\interface\service\config\task_config.h %1
copy /y .\interface\service\config\syscomp_config.h %1
copy /y .\interface\middleware\meta\ft_msg_common.h %1
copy /y .\interface\modem\lte\el1_meta_if.h %1
copy /y .\interface\modem\lte\el1_rf_cid.h %1
copy /y .\interface\service\hif\hmu_conf_data.h %1
copy /y .\interface\modem\general\mmi_l3_enums.h %1
copy /y .\interface\middleware\hif\nmu.h %1
copy /y .\interface\modem\lte\el1_rf_public_mt6169.h %1
copy /y .\interface\service\asn1_common\mtkasn_global.h %1
copy /y .\interface\modem\lte\el1_drdi.h %1
copy /y .\interface\sap\md_sap.h %1
copy /y .\interface\driver\sys_drv\cache_sw.h %1
copy /y .\interface\modem\general\em_struct.h %1
copy /y .\driver\devdrv\cirq_v2\inc\irqid.h %1
copy /y .\interface\modem\l1\fdd\external\ul1d_rf_public.h %1
copy /y .\interface\modem\l1\fdd\internal\ul1_cnst.h %1
copy /y .\modem\interface\general\uas_common_enums.h %1
copy /y .\interface\modem\general\sim_common_enums.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_usb_hcd.h %1
copy /y .\interface\driver\peripheral\dcl_i2c.h %1
copy /y .\interface\driver\peripheral\dcl_pxs.h %1
copy /y .\interface\driver\peripheral\dcl_aux.h %1
copy /y .\interface\driver\peripheral\dcl_irda.h %1
copy /y .\interface\driver\peripheral\dcl_pwm.h %1
copy /y .\interface\driver\connectivity\usb_driver\dcl_otg_drv.h %1
copy /y .\interface\driver\peripheral\dcl_i2c_owner.h %1
copy /y .\interface\service\dhl\L1Trc.h %1
copy /y .\interface\service\flc2\flc2_config.h %1
copy /y .\interface\sap\svc_sap.h %1
copy /y .\driver\devdrv\cirq_v2\inc\irqid_MT6290.h %1
copy /y .\interface\driver\peripheral\drv_comm.h %1
copy /y .\interface\driver\sys_drv\intrCtrl.h %1
copy /y .\interface\modem\l1\fdd\internal\ul1_def.h %1
copy /y .\modem\gl1\l1_dm\l1d_ext\l1d_cid.h %1
copy /y .\driver\devdrv\cirq_v2\inc\drv_mdcirq.h %1
copy /y .\driver\devdrv\cirq_v2\inc\drv_mdcirq_reg.h %1
copy /y .\interface\modem\general\sim_public_api.h %1
copy /y .\driver\devdrv\cirq_v2\inc\intrCtrl_MT6290.h %1
copy /y .\interface\driver\sys_drv\isrentry.h %1
copy /y .\driver\devdrv\cirq_v1\inc\intrCtrl_SW_Handle.h %1
copy /y .\driver\devdrv\cirq_v2\inc\intrCtrl_MT6290_SW_Handle.h %1
copy /y .\interface\modem\l1\fdd\external\ul1cal.h %1
copy /y .\interface\modem\general\sim_ps_api.h %1
copy /y .\interface\service\stacklib\lcd.h %1
copy /y .\interface\sap\md_drv_sap.h %1
copy /y .\modem\interface\l1\inner\l1_types.h %1
copy /y .\modem\interface\l1\inner\l1_core_private.h %1
copy /y .\interface\modem\l1\gsm\external\l1_option.h %1
copy /y .\modem\interface\general\uas_gas_enums.h %1
copy /y .\interface\service\qmu_bm\qmu_bm.h %1
copy /y .\interface\service\asn1_common\asn_memory.h %1
copy /y .\interface\service\fsm\sm_type.h %1
copy /y .\interface\service\asn1_common\asn_common.h %1
copy /y .\modem\interface\general\l3llc_enums.h %1
copy /y .\service\nucleus_v2\inc\nucleus.h %1
copy /y .\modem\interface\general\mrs_as_enums.h %1
copy /y .\modem\md_sm\common\l1sm\l1sm_internal_public.h %1
copy /y .\modem\gl1\l1_dm\common\tool.h %1
copy /y .\interface\modem\general\tcm_api.h %1
copy /y .\modem\interface\l1\inner\l1_tool.h %1
copy /y .\modem\interface\l1\inner\l1_public.h %1
copy /y .\interface\modem\l1\gsm\external\l1_types_public.h %1
copy /y .\modem\interface\l1\inner\l1_core.h %1
copy /y .\interface\sap\md\l4_msgid.h %1
copy /y .\interface\modem\general\l4c_msg_hdlr_defs.h %1
copy /y .\modem\interface\general\protocol_section.h %1
copy /y .\interface\modem\general\device.h %1
copy /y .\modem\interface\l1\gsm\mph_cnst.h %1
copy /y .\modem\interface\general\tftlib_common_enum.h %1
copy /y .\driver\drv_def\drv_features_wdt.h %1
copy /y .\modem\interface\l4\l4c_ratdm_struct.h %1
copy /y .\driver\drv_def\drv_features_pwm.h %1
copy /y .\driver\drv_def\drv_features_gcu.h %1
copy /y .\interface\service\fs\fs_gprot.h %1
copy /y .\modem\interface\asn\rr\include\csn_common.h %1
copy /y .\driver\drv_def\drv_features_misc.h %1
copy /y .\driver\drv_def\drv_features_hif.h %1
copy /y .\driver\drv_def\drv_features_accdet.h %1
copy /y .\driver\drv_def\drv_features_msdc.h %1
copy /y .\driver\drv_def\drv_features_f32k.h %1
copy /y .\driver\drv_def\drv_features_uart.h %1
copy /y .\driver\drv_def\drv_features_pfc.h %1
copy /y .\driver\drv_def\drv_features_bmt.h %1
copy /y .\driver\drv_def\drv_features_i2c.h %1
copy /y .\driver\drv_def\drv_features.h %1
copy /y .\driver\drv_def\drv_features_spi.h %1
copy /y .\driver\drv_def\drv_features_usb.h %1
copy /y .\interface\driver\peripheral\adc_cali.h %1
copy /y .\interface\service\stacklib\lcd_cqueue.h %1
copy /y .\interface\service\qmu_bm\qmu_bm_size.h %1
copy /y .\modem\interface\general\divider_public.h %1
copy /y .\modem\interface\l1\inner\l1_private.h %1
copy /y .\modem\interface\general\gas_eas_enums.h %1
copy /y .\modem\interface\l4misc\l4c_common_enum.h %1
copy /y .\driver\sleep_drv\internal\inc\dcxo_div.h %1
copy /y .\custom\modem\common\ps\ul1_nvram_def.h %1
copy /y .\modem\interface\l1\inner\l1_timertype.h %1
copy /y .\modem\interface\general\rlc_mac_enums.h %1
copy /y .\interface\service\nvram\nvram_editor_data_item.h %1
copy /y .\modem\l4\include\rmmi_common_enum.h %1
copy /y .\modem\interface\lte\tcm_eval_enums.h %1
copy /y .\interface\service\qmu_bm\qbm_features.h %1
copy /y .\modem\interface\asn\rr\include\gprs_rlcmac_common_struct.h %1
copy /y .\modem\ul1\ul1_hs_plus\common\ul1_types.h %1
copy /y .\interface\service\qmu_bm\qmu_bm_in.h %1
copy /y .\interface\service\qmu_bm\qmu_bm_enum.h %1
copy /y .\interface\modem\l1\fdd\external\ul1d_rf_common.h %1
copy /y .\modem\interface\general\rr2mpal_struct.h %1
copy /y .\interface\service\nvram\nvram_struct.h %1
copy /y .\modem\interface\asn\rr\include\gprs_rlcmac_dl_struct.h %1
copy /y .\modem\common\mcd\include\mcd_struct.h %1
copy /y .\interface\service\flc2\flc2_ent_functions.h %1
copy /y .\service\nucleus_v2\inc\tc_defs.h %1
copy /y .\interface\service\stacklib\lcd_lqueue.h %1
copy /y .\interface\service\fs\fs_type.h %1
copy /y .\interface\service\stacklib\dlist.h %1
copy /y .\modem\interface\general\rsvas_enum.h %1
copy /y .\service\nucleus_v2\inc\esal_ts_rte_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_int_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_int_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_mem_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_pr_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_dbg_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_com_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_stk_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_rte_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_stk_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_ts_stk_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_co_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_pr_tmr_defs.h %1
copy /y .\service\nucleus_v2\inc\esal_dp_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_extern.h %1
copy /y .\service\nucleus_v2\inc\esal_ar_cfg.h %1
copy /y .\service\nucleus_v2\inc\esal_ge_isr_defs.h %1
