/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/******************************************************************************
 * Filename:
 * ---------
 *	nstd_struct_enum.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *
 * Author:
 * -------
 * -------
 *
 *=============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *=============================================================================
 ******************************************************************************/

/********************************************************************************
*  Copyright Statement:
*  --------------------
*
*  This product has been developed using a protocol stack
*  developed by Sasken Communication Technologies Limited.
*
********************************************************************************/

#ifndef _ERROR_STRUCT_ENUM_H_
#define _ERROR_STRUCT_ENUM_H_

typedef enum {
RR_NO_ERROR_STRUCT = 0,
RR_PACKET_DOWNLINK_STRUCT_ERROR ,
PDCH_DYNAMIC_ALLOC_STRUCT_ERROR,
PDCH_SINGLE_BLK_ALLOC_STRUCT_ERROR,
PDCH_FIXED_ALLOC_STRUCT_ERROR,
RR_PACKET_UPLINK_STRUCT_ERROR,
RMC_START_TIME_STRUCT_ERROR,
STARTING_TIME_ERROR,
RMC_P0_PWR_CNTRL_MODE_STRUCT_ERROR,
RMC_SINGLE_BLOCK_ALLOC_STRUCT_ERROR,
RMC_P0_PR_MODE_STRUCT_ERROR,
RMC_DYN_ALLOC_STRUCT_ERROR,
RMC_FIXED_ALLOC_STRUCT_ERROR,
RMC_DYN_OR_FIXED_ALLOC_STRUCT_ERROR,
RMC_PKT_UL_ASGN_STRUCT_ERROR,
RMC_ACCESS_TECH_REQ_ELEM_STRUCT_ERROR,
RMC_ACCESS_TECH_REQ_STRUCT_ERROR,
RMC_MULTI_BLK_ALLOC_STRUCT_ERROR,
RMC_EGPRS_MOD_AND_CODING_STRUCT_ERROR,
RMC_EGPRS_WINDOW_SIZE_STRUCT_ERROR,
RMC_EGPRS_DYN_OR_FIXED_ALLOC_STRUCT_ERROR,
RMC_EGPRS_PKT_UL_ASGN_STRUCT_ERROR,
RMC_FREQ_PARAMS_WITH_LENGTH_STRUCT_ERROR,
RMC_RLC_MODE_ALPHA_GAMMA_STRUCT_ERROR,
RMC_EGPRS_TBF_MODE_STRUCT_ERROR,
RMC_PKT_DL_ASGN_STRUCT_ERROR,
IAREST_OCTETS_ERROR,

PERSIST_LEVEL_STRUCT_ERROR,
GLOBAL_TFISTRUCT_ERROR,
TIMING_ADV_IDX_TSLOT_STRUCT_ERROR,
PKT_TIMING_ADVANCE_STRUCT_ERROR,
CHNG_MARK1STRUCT_ERROR,
INDIRECT_ENCODE_STRUCT_ERROR,
DIRECT_ENCODE1STRUCT_ERROR,
FREQ_PARAMS_PEER_STRUCT_ERROR,
STARTING_FRAME_NUM_STRUCT_ERROR,
PKT_REQ_REF_STRUCT_ERROR,
USF_STRUCT_ERROR,
TIME_SLOT_ALLOC_STRUCT_ERROR,
USF_GAMMA_STRUCT_ERROR,
RR_USF_PWR_CTRL_STRUCT_ERROR,
TIME_SLOT_PWR_CTRL_ALLOC_STRUCT_ERROR,
P0PR_MODE_STRUCT_ERROR,
DYNAMIC_ALLOC_STRUCT_ERROR,
ALPHA_GAMMA_STRUCT_ERROR,
BTS_MODE_STRUCT_ERROR,
SINGLE_BLK_ALLOC_STRUCT_ERROR,
GAMMA_TN_VALUE_STRUCT_ERROR,
PWR_CTRL_PARAMS_PEER_STRUCT_ERROR,
FIXED_ALLOC_STRUCT_ERROR,
EXTEND_TIMING_ADV_STRUCT_ERROR,
GPRSUPLNK_ASSIGN_STRUCT_ERROR,
PKT_UPLINK_ASSIGNMENT_MSG_ERROR,
MEAS_MAP_PEER_STRUCT_ERROR,
PKT_DOWNLINK_ASSIGN_ERROR,
WAIT_STRUCT_ERROR,
REJECT_STRUCT_ERROR,
PACKET_ACCESS_REJECT_ERROR,
PACKET_QUEING_NOTIFICATION_ERROR,
ALLOC_BITMAP_STRUCT_ERROR,
ALLOC_STRUCT_ERROR, 
ACK_NACK_FIXED_ALLOC_STRUCT_ERROR,
GPRSUPLNK_ACK_NACK_STRUCT_ERROR,
PKT_UPLINK_ACK_NACK_ERROR,
TIMING_ADV_INDEX_TN_STRUCT_ERROR,
GLOBAL_PKT_TIM_ADV_STRUCT_ERROR,
GLOBAL_PWR_CTRL_PARAMS_STRUCT_ERROR,
GLOBAL_PWR_CTRL_PKT_TIM_STRUCT_ERROR,
PKT_PWR_CTRL_TIM_ADV_STRUCT_ERROR,
TS_RECONFIG_DYNAMIC_ALLOC_STRUCT_ERROR,
TS_RECONFIG_FIXED_ALLOC_STRUCT_ERROR,
GPRS_TIMESLOT_RECONFIG_ERROR,
PKT_TIMESLOT_RECONFIGURE_ERROR,
PACKET_POLLING_REQUEST_ERROR,
HEADER_STRUCT_ERROR,
EXTENSION_BIT_STRUCT_ERROR,
/* Evelyn 20090415: Merge R6 */
//#ifdef __MTBF__
/*TLLI_G_RNTI_STRUCT_ERROR,
BTS_MODE_MODIFY_STRUCT_ERROR,
EGPRS_WINDOW_SIZE_STRUCT_ERROR,
HFN_LSB_STRUCT_ERROR,
MTBF_DOWNLINK_TBF_ASSIGN_STRUCT_ERROR,
PFI_RLCMODE_STRUCT_ERROR,
TBF_ADDRESS_REL6_STRUCT_ERROR,
DOWNLINK_TBF_ASSIGN_STRUCT_ERROR,
UPLINK_TBF_ASSIGN_STRUCT_ERROR,
UPLINK_ASSIGN_STRUCT_ERROR,
GPRS_UPLINK_ASSIGN_MTBF_STRUCT_ERROR,
EGPRS_UPLINK_ASSIGN_MTBF_STRUCT_ERROR,
MTBF_UPLINK_ASSIGN_ERROR,
TS_RECONFIG_DL_TBF_ASSIGN_STRUCT_ERROR,
TS_RECONFIG_DL_TBF_ASSIGN_MTBF_STRUCT_ERROR,
TS_RECONFIG_UL_ASSIGN_STRUCT_ERROR,
MTBF_DOWNLINK_ASSIGN_ERROR,
GPRS_TS_RECONFIG_MTBF_STRUCT_ERROR,
EGPRS_TS_RECONFIG_MTBF_STRUCT_ERROR,
MTBF_TIMESLOT_RECONFIGURE_ASSIGN_ERROR,*/
REL_5_LATER_PDAS_STRUCT_ERROR,
REL_5_LATER_PUAS_STRUCT_ERROR,
REL_5_LATER_PTR_STRUCT_ERROR,
REL_6_PDAS_STRUCT_ERROR,
REL_6_PUAS_STRUCT_ERROR,
REL_6_PTR_STRUCT_ERROR,
//#endif
//#ifdef __PS_HO__
/*GLOBAL_AND_EXTENDED_TIMING_ADV_STRUCT_ERROR,
PS_HO_DOWNLINK_TBF_ASSIGN_STRUCT_ERROR,
PS_HO_EDGE_DL_STRUCT_ERROR,
PS_HO_EDGE_DL_EXIST_ERROR,
GPRS_MODE_STRUCT_ERROR,
EGPRS_MODE_STRUCT_ERROR,
PS_HO_RADIO_RESOURCE_STRUCT_ERROR,
PS_HO_TO_GERAN_STRUCT_ERROR,
PS_HO_COMMAND_STRUCT_ERROR,*/
//#endif
ACK_NACK_DESC_STRUCT_ERROR,

// Evelyn: Merge CSN generated Error_struct_enum
DYNAMIC_ALLOCATION_2_STRUCT_ERROR,
ASSIGNMENT_INFO_STRUCT_ERROR,
ENHANCED_MEASUREMENT_REPORT_STRUCT_ERROR,
EXTENDED_MEASUREMENT_REPORT_STRUCT_ERROR,
GPRS_SUSPENSION_REQUEST_STRUCT_ERROR,
HANDOVER_FAILURE_STRUCT_ERROR,
ASSIGNMENT_FAILURE_STRUCT_ERROR,
ASSIGNMENT_COMPLETE_STRUCT_ERROR,
UPLINK_ASSIGNMENT_2_STRUCT_ERROR,
BTTI_MULTIPLE_DOWNLINK_ASSIGNMENT_STRUCT_ERROR,
RTTI_MULTIPLE_DOWNLINK_ASSIGNMENT_SC_STRUCT_ERROR,
RTTI_MULTIPLE_DOWNLINK_ASSIGNMENT_DC_STRUCT_ERROR,
MULTIPLE_UPLINK_ASSIGNMENT_2_STRUCT_ERROR,
PDCH_PAIRS_DESCRIPTION_IE_FOR_MTTR_ERROR,
PACKET_CONTROL_ACKNOWLEDGEMENT_MESSAGE_CONTENT_ERROR,
PACKET_CONTROL_ACKNOWLEDGEMENT_11_BIT_MESSAGE_ERROR,
PACKET_CONTROL_ACKNOWLEDGEMENT_8_BIT_MESSAGE_ERROR,
PACKET_CELL_CHANGE_FAILURE_MESSAGE_CONTENT_ERROR,
PACKET_CELL_CHANGE_NOTIFICATION_MESSAGE_CONTENT_ERROR,
PACKET_DOWNLINK_ACK_NACK_MESSAGE_CONTENT_ERROR,
PACKET_UPLINK_DUMMY_CONTROL_BLOCK_MESSAGE_CONTENT_ERROR,
PACKET_MEASUREMENT_REPORT_MESSAGE_CONTENT_ERROR,
PACKET_MOBILE_TBF_STATUS_MESSAGE_CONTENT_ERROR,
PACKET_PSI_STATUS_MESSAGE_CONTENT_ERROR,
PACKET_SI_STATUS_MESSAGE_CONTENT_ERROR,
PACKET_PAUSE_MESSAGE_CONTENT_ERROR,
ADDITIONAL_MS_RADIO_ACCESS_CAPABILITIES_MESSAGE_CONTENT_ERROR,
MS_NETWORK_CAPABILITY_VALUE_PART_ERROR,
P_3_G_NEIGHBOUR_CELL_DESCRIPTION_STRUCT_MI_ERROR,
HANDOVER_COMPLETE_MESG_STRUCT_ERROR,
PAGING_RESPONSE_ERROR,
CSN_PAGING_REQUEST_TYPE1_ERROR,
PACKET_ENHANCED_MEASUREMENT_REPORT_MESSAGE_CONTENT_ERROR,
PACKET_RESOURCE_REQUEST_MESSAGE_CONTENT_ERROR,
MEASUREMENT_INFORMATION_STRUCT_ERROR,
MEASUREMENT_REPORT_STRUCT_ERROR,
PACKET_TIMESLOT_RECONFIGURE_MESSAGE_CONTENT_ERROR,
PACKET_UPLINK_ACK_NACK_MESSAGE_CONTENT_ERROR,
PACKET_TBF_RELEASE_MESSAGE_CONTENT_ERROR,
PSI16_MESSAGE_CONTENT_ERROR,
PSI15_MESSAGE_CONTENT_ERROR,
PSI14_MESSAGE_CONTENT_ERROR,
PSI13_MESSAGE_CONTENT_ERROR,
PSI8_MESSAGE_CONTENT_ERROR,
PSI7_MESSAGE_CONTENT_ERROR,
PSI6_MESSAGE_CONTENT_ERROR,
PSI4_MESSAGE_CONTENT_ERROR,
PSI3_QUATER_MESSAGE_CONTENT_ERROR,
PSI3_TER_MESSAGE_CONTENT_ERROR,
PSI3_BIS_MESSAGE_CONTENT_ERROR,
PSI3_MESSAGE_CONTENT_ERROR,
PSI1_MESSAGE_CONTENT_ERROR,
PACKET_SERVING_CELL_DATA_MESSAGE_CONTENT_ERROR,
PACKET_QUEUEING_NOTIFICATION_MESSAGE_CONTENT_ERROR,
PACKET_PRACH_PARAMETERS_MESSAGE_CONTENT_ERROR,
PACKET_POWER_CONTROL_TIMING_ADVANCE_MESSAGE_CONTENT_ERROR,
PACKET_POLLING_REQUEST_MESSAGE_CONTENT_ERROR,
PACKET_PDCH_RELEASE_MESSAGE_CONTENT_ERROR,
PACKET_PAGING_REQUEST_MESSAGE_CONTENT_ERROR,
PACKET_NEIGHBOUR_CELL_DATA_MESSAGE_CONTENT_ERROR,
PACKET_DOWNLINK_DUMMY_CONTROL_BLOCK_MESSAGE_CONTENT_ERROR,
PACKET_DOWNLINK_ASSIGNMENT_MESSAGE_CONTENT_ERROR,
PACKET_CELL_CHANGE_CONTINUE_MESSAGE_CONTENT_ERROR,
PACKET_ACCESS_REJECT_MESSAGE_CONTENT_ERROR,
PACKET_UPLINK_ASSIGNMENT_MESSAGE_CONTENT_ERROR,
MULTIPLE_TBF_DOWNLINK_ASSIGNMENT_MESSAGE_CONTENT_ERROR,
MULTIPLE_TBF_UPLINK_ASSIGNMENT_MESSAGE_CONTENT_ERROR,
PS_HANDOVER_COMMAND_MESSAGE_CONTENT_ERROR,
MULTIPLE_TBF_TIMESLOT_RECONFIGURE_MESSAGE_CONTENT_ERROR,
PS_HANDOVER_RADIO_RESOURCES_2_IE_ERROR,
EGPRS_PACKET_DOWNLINK_ACK_NACK_MESSAGE_CONTENT_ERROR,
MS_RA_CAPABILITY_VALUE_PART_STRUCT_ERROR,
PSI5_MESSAGE_CONTENT_ERROR,
PSI2_MESSAGE_CONTENT_ERROR,
PACKET_MEASUREMENT_ORDER_MESSAGE_CONTENT_ERROR,
PACKET_CELL_CHANGE_ORDER_MESSAGE_CONTENT_ERROR,
CHANNEL_RELEASE_STRUCT_ERROR,
RR_PEER_CLASSMARK_CHANGE_STRUCT_ERROR,
PAGING_REQUEST_TYPE1_STRUCT_ERROR,
PAGING_REQUEST_TYPE2_STRUCT_ERROR,
PAGING_REQUEST_TYPE3_STRUCT_ERROR,
MEASUREMENT_INFORMATION_ERROR,
SI_2TER_STRUCT_ERROR,
SI_2QUATER_STRUCT_ERROR,
RR_EM_CELL_SELECT_PARA_INFO_STRUCT_ERROR,
RR_EM_CHANNEL_DESCR_INFO_STRUCT_ERROR,
RR_EM_CTRL_CHANNEL_DESCR_INFO_STRUCT_ERROR,
RR_EM_RACH_CTRL_PARA_INFO_STRUCT_ERROR,
RR_EM_RADIO_LINK_COUNTER_INFO_STRUCT_ERROR,
RR_EM_CA_LIST_INFO_STRUCT_ERROR,
RR_EM_CONTROL_MSG_INFO_STRUCT_ERROR,
RR_EM_SI2Q_INFO_STRUCT_ERROR,
RR_EM_MI_INFO_STRUCT_ERROR,
RR_EM_MEASUREMENT_REPORT_INFO_STRUCT_ERROR,
ENUM_ERROR_STRUCT_TYPE_END
}enum_error_struct_type;

typedef enum {
CSN_NOT_ERROR=0,
CSN_UNRECOVERABLE_ERROR,
CSN_ERRORTYPE_END
}CSN_ErrorType;

#endif /* _ERROR_STRUCT_ENUM_H */

