/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  l1edps_SCH_SYNC_Handover_01.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *  Parameters define value between SS and UE
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * removed!
 * removed!
 * L1S script mod.
 *
 * removed!
 * removed!
 * . modify L1S header file.
 *
 ****************************************************************************/



#ifndef _L1SS_SCH_SYNC_Handover_01_H
#define _L1SS_SCH_SYNC_Handover_01_H

#include "l1edps_common_parameters.h"

//#undef PHYS_CELL_ID_BTS1
#undef MIB_DL_BANDWIDTH_BTS1	
#undef DL_EARFCN_BTS1
#undef RRC_SETUP_DRX_CONFIG_BTS1
#undef RRC_SETUP_ON_DURATION_TIMER_BTS1
#undef RRC_SETUP_DRX_INACTIVITY_TIMER_BTS1
#undef RRC_SETUP_DRX_RETRANSMISSION_TIMER_BTS1
#undef RRC_SETUP_LONG_DRX_CYCLE_BTS1
#undef RRC_SETUP_SHORT_DRX_SETUP_BTS1
#undef RRC_RECONFIG_REPORT_EVENT_A3_OFFSET_BTS1
#undef RRC_RECONFIG_GAP_CONFIG_SETUP_BTS1
#undef RRC_RECONFIG_GAP_PATTERN_BTS1
//#undef RRC_RECONFIG_GAP_OFFSET_gp0_BTS1
#undef RRC_RECONFIG_FILTER_COEFFICIENT_RSRP_BTS1

//#undef PHYS_CELL_ID_BTS2
#undef MIB_DL_BANDWIDTH_BTS2	
#undef DL_EARFCN_BTS2
#undef SIB2_PRACH_CONFIG_INDEX_BTS2

//#define PHYS_CELL_ID_BTS1 0
#define MIB_DL_BANDWIDTH_BTS1 BW_100_RB
#define DL_EARFCN_BTS1 900
#define RRC_SETUP_DRX_CONFIG_BTS1 L1S_SETUP
#define RRC_SETUP_ON_DURATION_TIMER_BTS1 ON_DURATION_TIMER_psf6 
#define RRC_SETUP_DRX_INACTIVITY_TIMER_BTS1 DRX_INACTIVITY_TIMER_psf1920
#define RRC_SETUP_DRX_RETRANSMISSION_TIMER_BTS1 DRX_RETRANSMISSION_TIMER_psf16
#define RRC_SETUP_LONG_DRX_CYCLE_BTS1 LONG_DRX_CYCLE_sf1280
#define RRC_SETUP_SHORT_DRX_SETUP_BTS1 L1S_RELEASE
#define RRC_RECONFIG_REPORT_EVENT_A3_OFFSET_BTS1 -4
#define RRC_RECONFIG_GAP_CONFIG_SETUP_BTS1 L1S_SETUP
#define RRC_RECONFIG_GAP_PATTERN_BTS1 GAP_PATTERN_gp0
//#define RRC_RECONFIG_GAP_OFFSET_gp0_BTS1 0
#define RRC_RECONFIG_FILTER_COEFFICIENT_RSRP_BTS1 FILTER_COEFFICIENT_fc0

//#define PHYS_CELL_ID_BTS2 1
#define MIB_DL_BANDWIDTH_BTS2 BW_100_RB
#define DL_EARFCN_BTS2 1100
#define SIB2_PRACH_CONFIG_INDEX_BTS2 63

#undef SIB2_REFERENCE_SIGNAL_POWER_BTS1
#define SIB2_REFERENCE_SIGNAL_POWER_BTS1 0

#undef SIB2_REFERENCE_SIGNAL_POWER_BTS2
#define SIB2_REFERENCE_SIGNAL_POWER_BTS2 0


#endif







