/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2013
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#ifndef __SDIO_INIT_H__
#define __SDIO_INIT_H__

#include "reg_base.h"

/*************************************************************************
 * Define exported function prototype
 *************************************************************************/
extern void boot_init_sdio_clock();

#ifdef MT6290

#define ORG_SDIO_BASE	BASE_ADDR_SDIO

#define ORG_SDIO_PAD_CR_SET_BY_FW   0x10000000

/* SDIO QMU  Register */
#define ORG_SDIO_HGFCR				(volatile kal_uint32 *)(ORG_SDIO_BASE+0x0000)
#define ORG_SDIO_HGFISR				(volatile kal_uint32 *)(ORG_SDIO_BASE+0x0004)
#define ORG_SDIO_HGFIER				(volatile kal_uint32 *)(ORG_SDIO_BASE+0x0008)

/*  Pad Macro related register  */
#define ORG_SDIO_FWCLKIOCR          (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0040)	
#define ORG_SDIO_FWCMDIOCR          (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0044)	
#define ORG_SDIO_FWDAT0IOCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0048)	
#define ORG_SDIO_FWDAT1IOCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x004C)	
#define ORG_SDIO_FWDAT2IOCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0050)	
#define ORG_SDIO_FWDAT3IOCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0054)	
#define ORG_SDIO_FWCLKDLYCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0058)	
#define ORG_SDIO_FWCMDDLYCR         (volatile kal_uint32 *)(ORG_SDIO_BASE+0x005C)	
#define ORG_SDIO_FWODATDLYCR        (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0060)	
#define ORG_SDIO_FWIDATDLYCR1       (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0064)	
#define ORG_SDIO_FWIDATDLYCR2       (volatile kal_uint32 *)(ORG_SDIO_BASE+0x0068)	
#define ORG_SDIO_FWILCHCR           (volatile kal_uint32 *)(ORG_SDIO_BASE+0x006C)	

#define ORG_SDIO_PAD_CLK_PUPD       0x00000010
#define ORG_SDIO_PAD_50K_RESISTOR       0x00000008
#define ORG_SDIO_PAD_10K_RESISTOR       0x00000004




#define SDIO_CTRL_HGFCR      ORG_SDIO_HGFCR   
#define SDIO_PAD_CR_SET_BY_FW    ORG_SDIO_PAD_CR_SET_BY_FW 

/*  Pad Macro related register  */
#define SDIO_PAD_FWCLKIOCR     ORG_SDIO_FWCLKIOCR  	
#define SDIO_PAD_FWCMDIOCR     ORG_SDIO_FWCMDIOCR  	
#define SDIO_PAD_FWDAT0IOCR    ORG_SDIO_FWDAT0IOCR  	
#define SDIO_PAD_FWDAT1IOCR    ORG_SDIO_FWDAT1IOCR  	
#define SDIO_PAD_FWDAT2IOCR    ORG_SDIO_FWDAT2IOCR  	
#define SDIO_PAD_FWDAT3IOCR    ORG_SDIO_FWDAT3IOCR  	
#define SDIO_PAD_FWCLKDLYCR    ORG_SDIO_FWCLKDLYCR  	
#define SDIO_PAD_FWCMDDLYCR    ORG_SDIO_FWCMDDLYCR  	
#define SDIO_PAD_FWODATDLYCR   ORG_SDIO_FWODATDLYCR  	
#define SDIO_PAD_FWIDATDLYCR1  ORG_SDIO_FWIDATDLYCR1  	
#define SDIO_PAD_FWIDATDLYCR2  ORG_SDIO_FWIDATDLYCR2  	
#define SDIO_PAD_FWILCHCR      ORG_SDIO_FWILCHCR  

#define SDIO_PAD_CLK_PUPD           ORG_SDIO_PAD_CLK_PUPD
#define SDIO_PAD_50K_RESISTOR       ORG_SDIO_PAD_50K_RESISTOR
#define SDIO_PAD_10K_RESISTOR       ORG_SDIO_PAD_10K_RESISTOR 

#endif /* MT6290 */
#endif /* !__SDIO_INIT_H__ */
