/*******************************************************************************
*  Modification Notice:
*  --------------------------
*  This software is modified by MediaTek Inc. and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*******************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   l1edps_sap.h
 *
 * Project:
 * --------
 *   TATAKA
 *
 * Description:
 * ------------
 *   LTE Dummy Protocol Stack, SAP definition
 *
 * Author:
 * -------
 * -------
 *
 ****************************************************************************/
#include "module_msg_range.h"
#ifndef _L1EDPS_SAP_H
#define _L1EDPS_SAP_H

MODULE_MSG_BEGIN( MSG_ID_L1EDPS_CODE_BEGIN )

MSG_ID_L1EDPS_NOCH_CSR_01 = MSG_ID_L1EDPS_CODE_BEGIN ,
MSG_ID_L1EDPS_NOCH_CSR_02,
MSG_ID_L1EDPS_NOCH_CSR_03,
MSG_ID_L1EDPS_NOCH_CSR_04,
MSG_ID_L1EDPS_NOCH_CSR_05,
MSG_ID_L1EDPS_NOCH_CSR_06,
MSG_ID_L1EDPS_NOCH_CSR_07,
MSG_ID_L1EDPS_NOCH_CSR_08,
MSG_ID_L1EDPS_NOCH_CSR_09,
MSG_ID_L1EDPS_NOCH_CSR_10,
MSG_ID_L1EDPS_NOCH_CSR_11,
MSG_ID_L1EDPS_NOCH_SCS_01,
MSG_ID_L1EDPS_NOCH_RESET_01,
MSG_ID_L1EDPS_IDLE_CSR_01,
MSG_ID_L1EDPS_IDLE_CSR_02,
MSG_ID_L1EDPS_IDLE_BCCH_01,
MSG_ID_L1EDPS_IDLE_BCCH_02,
MSG_ID_L1EDPS_IDLE_BCCH_03,
MSG_ID_L1EDPS_IDLE_BCCH_04,
MSG_ID_L1EDPS_IDLE_PCH_01,
MSG_ID_L1EDPS_IDLE_PCH_02,
MSG_ID_L1EDPS_IDLE_PCH_03,
MSG_ID_L1EDPS_IDLE_PCH_TDD_01,
MSG_ID_L1EDPS_IDLE_PCH_TDD_02,
MSG_ID_L1EDPS_IDLE_PWS_01,
MSG_ID_L1EDPS_IDLE_CELL_RESEL_01,
MSG_ID_L1EDPS_IDLE_CELL_RESEL_02,
MSG_ID_L1EDPS_IDLE_CELL_RESEL_03,
MSG_ID_L1EDPS_IDLE_CELL_RESEL_04,
MSG_ID_L1EDPS_IDLE_PLMN_LIST_01,
MSG_ID_L1EDPS_IDLE_PLMN_LIST_02,
MSG_ID_L1EDPS_IDLE_OOS_01,
MSG_ID_L1EDPS_IDLE_OOS_02,
MSG_ID_L1EDPS_IDLE_OOS_03,
MSG_ID_L1EDPS_IDLE_OOS_04,
MSG_ID_L1EDPS_IDLE_SCH_RA_01,
MSG_ID_L1EDPS_IDLE_SCH_RA_02,
MSG_ID_L1EDPS_IDLE_SCH_RA_03,
MSG_ID_L1EDPS_IDLE_SCH_RA_04,
MSG_ID_L1EDPS_IDLE_SCH_RA_05,
MSG_ID_L1EDPS_IDLE_SCH_RA_06,
MSG_ID_L1EDPS_IDLE_SCH_RA_07,
MSG_ID_L1EDPS_IDLE_SCH_RA_08,
MSG_ID_L1EDPS_IDLE_SCH_CONN_EST_01,
MSG_ID_L1EDPS_SCH_TPC_01,
MSG_ID_L1EDPS_SCH_TPC_02,
MSG_ID_L1EDPS_SCH_TPC_03,
MSG_ID_L1EDPS_SCH_TPC_04,
MSG_ID_L1EDPS_SCH_TPC_05,
MSG_ID_L1EDPS_SCH_TPC_06,
MSG_ID_L1EDPS_SCH_TX_01,
MSG_ID_L1EDPS_SCH_TX_02,
MSG_ID_L1EDPS_SCH_TX_03,
MSG_ID_L1EDPS_SCH_TX_04,
MSG_ID_L1EDPS_SCH_TX_05,
MSG_ID_L1EDPS_SCH_TX_06,
MSG_ID_L1EDPS_SCH_TRX_01,
MSG_ID_L1EDPS_SCH_TRX_02,
MSG_ID_L1EDPS_SCH_TRX_GAP,
MSG_ID_L1EDPS_SCH_PC_01,
MSG_ID_L1EDPS_SCH_PCQI_01,
MSG_ID_L1EDPS_SCH_ACQI_01,
MSG_ID_L1EDPS_SCH_HANDOVER_01,
MSG_ID_L1EDPS_SCH_HANDOVER_02,
MSG_ID_L1EDPS_SCH_HANDOVER_03,
MSG_ID_L1EDPS_SCH_HANDOVER_04,
MSG_ID_L1EDPS_SCH_HANDOVER_05,
MSG_ID_L1EDPS_SCH_HANDOVER_06,
MSG_ID_L1EDPS_SCH_SYNC_HANDOVER_01,
MSG_ID_L1EDPS_SCH_INTRAHO_01,
MSG_ID_L1EDPS_SCH_REDIRECTION_01,
MSG_ID_L1EDPS_SCH_REDIRECTION_02,
MSG_ID_L1EDPS_SCH_REDIRECTION_03,
MSG_ID_L1EDPS_SCH_REDIRECTION_04,
MSG_ID_L1EDPS_SCH_CSG_01,
MSG_ID_L1EDPS_SCH_CSG_02,
MSG_ID_L1EDPS_SCH_SI_MODIFY_01,
MSG_ID_L1EDPS_SCH_PWS_01,
MSG_ID_L1EDPS_SCH_PAG_GAP_01,
MSG_ID_L1EDPS_SCH_CONN_REEST_01,
MSG_ID_L1EDPS_SCH_CONN_REEST_02,
MSG_ID_L1EDPS_SCH_CONN_REEST_03,
MSG_ID_L1EDPS_SCH_CONN_REEST_04,
MSG_ID_L1EDPS_SCH_RLM_01,
MSG_ID_L1EDPS_SCH_RLM_02,
MSG_ID_L1EDPS_SCH_RLM_03,
MSG_ID_L1EDPS_SCH_RLM_04,
MSG_ID_L1EDPS_SCH_RLM_05,
MSG_ID_L1EDPS_SCH_RLM_06,
MSG_ID_L1EDPS_SCH_RLM_07,
MSG_ID_L1EDPS_SCH_RLM_08,
MSG_ID_L1EDPS_SCH_RLM_DRX_01,
MSG_ID_L1EDPS_SCH_RLM_DRX_02,
MSG_ID_L1EDPS_SCH_RLM_DRX_03,
MSG_ID_L1EDPS_SCH_RLM_DRX_04,
MSG_ID_L1EDPS_SCH_DRX_TRANS_01,
MSG_ID_L1EDPS_BCCH_MEASUREMENT_01,
MSG_ID_L1EDPS_BCCH_MEASUREMENT_02,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_01,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_02,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_03,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_04,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_05,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_06,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_07,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_08,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_09,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_10,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_11,
MSG_ID_L1EDPS_IDLE_MEASUREMENT_12,
MSG_ID_L1EDPS_IDLE_SCH_MEASUREMENT_01,
MSG_ID_L1EDPS_IDLE_SCH_MEASUREMENT_02,
MSG_ID_L1EDPS_SCH_MEASUREMENT_01,
MSG_ID_L1EDPS_SCH_MEASUREMENT_02,
MSG_ID_L1EDPS_SCH_MEASUREMENT_03,
MSG_ID_L1EDPS_SCH_MEASUREMENT_04,
MSG_ID_L1EDPS_SCH_MEASUREMENT_05,
MSG_ID_L1EDPS_SCH_MEASUREMENT_06,
MSG_ID_L1EDPS_SCH_MEASUREMENT_07,
MSG_ID_L1EDPS_SCH_MEASUREMENT_08,
MSG_ID_L1EDPS_SCH_MEASUREMENT_09,
MSG_ID_L1EDPS_SCH_MEASUREMENT_10,
MSG_ID_L1EDPS_SCH_MEASUREMENT_11,
MSG_ID_L1EDPS_SCH_MEASUREMENT_12,
MSG_ID_L1EDPS_OTDOA_MEASUREMENT_01,
MSG_ID_L1EDPS_OTDOA_MEASUREMENT_02,
MSG_ID_L1EDPS_OTDOA_MEASUREMENT_03,
MSG_ID_L1EDPS_OTDOA_MEASUREMENT_04,
//add MSG ID Before this line
MSG_ID_L1EDPS_START_RUN_L1S_CASE,

MODULE_MSG_END(MSG_ID_L1EDPS_CODE_TAIL)
#endif /* _L1EDPS_SAP_H */

