/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   upcm_msgid.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *   UPCM and Protocol Stack related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * Interface Check-in
 *
 * removed!
 * removed!
 * add PDN Bind related structure and enum.
 *
 * removed!
 * removed!
 * interface - sap part
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _UPCM_MSGID_H
#define _UPCM_MSGID_H


MODULE_MSG_BEGIN( MSG_ID_UPCM_CODE_BEGIN )

MSG_ID_TCM_UPCM_BEARER_ACT_REQ = MSG_ID_UPCM_CODE_BEGIN,
MSG_ID_TCM_UPCM_BEARER_DEACT_REQ,
MSG_ID_TCM_UPCM_PDN_BIND_REQ,
MSG_ID_TCM_UPCM_PDN_BIND_CNF,
MSG_ID_TCM_UPCM_PDN_UNBIND_REQ,
MSG_ID_TCM_UPCM_PDN_UNBIND_CNF,
MSG_ID_TCM_UPCM_PF_UPDATE_REQ,
MSG_ID_RAT_TCM_UPCM_SUSPEND_REQ,
MSG_ID_RAT_TCM_UPCM_RESUME_REQ,

MSG_ID_IPCORE_UPCM_PDN_BIND_IND,
MSG_ID_IPCORE_UPCM_PDN_BIND_RSP,
MSG_ID_IPCORE_UPCM_PDN_DEACT_IND,

MSG_ID_MNY_UPCM_SUSPEND_REQ,
MSG_ID_MNY_UPCM_RESUME_REQ,

MODULE_MSG_END( MSG_ID_UPCM_CODE_TAIL )

#endif /* _UPCM_MSGID_H */
