#ifndef __PERI_PWRAP_BRIDGE_REGS_H__
#define __PERI_PWRAP_BRIDGE_REGS_H__

#include "reg_base.h"

#define PERI_PWRAP_BRIDGE_BASE (AP_PERI_PWRAP_BRIDGE_base)

#define PERI_PWRAP_BRIDGE_IARB_INIT             (PERI_PWRAP_BRIDGE_BASE+0x0)
#define PERI_PWRAP_BRIDGE_IORD_ARB_EN           (PERI_PWRAP_BRIDGE_BASE+0x4)
#define PERI_PWRAP_BRIDGE_IARB_STA0             (PERI_PWRAP_BRIDGE_BASE+0x8)
#define PERI_PWRAP_BRIDGE_IARB_STA1             (PERI_PWRAP_BRIDGE_BASE+0xC)
#define PERI_PWRAP_BRIDGE_WACS3_EN              (PERI_PWRAP_BRIDGE_BASE+0x10)
#define PERI_PWRAP_BRIDGE_INIT_DONE3            (PERI_PWRAP_BRIDGE_BASE+0x14)
#define PERI_PWRAP_BRIDGE_WACS3_CMD             (PERI_PWRAP_BRIDGE_BASE+0x18)
#define PERI_PWRAP_BRIDGE_WACS3_RDATA           (PERI_PWRAP_BRIDGE_BASE+0x1C)
#define PERI_PWRAP_BRIDGE_WACS3_VLDCLR          (PERI_PWRAP_BRIDGE_BASE+0x20)
#define PERI_PWRAP_BRIDGE_WACS4_EN              (PERI_PWRAP_BRIDGE_BASE+0x24)
#define PERI_PWRAP_BRIDGE_INIT_DONE4            (PERI_PWRAP_BRIDGE_BASE+0x28)
#define PERI_PWRAP_BRIDGE_WACS4_CMD             (PERI_PWRAP_BRIDGE_BASE+0x2C)
#define PERI_PWRAP_BRIDGE_WACS4_RDATA           (PERI_PWRAP_BRIDGE_BASE+0x30)
#define PERI_PWRAP_BRIDGE_WACS4_VLDCLR          (PERI_PWRAP_BRIDGE_BASE+0x34)
#define PERI_PWRAP_BRIDGE_INT_EN                (PERI_PWRAP_BRIDGE_BASE+0x38)
#define PERI_PWRAP_BRIDGE_INT_FLG_RAW           (PERI_PWRAP_BRIDGE_BASE+0x3C)
#define PERI_PWRAP_BRIDGE_INT_FLG               (PERI_PWRAP_BRIDGE_BASE+0x40)
#define PERI_PWRAP_BRIDGE_INT_CLR               (PERI_PWRAP_BRIDGE_BASE+0x44)
#define PERI_PWRAP_BRIDGE_TIMER_EN              (PERI_PWRAP_BRIDGE_BASE+0x48)
#define PERI_PWRAP_BRIDGE_TIMER_STA             (PERI_PWRAP_BRIDGE_BASE+0x4C)
#define PERI_PWRAP_BRIDGE_WDT_UNIT              (PERI_PWRAP_BRIDGE_BASE+0x50)
#define PERI_PWRAP_BRIDGE_WDT_SRC_EN            (PERI_PWRAP_BRIDGE_BASE+0x54)
#define PERI_PWRAP_BRIDGE_WDT_FLG               (PERI_PWRAP_BRIDGE_BASE+0x58)
#define PERI_PWRAP_BRIDGE_DEBUG_INT_SEL         (PERI_PWRAP_BRIDGE_BASE+0x5C)


#define GET_WACS3_RDATA(x)           ((x>>0)  & 0x0000ffff)
#define GET_WACS3_FSM(x)             ((x>>16) & 0x00000007)
#define GET_WACS3_REQ(x)             ((x>>19) & 0x00000001)
#define GET_SYNC_IDLE3(x)            ((x>>20) & 0x00000001)
#define GET_INIT_DONE3(x)            ((x>>21) & 0x00000001)
#define GET_WACS4_RDATA(x)           ((x>>0)  & 0x0000ffff)
#define GET_WACS4_FSM(x)             ((x>>16) & 0x00000007)
#define GET_WACS4_REQ(x)             ((x>>19) & 0x00000001)
#define GET_SYNC_IDLE4(x)            ((x>>20) & 0x00000001)
#define GET_INIT_DONE4(x)            ((x>>21) & 0x00000001)

#endif //__PERI_PWRAP_BRIDGE_REGS_H__

