cp ./interface/service/kal/kal_general_types.h $1/kal_general_types.h
cp ./interface/service/config/middleWare_task_config.h $1/middleWare_task_config.h
cp ./interface/service/config/modem_2g3g_task_config.h $1/modem_2g3g_task_config.h
cp ./interface/service/config/drv_task_config.h $1/drv_task_config.h
cp ./interface/service/config/modem_4g_task_config.h $1/modem_4g_task_config.h
cp ./interface/sap/module_hisrid_range.h $1/module_hisrid_range.h
cp ./interface/service/config/srv_task_config.h $1/srv_task_config.h
cp ./interface/service/kal/kal_public_defs.h $1/kal_public_defs.h
cp ./interface/service/config/stack_config.h $1/stack_config.h
cp ./interface/service/config/hisr_config_internal.h $1/hisr_config_internal.h
cp ./interface/service/kal/clib.h $1/clib.h
cp ./interface/service/kal/clib_list.h $1/clib_list.h
cp ./interface/sap/module_id_range.h $1/module_id_range.h
cp ./interface/sap/hisr_modid.h $1/hisr_modid.h
cp ./interface/sap/middleware_modid.h $1/middleware_modid.h
cp ./interface/sap/modem_2g3g_modid.h $1/modem_2g3g_modid.h
cp ./interface/sap/srv_modid.h $1/srv_modid.h
cp ./interface/sap/modem_4g_modid.h $1/modem_4g_modid.h
cp ./interface/service/config/stack_msgs.h $1/stack_msgs.h
cp ./interface/sap/drv_modid.h $1/drv_modid.h
cp ./interface/service/kal/kal_public_api.h $1/kal_public_api.h
cp ./interface/service/dhl/dhl_trace.h $1/dhl_trace.h
cp ./interface/driver/peripheral/dcl.h $1/dcl.h
cp ./interface/modem/general/ps_public_enum.h $1/ps_public_enum.h
cp ./interface/service/nvram/nvram_defs.h $1/nvram_defs.h
cp ./interface/modem/general/ps_public_struct.h $1/ps_public_struct.h
cp ./interface/service/dhl/kal_trace.h $1/kal_trace.h
cp ./interface/service/nvram/nvram_enums.h $1/nvram_enums.h
cp ./interface/common/global_def.h $1/global_def.h
cp ./modem/interface/l4misc/l3_inc_enums.h $1/l3_inc_enums.h
cp ./driver/drv_def/drv_features_chip_select.h $1/drv_features_chip_select.h
cp ./driver/drv_def/drv_features_gpio.h $1/drv_features_gpio.h
cp ./driver/devdrv/drv_def/drv_features_6290.h $1/drv_features_6290.h
cp ./interface/service/config/stack_buff_pool.h $1/stack_buff_pool.h
cp ./modem/interface/general/irat_common_enums.h $1/irat_common_enums.h
cp ./interface/service/config/ctrl_buff_pool.h $1/ctrl_buff_pool.h
cp ./interface/modem/general/sim_public_enum.h $1/sim_public_enum.h
cp ./custom/service/nvram/custom_nvram_sec.h $1/custom_nvram_sec.h
cp ./interface/modem/general/sim_ps_enum.h $1/sim_ps_enum.h
cp ./interface/modem/lte/el1_rf_public.h $1/el1_rf_public.h
cp ./interface/service/config/hisr_config.h $1/hisr_config.h
cp ./interface/service/config/stack_types.h $1/stack_types.h
cp ./interface/sap/module_msg_range.h $1/module_msg_range.h
cp ./interface/sap/sap_range.h $1/sap_range.h
cp ./interface/driver/peripheral/dcl_uart.h $1/dcl_uart.h
cp ./interface/driver/peripheral/dcl_msdc.h $1/dcl_msdc.h
cp ./interface/driver/peripheral/dcl_gpt.h $1/dcl_gpt.h
cp ./interface/driver/peripheral/dcl_gpio.h $1/dcl_gpio.h
cp ./interface/driver/peripheral/dcl_wdt.h $1/dcl_wdt.h
cp ./interface/driver/peripheral/dcl_idc.h $1/dcl_idc.h
cp ./interface/driver/peripheral/dcl_f32k_clk.h $1/dcl_f32k_clk.h
cp ./interface/driver/peripheral/dcl_adc.h $1/dcl_adc.h
cp ./interface/driver/connectivity/usb_driver/dcl_usb_drv.h $1/dcl_usb_drv.h
cp ./interface/driver/peripheral/dcl_sts.h $1/dcl_sts.h
cp ./interface/driver/peripheral/dcl_sim.h $1/dcl_sim.h
cp ./interface/driver/peripheral/dcl_rtc.h $1/dcl_rtc.h
cp ./interface/driver/peripheral/DclS_kbd.h $1/DclS_kbd.h
cp ./interface/driver/peripheral/dcl_pw.h $1/dcl_pw.h
cp ./interface/driver/peripheral/dcl_pfc.h $1/dcl_pfc.h
cp ./interface/driver/peripheral/DclH_kbd.h $1/DclH_kbd.h
cp ./interface/driver/peripheral/dcl_chr_det.h $1/dcl_chr_det.h
cp ./interface/driver/peripheral/dcl_bmt.h $1/dcl_bmt.h
cp ./interface/driver/peripheral/dcl_sim_gpio.h $1/dcl_sim_gpio.h
cp ./interface/driver/peripheral/dcl_pmu.h $1/dcl_pmu.h
cp ./interface/modem/general/cmux_vp_num.h $1/cmux_vp_num.h
cp ./interface/modem/general/em_public_struct.h $1/em_public_struct.h
cp ./driver/drv_def/drv_features_adc.h $1/drv_features_adc.h
cp ./driver/regbase/inc/reg_base_mt6290.h $1/reg_base_mt6290.h
cp ./driver/regbase/inc/reg_base.h $1/reg_base.h
cp ./driver/drv_def/drv_features_sim.h $1/drv_features_sim.h
cp ./driver/drv_def/drv_features_rtc.h $1/drv_features_rtc.h
cp ./interface/modem/general/ps_em_enum.h $1/ps_em_enum.h
cp ./interface/modem/l1/fdd/external/ul1d_rf_cid.h $1/ul1d_rf_cid.h
cp ./interface/service/nvram/nvram_data_items.h $1/nvram_data_items.h
cp ./interface/service/stacklib/lcd_ip_cqueue.h $1/lcd_ip_cqueue.h
cp ./modem/interface/l4misc/l3_inc_local.h $1/l3_inc_local.h
cp ./driver/drv_def/drv_features_gpt.h $1/drv_features_gpt.h
cp ./interface/modem/l1/gsm/external/mph_types.h $1/mph_types.h
cp ./modem/interface/general/as_common.h $1/as_common.h
cp ./interface/service/config/kal_user_mem.h $1/kal_user_mem.h
cp ./interface/service/dhl/tst.h $1/tst.h
cp ./interface/service/event_info/event_info_utility.h $1/event_info_utility.h
cp ./interface/service/config/sysconf_statistics.h $1/sysconf_statistics.h
cp ./modem/gl1/l1_dm/common/l1_const.h $1/l1_const.h
cp ./modem/interface/general/irat_common_struct.h $1/irat_common_struct.h
cp ./interface/modem/mml1/mml1_rf_global.h $1/mml1_rf_global.h
cp ./interface/sap/svc/sysservice_msgid.h $1/sysservice_msgid.h
cp ./interface/service/config/task_config.h $1/task_config.h
cp ./interface/service/config/syscomp_config.h $1/syscomp_config.h
cp ./interface/middleware/meta/ft_msg_common.h $1/ft_msg_common.h
cp ./interface/modem/lte/el1_meta_if.h $1/el1_meta_if.h
cp ./interface/modem/lte/el1_rf_cid.h $1/el1_rf_cid.h
cp ./interface/service/hif/hmu_conf_data.h $1/hmu_conf_data.h
cp ./interface/modem/general/mmi_l3_enums.h $1/mmi_l3_enums.h
cp ./interface/middleware/hif/nmu.h $1/nmu.h
cp ./interface/modem/lte/el1_rf_public_mt6169.h $1/el1_rf_public_mt6169.h
cp ./interface/service/asn1_common/mtkasn_global.h $1/mtkasn_global.h
cp ./interface/modem/lte/el1_drdi.h $1/el1_drdi.h
cp ./interface/sap/md_sap.h $1/md_sap.h
cp ./interface/driver/sys_drv/cache_sw.h $1/cache_sw.h
cp ./interface/modem/general/em_struct.h $1/em_struct.h
cp ./driver/devdrv/cirq_v2/inc/irqid.h $1/irqid.h
cp ./interface/modem/l1/fdd/external/ul1d_rf_public.h $1/ul1d_rf_public.h
cp ./interface/modem/l1/fdd/internal/ul1_cnst.h $1/ul1_cnst.h
cp ./modem/interface/general/uas_common_enums.h $1/uas_common_enums.h
cp ./interface/modem/general/sim_common_enums.h $1/sim_common_enums.h
cp ./interface/driver/connectivity/usb_driver/dcl_usb_hcd.h $1/dcl_usb_hcd.h
cp ./interface/driver/peripheral/dcl_i2c.h $1/dcl_i2c.h
cp ./interface/driver/peripheral/dcl_pxs.h $1/dcl_pxs.h
cp ./interface/driver/peripheral/dcl_aux.h $1/dcl_aux.h
cp ./interface/driver/peripheral/dcl_irda.h $1/dcl_irda.h
cp ./interface/driver/peripheral/dcl_pwm.h $1/dcl_pwm.h
cp ./interface/driver/connectivity/usb_driver/dcl_otg_drv.h $1/dcl_otg_drv.h
cp ./interface/driver/peripheral/dcl_i2c_owner.h $1/dcl_i2c_owner.h
cp ./interface/service/dhl/L1Trc.h $1/L1Trc.h
cp ./interface/service/flc2/flc2_config.h $1/flc2_config.h
cp ./interface/sap/svc_sap.h $1/svc_sap.h
cp ./driver/devdrv/cirq_v2/inc/irqid_MT6290.h $1/irqid_MT6290.h
cp ./interface/driver/peripheral/drv_comm.h $1/drv_comm.h
cp ./interface/driver/sys_drv/intrCtrl.h $1/intrCtrl.h
cp ./interface/modem/l1/fdd/internal/ul1_def.h $1/ul1_def.h
cp ./modem/gl1/l1_dm/l1d_ext/l1d_cid.h $1/l1d_cid.h
cp ./driver/devdrv/cirq_v2/inc/drv_mdcirq.h $1/drv_mdcirq.h
cp ./driver/devdrv/cirq_v2/inc/drv_mdcirq_reg.h $1/drv_mdcirq_reg.h
cp ./interface/modem/general/sim_public_api.h $1/sim_public_api.h
cp ./driver/devdrv/cirq_v2/inc/intrCtrl_MT6290.h $1/intrCtrl_MT6290.h
cp ./interface/driver/sys_drv/isrentry.h $1/isrentry.h
cp ./driver/devdrv/cirq_v1/inc/intrCtrl_SW_Handle.h $1/intrCtrl_SW_Handle.h
cp ./driver/devdrv/cirq/inc/intrCtrl_MT6290_SW_Handle.h $1/intrCtrl_MT6290_SW_Handle.h
cp ./interface/modem/l1/fdd/external/ul1cal.h $1/ul1cal.h
cp ./interface/modem/general/sim_ps_api.h $1/sim_ps_api.h
cp ./interface/service/stacklib/lcd.h $1/lcd.h
cp ./interface/sap/md_drv_sap.h $1/md_drv_sap.h
cp ./modem/interface/l1/inner/l1_types.h $1/l1_types.h
cp ./modem/interface/l1/inner/l1_core_private.h $1/l1_core_private.h
cp ./interface/modem/l1/gsm/external/l1_option.h $1/l1_option.h
cp ./modem/interface/general/uas_gas_enums.h $1/uas_gas_enums.h
cp ./interface/service/qmu_bm/qmu_bm.h $1/qmu_bm.h
cp ./interface/service/asn1_common/asn_memory.h $1/asn_memory.h
cp ./interface/service/fsm/sm_type.h $1/sm_type.h
cp ./interface/service/asn1_common/asn_common.h $1/asn_common.h
cp ./modem/interface/general/l3llc_enums.h $1/l3llc_enums.h
cp ./modem/interface/general/mrs_as_enums.h $1/mrs_as_enums.h
cp ./modem/md_sm/common/l1sm/l1sm_internal_public.h $1/l1sm_internal_public.h
cp ./modem/gl1/l1_dm/common/tool.h $1/tool.h
cp ./interface/modem/general/tcm_api.h $1/tcm_api.h
cp ./modem/interface/l1/inner/l1_tool.h $1/l1_tool.h
cp ./modem/interface/l1/inner/l1_public.h $1/l1_public.h
cp ./interface/modem/l1/gsm/external/l1_types_public.h $1/l1_types_public.h
cp ./modem/interface/l1/inner/l1_core.h $1/l1_core.h
cp ./interface/sap/md/l4_msgid.h $1/l4_msgid.h
cp ./interface/modem/general/l4c_msg_hdlr_defs.h $1/l4c_msg_hdlr_defs.h
cp ./modem/interface/general/protocol_section.h $1/protocol_section.h
cp ./interface/modem/general/device.h $1/device.h
cp ./modem/interface/l1/gsm/mph_cnst.h $1/mph_cnst.h
cp ./modem/interface/general/tftlib_common_enum.h $1/tftlib_common_enum.h
cp ./driver/drv_def/drv_features_wdt.h $1/drv_features_wdt.h
cp ./modem/interface/l4/l4c_ratdm_struct.h $1/l4c_ratdm_struct.h
cp ./driver/drv_def/drv_features_pwm.h $1/drv_features_pwm.h
cp ./driver/drv_def/drv_features_gcu.h $1/drv_features_gcu.h
cp ./interface/service/fs/fs_gprot.h $1/fs_gprot.h
cp ./modem/interface/asn/rr/include/csn_common.h $1/csn_common.h
cp ./driver/drv_def/drv_features_misc.h $1/drv_features_misc.h
cp ./driver/drv_def/drv_features_hif.h $1/drv_features_hif.h
cp ./driver/drv_def/drv_features_accdet.h $1/drv_features_accdet.h
cp ./driver/drv_def/drv_features_msdc.h $1/drv_features_msdc.h
cp ./driver/drv_def/drv_features_f32k.h $1/drv_features_f32k.h
cp ./driver/drv_def/drv_features_uart.h $1/drv_features_uart.h
cp ./driver/drv_def/drv_features_pfc.h $1/drv_features_pfc.h
cp ./driver/drv_def/drv_features_bmt.h $1/drv_features_bmt.h
cp ./driver/drv_def/drv_features_i2c.h $1/drv_features_i2c.h
cp ./driver/drv_def/drv_features.h $1/drv_features.h
cp ./driver/drv_def/drv_features_spi.h $1/drv_features_spi.h
cp ./driver/drv_def/drv_features_usb.h $1/drv_features_usb.h
cp ./interface/driver/peripheral/adc_cali.h $1/adc_cali.h
cp ./interface/service/stacklib/lcd_cqueue.h $1/lcd_cqueue.h
cp ./interface/service/qmu_bm/qmu_bm_size.h $1/qmu_bm_size.h
cp ./modem/interface/general/divider_public.h $1/divider_public.h
cp ./modem/interface/l1/inner/l1_private.h $1/l1_private.h
cp ./modem/interface/general/gas_eas_enums.h $1/gas_eas_enums.h
cp ./modem/interface/l4misc/l4c_common_enum.h $1/l4c_common_enum.h
cp ./driver/sleep_drv/internal/inc/dcxo_div.h $1/dcxo_div.h
cp ./custom/modem/common/ps/ul1_nvram_def.h $1/ul1_nvram_def.h
cp ./modem/interface/l1/inner/l1_timertype.h $1/l1_timertype.h
cp ./modem/interface/general/rlc_mac_enums.h $1/rlc_mac_enums.h
cp ./interface/service/nvram/nvram_editor_data_item.h $1/nvram_editor_data_item.h
cp ./modem/l4/include/rmmi_common_enum.h $1/rmmi_common_enum.h
cp ./modem/interface/lte/tcm_eval_enums.h $1/tcm_eval_enums.h
cp ./interface/service/qmu_bm/qbm_features.h $1/qbm_features.h
cp ./modem/interface/asn/rr/include/gprs_rlcmac_common_struct.h $1/gprs_rlcmac_common_struct.h
cp ./modem/ul1/ul1_hs_plus/common/ul1_types.h $1/ul1_types.h
cp ./interface/service/qmu_bm/qmu_bm_in.h $1/qmu_bm_in.h
cp ./interface/service/qmu_bm/qmu_bm_enum.h $1/qmu_bm_enum.h
cp ./interface/modem/l1/fdd/external/ul1d_rf_common.h $1/ul1d_rf_common.h
cp ./modem/interface/general/rr2mpal_struct.h $1/rr2mpal_struct.h
cp ./interface/service/nvram/nvram_struct.h $1/nvram_struct.h
cp ./modem/interface/asn/rr/include/gprs_rlcmac_dl_struct.h $1/gprs_rlcmac_dl_struct.h
cp ./modem/common/mcd/include/mcd_struct.h $1/mcd_struct.h
cp ./interface/service/flc2/flc2_ent_functions.h $1/flc2_ent_functions.h
cp ./interface/service/stacklib/lcd_lqueue.h $1/lcd_lqueue.h
cp ./interface/service/fs/fs_type.h $1/fs_type.h
cp ./interface/service/stacklib/dlist.h $1/dlist.h
cp ./modem/interface/general/rsvas_enum.h $1/rsvas_enum.h
