/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#ifndef _IRDA_ENUMS_H
#define _IRDA_ENUMS_H

/*link error code*/
typedef enum
{
	IRDA_SUCCESS=0,
	IRDA_WRONG_CC_STATE_ERROR,
	IRDA_WRONG_SC_STATE_ERROR,
	IRDA_NO_DEVICE_ERROR,
	IRDA_LAP_CONNECT_FAIL_ERROR,				
	IRDA_LSAP_CONNECT_FAIL_ERROR,
	IRDA_LSAP_CONNECT_IN_PROGRESS_ERROR
} irda_error_code_enum;

/*class ID*/
typedef enum
{
 LPT_CLASS_ID =0,		   
 COMM_CLASS_ID,	
 OBEX_DEFAULT_ID,
 IRLAN_CLASS_ID,	
 DEV_CLASS_ID,	
 TTP2_CLASS_ID,	
 PNP_CLASS_ID    
}irda_class_id_enum;

/*attribute ID */
typedef enum
{
 OBEX_IRXFER_ATTRIBUTE_ID=0,	
 DEV_NAME_ATTRIBUTE_ID,		//OBEX_IRXFER_ATTRIBUTE_ID+1
 IRDA_SUP_ATTRIBUTE_ID,		//DEV_NAME_ATTRIBUTE_ID+1
 LMP_SEL_ATTRIBUTE_ID,		//IRDA_SUP_ATTRIBUTE_ID+1
 TTP_SEL_ATTRIBUTE_ID,		//LMP_SEL_ATTRIBUTE_ID+1
 COMM_PAR_ATTRIBUTE_ID,		//TTP_SEL_ATTRIBUTE_ID+1
 PNP_DEVICEID_ID,	         //"DeviceID"
 PNP_NAME_ID,		         //"Name"
 PNP_MANUFACTURER_ID,	   //"Manufacturer"
 PNP_CATEGORY_ID,	         //"Category"
 PNP_VERSION_ID,		      //"Version"
 PNP_STATUS_ID		         //"Status"
}irda_attribute_id_enum;

/*disconnect code*/
typedef enum
{
 DISCONNECT_REASON_USER_REQUEST=0,					     
 DISCONNECT_REASON_LAP_DISCONNECT,				     
 DISCONNECT_REASON_LAP_CONNECT_FAIL,				  
 DISCONNECT_REASON_LAP_RESET,						     
 DISCONNECT_REASON_LM_INITIATE,					     
 DISCONNECT_REASON_TTP_DISCONNECTED_LSAP,		
 DISCONNECT_REASON_NON_RESPONSIVE_LM_MUX_CLIENT,	
 DISCONNECT_REASON_NO_LM_MUX_CLIENT,				  
 DISCONNECT_REASON_CONENCTION_HALF_OPEN,			  
 DISCONNECT_REASON_ILLEGAL_SOURCE_ADDRESS,		  
 DISCONNECT_REASON_UNSPECIFIED_REASON=0xff			     
}irda_disconnect_code_enum;

typedef enum
{
 SUCCESS=0,					     
 NO_SUCH_CLASS,				     
 NO_SUCH_ATTRIBUTE
}irda_ias_return_code_enum;

/*IAS LSAP_sel*/
typedef enum
{
IAS_SERVER_LSAP_SEL=0,	 /* 0   IAS server sel */
IAS_CLIENT_LSAP_SEL,	    /* 1   IAS client sel */
LMP_LSAP_SEL,		       /* 2   LMP app sel, also IAS Client */
//RAW_COMM_LSAP_SEL,	    /* 3   RAW COMM app sel */
//LPT_LSAP_SEL,		       /* 4   LPT app sel */
TTP_LSAP_SEL,		       /* 5   TINYTP app sel */
//TTP2_LSAP_SEL,		       /* 6   TINYTP app 2 sel */
OBEX_LSAP_SEL,		       /* 7   Default OBEX app sel */
OBEX_IRXFER_LSAP_SEL,	 /* 8   OBEX irxfer app sel */
COMMX_LSAP_SEL,		    /* 9   IrCOMM 3 or 9 wire app sel */
//LAN_CONTROL_LSAP_SEL,	 /* 10  IrLAN control channel */
//LAN_DATA_LSAP_SEL,	       /* 11  IrLAN data channel */
MAX_SEL
}irda_lasp_sel_enum;

typedef enum 
{
FLC_OWNER_NULL = 0,
FLC_OWNER_OBEX ,
FLC_OWNER_IRCOMM 
}irda_flc_owner_enum;

#endif
