/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2001
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   audio_enum.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   audio common enum
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *==============================================================================
 *******************************************************************************/
#ifndef _L1AUDIO_COMMON_ENUM_H
#define _L1AUDIO_COMMON_ENUM_H

typedef enum
{
 //audio playback private function 
 AUDIO_TRACE_OPEN = 0x1000,
 AUDIO_TRACE_PLAY,
 AUDIO_TRACE_PLAY_FILE,
 AUDIO_TRACE_PLAY_STREAM,
 AUDIO_TRACE_PLAY_SUCCESS,
 AUDIO_TRACE_STOP,
 AUDIO_TRACE_STOP_FINISH,
 AUDIO_TRACE_RESUME,
 AUDIO_TRACE_PAUSE,
 AUDIO_TRACE_CLOSE,
 AUDIO_TRACE_PROCESS,
 AUDIO_TRACE_GET_DESCINFO,
 AUDIO_TRACE_HISR,
 AUDIO_TRACE_RESUME_STREAM,
 AUDIO_TRACE_ALLOC_MEM,
 AUDIO_TRACE_FREE_MEM,
 AUDIO_TRACE_SR_CH,

 //audio playback common function 
 AUDIO_TRACE_SET_START_TIME = 0x2000,
 AUDIO_TRACE_SET_STOP_TIME,
 AUDIO_TRACE_GET_CURRENT_TIME,
 AUDIO_TRACE_SET_BUFFER,
 AUDIO_TRACE_WRITE_DATA_DONE,
 AUDIO_TRACE_READ_DATA_DONE,
 AUDIO_TRACE_DATA_FINISH,
 AUDIO_TRACE_GET_SILENCE,
 AUDIO_TRACE_GET_HEADER,
 AUDIO_TRACE_REACH_VALID_REGION,
 AUDIO_TRACE_GET_SILENCE_PATTERN,
 AUDIO_TRACE_IS_FORMAT_SUPPORT,
 AUDIO_TRACE_GET_TOTAL_DUR_NONAST,
 AUDIO_TRACE_GET_TOTAL_DUR_AST,
 AUDIO_TRACE_GET_TOTAL_DUR_META,
 AUDIO_TRACE_GET_AST_DUR,
 AUDIO_TRACE_SET_AST,
 AUDIO_TRACE_BUILD_AST,
 AUDIO_TRACE_SET_LEVEL,
 AUDIO_TRACE_GET_LEVEL,
 AUDIO_TRACE_GET_RECORD_FORMAT,
 AUDIO_TRACE_FINISH_WRITE_DATA,
 AUDIO_TRACE_SET_BUFFER_INTERNAL,
 AUDIO_TRACE_FREE_BUFFER_INTERNAL,
 
 //audio info 
 AUDIO_TRACE_MHDL_EXCEPTION = 0x3000,
 AUDIO_TRACE_DATA_REQUEST,
 AUDIO_TRACE_PLAY_ERROR,
 AUDIO_TRACE_UNDERFLOW,
 AUDIO_TRACE_EOF,
 AUDIO_TRACE_MEDIAEND,
 AUDIO_TRACE_DUMMY_PLAY,

 //audio component
 AUDIO_TRACE_COMP_INIT = 0x4000,
 AUDIO_TRACE_COMP_START,
 AUDIO_TRACE_COMP_STOP,
 AUDIO_TRACE_COMP_DEINIT,
 AUDIO_TRACE_COMP_SETPARAM,
 AUDIO_TRACE_COMP_GETMEMSIZE,
 AUDIO_TRACE_COMP_PROCESS,
 AUDIO_TRACE_COMP_PROCESS_I,
 AUDIO_TRACE_COMP_OPENDEVICE,
 AUDIO_TRACE_COMP_CLOSEDEVICE,


 //audio component info
 AUDIO_TRACE_COMP_ERROR = 0x5000,
 AUDIO_TRACE_COMP_EOF,
 AUDIO_TRACE_COMP_DEC_OK,
 AUDIO_TRACE_COMP_DEC_ERR,
 AUDIO_TRACE_COMP_PAR_OK,
 AUDIO_TRACE_COMP_PAR_ERR,
 AUDIO_TRACE_COMP_UNDERFLOW,
 AUDIO_TRACE_COMP_START_TIME_OFFSET,
 AUDIO_TRACE_COMP_SEEK,
 AUDIO_TRACE_COMP_SEEK_RESUME,
 AUDIO_TRACE_COMP_FILL_SILENCE,
 AUDIO_TRACE_COMP_BS_TEMPLATE_PROCESS,
 AUDIO_TRACE_COMP_APM_IN,
 AUDIO_TRACE_COMP_APM_OUT,
 AUDIO_TRACE_COMP_PCMSINK_CHECK_THRESHOLD,

 //audio component avsync
 AUDIO_TRACE_AVSYNC_ENABLE = 0x6000,
 AUDIO_TRACE_AVSYNC_DISABLE,
 AUDIO_TRACE_AVSYNC_GET_INT_CNT,
 AUDIO_TRACE_AVSYNC_SET_TIME_STAMP,
 AUDIO_TRACE_AVSYNC_NOTIFY_MEDIA_END,
 AUDIO_TRACE_AVSYNC_EXECUTE_MEDIA_END,
 AUDIO_TRACE_AVSYNC_GET_PLAYTIME_A,
 AUDIO_TRACE_AVSYNC_GET_PLAYTIME_V,
 AUDIO_TRACE_AVSYNC_GET_TIME,

 //audio recording
 AUDIO_TRACE_MEDIA_RECORD = 0x7000,
 AUDIO_TRACE_MEDIA_STOP,
 AUDIO_TRACE_MEDIA_PAUSE,
 AUDIO_TRACE_MEDIA_RESUME,

 //Audio Drain
 AUDIO_TRACE_DRAIN_INIT = 0x8000, 
 AUDIO_TRACE_DRAIN_START, 
 AUDIO_TRACE_DRAIN_START_SUCCESS, 
 AUDIO_TRACE_DRAIN_STOP, 
 AUDIO_TRACE_DRAIN_FREE, 
 AUDIO_TRACE_ROUTE2DRAIN_INIT, 
 AUDIO_TRACE_ROUTE2DRAIN_START, 
 AUDIO_TRACE_ROUTE2DRAIN_START_SUCCESS,
 AUDIO_TRACE_ROUTE2DRAIN_STOP, 
 AUDIO_TRACE_ROUTE2DRAIN_FREE, 

 AUDIO_TRACE_DRAIN_SET_TS_HANDLE, 
 AUDIO_TRACE_DRAIN_FREE_TS_HANDLE, 
 AUDIO_TRACE_DRAIN_SET_TS_PARAM, 

 AUDIO_TRACE_DRAIN_CHECK_SR_CH, 

 //Audio Stream MPL
 AUDIO_TRACE_MPL_SET_PARAMETER = 0x9000,
 AUDIO_TRACE_MPL_FILL_THIS_BUFFER,
 AUDIO_TRACE_MPL_FLUSHQ,
 AUDIO_TRACE_MPL_ENQUEUE,
 AUDIO_TRACE_MPL_READ_DATA_DONE,
 AUDIO_TRACE_MPL_GET_READ_BUFFER,
 AUDIO_TRACE_MPL_EMPTY_BUFFER_DONE,
 AUDIO_TRACE_MPL_EMPTY_THIS_BUFFER,
 AUDIO_TRACE_MPL_TIME_STAMP_INFO,
 AUDIO_TRACE_MPL_FILL_SILENCE,
 AUDIO_TRACE_MPL_FILL_HEADER,
 AUDIO_TRACE_MPL_FILL_FRAME,
 AUDIO_TRACE_MPL_AUDIO_FILL_BUFFER,
 
 //info
 AUDIO_TRACE_PCM_STRM_FORMAT = 0x10000,
 AUDIO_TRACE_I2S_INPUT_GPIO_PIN,

 //Audio Drain
 AUDIO_TRACE_VIBR_ENABLE = 0x11000,
 AUDIO_TRACE_VIBR_FILTER_ACTIVATE,
 AUDIO_TRACE_VIBR_FILTER_DEACTIVATE,
 AUDIO_TRACE_VIBR_FILTER_SETCOEFF,
 AUDIO_TRACE_VIBR_PLAY_DUMMY,
 AUDIO_TRACE_VIBR_STOP_DUMMY,
 AUDIO_TRACE_VIBR_VIBRATION_ACTIVATE,
 AUDIO_TRACE_VIBR_VIBRATION_DEACTIVATE,
 AUDIO_TRACE_VIBR_WRITE_GAIN2DSP,
 AUDIO_TRACE_VIBR_UPDATE_GAIN,
 AUDIO_TRACE_VIBR_IS_CONFLICT,
 AUDIO_TRACE_VIBR_IS_VIBRATING,
 AUDIO_TRACE_VIBR_IS_PLAYINGDUMMY,

 //AAC MCU Decoder for FD216
 AUDIO_TRACE_AAC_DECODE = 0x12000,
 AUDIO_TRACE_AAC_WRITE2DSP,
 AUDIO_TRACE_AAC_ADIF_PARSER
}Audio_Trace_Index;


typedef enum
{
   AMR_4_75 = 0,
   AMR_5_15,
   AMR_5_90, 
   AMR_6_70, 
   AMR_7_40, 
   AMR_7_95, 
   AMR_10_20,
   AMR_12_20,
   AMR_SID,
   GSM_EFR_SID,
   TDMA_EFR_SID,
   PDC_EFR_SID,
   RESERVE_1,
   RESERVE_2,
   RESERVE_3,
   AMR_NODATA,
   AMRWB_6_60,
   AMRWB_8_85,
   AMRWB_12_65,
   AMRWB_14_25,
   AMRWB_15_85,
   AMRWB_18_25,
   AMRWB_19_85,
   AMRWB_23_05,
   AMRWB_23_85
} tSP3G_SpeechCodecType;

#if 1 //defined(__MODEM_CCCI_EXIST__) || defined(__SMART_PHONE_MODEM__)
// FIXME
typedef enum {
    SPC_ID_AUDIO_A2M_CCCI = 0, //MSG_ID_AUDIO_MSG_CODE_BEGIN,
    SPC_ID_AUDIO_M2A_CCCI,
    // SPC_ID_AUDIO_AFE_REFRESH,
    // SPC_ID_AUDIO_CTM_PROCESS,
    // SPC_ID_AUDIO_CTM_RX_DATA,
    SPC_ID_AUDIO_STRM_PCM4WAY_DATA,
    SPC_ID_AUDIO_STRM_PNW_UL_DATA_NOTIFY,
    SPC_ID_AUDIO_STRM_PNW_DL_DATA_REQUEST,
    SPC_ID_AUDIO_STRM_BGSND_DATA_REQUEST,
    SPC_ID_AUDIO_STRM_VM_DATA_REQUEST,
    // SPC_ID_AUDIO_VM_DATA_NOTIFICATION,
    SPC_ID_AUDIO_STRM_PCM_DATA_REQUEST,
    SPC_ID_SPEECH_CUSTOM_DATA_REQUEST,

	 SPC_ID_AUDIO_STRM_PCMREC_DATA_NOTIFY,
	 SPC_ID_AUDIO_STRM_VMREC_DATA_NOTIFY,
	 SPC_ID_AUDIO_STRM_CTM_DUMP_DATA_NOTIFY,

	 SPC_ID_AUDIO_STRM_DACA_DL_DATA_NOTIFY, 
	 SPC_ID_AUDIO_STRM_DACA_UL_DATA_REQUEST,
	 
	 SPC_ID_AUDIO_CONTROL_BGSND_CLOSE,
	 SPC_ID_NETWORK_STATUS_NOTIFY,

    SPC_ID_AUDIO_STRM_RAWPCMREC_DATA_NOTIFY,

    SPC_ID_AUDIO_MAX
} SPC_MSG_ID_T; 

typedef enum {
    MSG_TYPE_VOLUME_CTRL = 0, 
    MSG_TYPE_SET_DEVICE,
    MSG_TYPE_SPEECH_CTRL,
    MSG_TYPE_DATA_TRANSFER_CTRL,
    MSG_TYPE_OTHER_API_HANDLER,
    MSG_TYPE_NOTIFICATION,
    MSG_TYPE_ACK_FROM_AP,
    MSG_TYPE_MISC_CTRL,
    MSG_TYPE_CHANGE_DEV,
    MSG_TYPE_MAX
} AUD_CCCI_MSG_TYPE_T;

#define CCCIMSG_A2M_BASE 0x2F00
#define CCCIMSG_M2A_BASE 0xAF00

typedef enum {
	MSG_VOL_CTRL_OUTPUT_VOL = 0, 
	MSG_VOL_MICROPHONE_VOL,
	MSG_VOL_MUTE_MICROPHONE,
	MSG_VOL_SIDETONE_VOL,
	MSG_VOL_GAINTABLE_OUTPUT_VOL,
	MSG_VOL_GAINTABLE_MICROPHONE_VOL,
	MSG_VOL_MUTE_SPEAKER,

	MSG_DEV_OUTPUT_DEV = 0x10, 
	MSG_DEV_INPUT_DEV,
	MSG_DEV_MIC_BIAS,
	MSG_DEV_VCM, //un used 
	MSG_DEV_REFMIC,

    MSG_SPH_CTRL_SPH_ON = 0x20, 
    MSG_SPH_CTRL_SPH_OFF,
    MSG_SPH_CTRL_SET_DAI_MODE, // un used in MT6280
    MSG_SPH_CTRL_SET_AFE_LOOPBACK,
	MSG_SPH_CTRL_SET_SPH_MODE = 0x24,
    MSG_SPH_CTRL_SET_RECEVER_TEST,
	MSG_SPH_CTRL_SET_ENH_INDIVIDUAL = 0x26,
    MSG_SPH_CTRL_SET_ENH,
    MSG_SPH_CTRL_SET_ACOUSTIC_LOOPBACK,
    MSG_SPH_CTRL_GET_MD_CAPABILITY,
    MSG_SPH_CTRL_SET_MD_CAPABILITY,
	MSG_SPH_CTRL_ENH_LOG_PRINT,
	
	// [REMIND]
	MSG_A2M_EXTEND_BASE = 0x2F, // message with 0x2f begin are new version handler. 

    MSG_DATA_TRANSFER_PCM_ON = 0x30, 
    MSG_DATA_TRANSFER_PCM_OFF, 
    MSG_DATA_TRANSFER_PLAYBACK_ON, 
    MSG_DATA_TRANSFER_PLAYBACK_OFF, 
	MSG_DATA_TRANSFER_RECORD_ON = 0x34, 
    MSG_DATA_TRANSFER_RECORD_OFF, 
    MSG_DATA_TRANSFER_DMRN_RECPLAY_ON,
    MSG_DATA_TRANSFER_DMRN_RECPLAY_OFF,
    MSG_DATA_TRANSFER_DMRN_REC_ONLY_ON,
    MSG_DATA_TRANSFER_DMRN_REC_ONLY_OFF,

    MSG_AP_CTM_ON = 0x40, 
    MSG_AP_CTM_OFF, 
    MSG_AP_START_NEGOTIATION, 
    MSG_AP_BGSND_ON, 
    MSG_AP_BGSND_OFF, 
    MSG_AP_BGSND_CONFIG, 

	MSG_DATA_NOTIFY_PNW_DLDATA = 0x50, // DL
    MSG_DATA_NOTIFY_PLAYBACK_NOTIFY = 0x54, 
    MSG_DATA_NOTIFY_BGS_NOTIFY = 0x58, 
    MSG_DATA_NOTIFY_CTM_NOTIFY = 0x5C,
    
	MSG_DATA_NOTIFY_PNW_ULREAD_ACK = 0x60, 
	MSG_DATA_NOTIFY_REC_READ_ACK = 0x64,

	MSG_MISC_UNUSED = 0x70,
	MSG_MISC_EM_INCALL = 0x74,
	MSG_MISC_EM_DMNR = 0x78,
	MSG_MISC_EM_WB = 0x7C,

	MSG_M2A_DATA_REQUEST_PNW_DLDATA = 0x80, //mapping to 0x50
	MSG_M2A_DATA_REQUEST_BGSND_DATA = 0x82,
	MSG_M2A_DATA_REQUEST_EM_DATA = 0x84, 
	
	MSG_M2A_DATA_NOTIFY_PNW_ULREAD = 0x90, //mapping to 0x60
	MSG_M2A_DATA_NOTIFY_REC_DATA = 0x94, 
	
	MSG_M2A_SPH_CTRL_SPH_ON_ACK = 0xA0,
	MSG_M2A_SPH_CTRL_SPH_OFF_ACK, 
	MSG_M2A_SPH_CTRL_SET_SPH_MODE_ACK = 0xA4,
	MSG_M2A_SPH_CTRL_SET_ACOUSTIC_LOOPBACK_ACK = 0xA8,
	MSG_M2A_SPH_CTRL_GET_MD_CAPABILITY_ACK, 
	MSG_M2A_SPH_CTRL_SET_MD_CAPABILITY_ACK, 
	
	// [REMIND]
	MSG_M2A_EXTEND_BASE = 0xAF, // message with 0xAF begin are new version handler and message
	
	MSG_M2A_DATA_TRANSFER_PCM_ON_ACK = 0xB0, // mapping to 0x30
	MSG_M2A_DATA_TRANSFER_PCM_OFF_ACK,
	MSG_M2A_DATA_TRANSFER_RECORD_ON_ACK = 0xB4,
	MSG_M2A_DATA_TRANSFER_RECORD_OFF_ACK,	
	MSG_M2A_DATA_TRANSFER_DMRN_RECPLAY_ON_ACK,
	MSG_M2A_DATA_TRANSFER_DMRN_RECPLAY_OFF_ACK,
	MSG_M2A_DATA_TRANSFER_DMRN_REC_ONLY_ON_ACK,
	MSG_M2A_DATA_TRANSFER_DMRN_REC_ONLY_OFF_ACK,

	MSG_M2A_AP_CTM_ON_ACK = 0xC0, 
	MSG_M2A_AP_CTM_OFF_ACK, 
	MSG_M2A_AP_START_NEGOTIATION_ACK, // usedless
	MSG_M2A_AP_BGSND_ON_ACK, 
	MSG_M2A_AP_BGSND_OFF_ACK, 
	MSG_M2A_AP_BGSND_CONFIG_ACK, //useless

	MSG_M2A_MISC_UNUSED = 0xF0,
	MSG_M2A_MISC_EM_INCALL = 0xF4,
	MSG_M2A_MISC_EM_DMNR = 0xF8,
	MSG_M2A_MISC_EM_WB = 0xFC,


// ======================== NEW VERSION ===========================

	//------------------ A2M -----------------------
	MSG_A2M_SPH_DL_DIGIT_VOLUME = CCCIMSG_A2M_BASE,
	MSG_A2M_SPH_UL_DIGIT_VOLUME,
	MSG_A2M_MUTE_SPH_UL,
	MSG_A2M_MUTE_SPH_DL,
	MSG_A2M_SIDETONE_VOLUME,
	MSG_A2M_SPH_DL_ENH_REF_DIGIT_VOLUME, 
	MSG_A2M_SIDETONE_CONFIG,
	MSG_A2M_MUTE_SPH_UL_ENH_RESULT,	
	MSG_A2M_MUTE_SPH_UL_SOURCE,
	
	MSG_A2M_SET_SAMPLE_RATE = CCCIMSG_A2M_BASE + 0x10,
	MSG_A2M_SET_DUAL_MIC,
	
	MSG_A2M_SPH_ON = CCCIMSG_A2M_BASE + 0x20,
	MSG_A2M_SPH_OFF,
	MSG_A2M_SET_SPH_MODE,
	MSG_A2M_CTRL_SPH_ENH,
	MSG_A2M_CONFIG_SPH_ENH,
	MSG_A2M_SET_ACOUSTIC_LOOPBACK,
	MSG_A2M_PRINT_SPH_COEFF,		
	MSG_A2M_SPH_ON_FOR_HOLD_CALL, // [Special] speech on with mute, for call hold use, no any other application can be turn on
	MSG_A2M_SPH_ON_FOR_DACA,	
	MSG_A2M_SPH_ROUTER_ON, // PCM wrouter on for enhancement and other application path. 
	
	
	MSG_A2M_PNW_ON = CCCIMSG_A2M_BASE + 0x30,
	MSG_A2M_PNW_OFF,
	MSG_A2M_RECORD_ON,
	MSG_A2M_RECORD_OFF,
	MSG_A2M_DMNR_RECPLAY_ON, // not use in MT6582
	MSG_A2M_DMNR_RECPLAY_OFF, // not use in MT6582
	MSG_A2M_DMNR_REC_ONLY_ON, // not use in MT6582
	MSG_A2M_DMNR_REC_ONLY_OFF, // not use in MT6582
	MSG_A2M_PCM_REC_ON,
	MSG_A2M_PCM_REC_OFF,
	MSG_A2M_VM_REC_ON,
	MSG_A2M_VM_REC_OFF,
	MSG_A2M_RECORD_RAW_PCM_ON,  //CCCIMSG_A2M_BASE + 0x30 + 0xC
	MSG_A2M_RECORD_RAW_PCM_OFF, //CCCIMSG_A2M_BASE + 0x30 + 0xD
	
	
	MSG_A2M_CTM_ON = CCCIMSG_A2M_BASE + 0x40,
	MSG_A2M_CTM_OFF,	
	MSG_A2M_CTM_DUMP_DEBUG_FILE,
	MSG_A2M_BGSND_ON,
	MSG_A2M_BGSND_OFF,
	MSG_A2M_BGSND_CONFIG,
	
	MSG_A2M_PNW_DLDATA_NOTIFY = CCCIMSG_A2M_BASE + 0x50,
	MSG_A2M_BGSND_DATA_NOTIFY,
	MSG_A2M_CTM_DATA_NOTIFY,	
	MSG_A2M_DACA_UL_DATA_NOTIFY,

	MSG_A2M_PNW_ULDATA_READ_ACK = CCCIMSG_A2M_BASE + 0x60,
	MSG_A2M_REC_DATA_READ_ACK,
	MSG_A2M_CTM_DEBUG_DATA_READ_ACK,
	MSG_A2M_PCM_REC_DATA_READ_ACK,
	MSG_A2M_VM_REC_DATA_READ_ACK,
	MSG_A2M_DACA_DL_DATA_READ_ACK,
	MSG_A2M_RAW_PCM_REC_DATA_READ_ACK, //CCCIMSG_A2M_BASE + 0x60 +0x6
	

	MSG_A2M_EM_DATA_REQUEST_ACK = CCCIMSG_A2M_BASE + 0x70,
	MSG_A2M_EM_INCALL,
	MSG_A2M_EM_DMNR,
	MSG_A2M_EM_WB,
	MSG_A2M_EM_MAGICON,
	MSG_A2M_NETWORK_STATUS_ACK,	
	MSG_A2M_QUERY_RF_INFO,
	MSG_A2M_EM_HAC,
	
	MSG_A2M_VIBSPK_PARAMETER = CCCIMSG_A2M_BASE + 0x80,
	MSG_A2M_NXP_SMARTPA_PARAMETER, 
	
	//------------------- M2A ----------------------
	MSG_M2A_SPH_DL_DIGIT_VOLUME_ACK = CCCIMSG_M2A_BASE,
	MSG_M2A_SPH_UL_DIGIT_VOLUME_ACK,
	MSG_M2A_MUTE_SPH_UL_ACK,
	MSG_M2A_MUTE_SPH_DL_ACK,
	MSG_M2A_SIDETONE_VOLUME_ACK,
	MSG_M2A_SPH_DL_ENH_REF_DIGIT_VOLUME_ACK,
	MSG_M2A_SIDETONE_CONFIG_ACK,
	MSG_M2A_MUTE_SPH_UL_ENH_RESULT_ACK,
	MSG_M2A_MUTE_SPH_UL_SOURCE_ACK,
	
	MSG_M2A_SET_SAMPLE_RATE_ACK = CCCIMSG_M2A_BASE + 0x10,
	MSG_M2A_SET_DUAL_MIC_ACK,
	
	MSG_M2A_SPH_ON_ACK = CCCIMSG_M2A_BASE + 0x20,
	MSG_M2A_SPH_OFF_ACK,
	MSG_M2A_SET_SPH_MODE_ACK,
	MSG_M2A_CTRL_SPH_ENH_ACK,
	MSG_M2A_CONFIG_SPH_ENH_ACK,
	MSG_M2A_SET_ACOUSTIC_LOOPBACK_ACK,
	MSG_M2A_PRINT_SPH_COEFF_ACK,
	MSG_M2A_SPH_ON_FOR_HOLD_CALL_ACK, 
	MSG_M2A_SPH_ON_FOR_DACA_ACK,
	MSG_M2A_SPH_ROUTER_ON_ACK,
	
	
	MSG_M2A_PNW_ON_ACK = CCCIMSG_M2A_BASE + 0x30,
	MSG_M2A_PNW_OFF_ACK,
	MSG_M2A_RECORD_ON_ACK,
	MSG_M2A_RECORD_OFF_ACK,
	MSG_M2A_DMNR_RECPLAY_ON_ACK, // not use in MT6582
	MSG_M2A_DMNR_RECPLAY_OFF_ACK, // not use in MT6582
	MSG_M2A_DMNR_REC_ONLY_ON_ACK, // not use in MT6582
	MSG_M2A_DMNR_REC_ONLY_OFF_ACK, // not use in MT6582
	MSG_M2A_PCM_REC_ON_ACK,
	MSG_M2A_PCM_REC_OFF_ACK,
	MSG_M2A_VM_REC_ON_ACK,
	MSG_M2A_VM_REC_OFF_ACK,
	MSG_M2A_RECORD_RAW_PCM_ON_ACK,  //CCCIMSG_M2A_BASE + 0x30 + 0xC
	MSG_M2A_RECORD_RAW_PCM_OFF_ACK, //CCCIMSG_M2A_BASE + 0x30 + 0xD
	
	
	MSG_M2A_CTM_ON_ACK = CCCIMSG_M2A_BASE + 0x40,
	MSG_M2A_CTM_OFF_ACK,
	MSG_M2A_CTM_DUMP_DEBUG_FILE_ACK,
	MSG_M2A_BGSND_ON_ACK,
	MSG_M2A_BGSND_OFF_ACK,
	MSG_M2A_BGSND_CONFIG_ACK,
	
	MSG_M2A_PNW_DL_DATA_REQUEST = CCCIMSG_M2A_BASE + 0x50,
	MSG_M2A_BGSND_DATA_REQUEST,
	MSG_M2A_CTM_DATA_REQUEST,	
	MSG_M2A_DACA_UL_DATA_REQUEST, 
	
	MSG_M2A_PNW_UL_DATA_NOTIFY = CCCIMSG_M2A_BASE + 0x60,
	MSG_M2A_REC_DATA_NOTIFY,
	MSG_M2A_CTM_DEBUG_DATA_NOTIFY,
	MSG_M2A_PCM_REC_DATA_NOTIFY,
	MSG_M2A_VM_REC_DATA_NOTIFY,	
	MSG_A2M_DACA_DL_DATA_NOTIFY, 
	MSG_M2A_RAW_PCM_REC_DATA_NOTIFY, //CCCIMSG_M2A_BASE + 0x60 + 0x6

	MSG_M2A_EM_DATA_REQUEST = CCCIMSG_M2A_BASE + 0x70,
	MSG_M2A_EM_INCALL_ACK,
	MSG_M2A_EM_DMNR_ACK,
	MSG_M2A_EM_WB_ACK,
	MSG_M2A_EM_MAGICON_ACK,
	MSG_M2A_NETWORK_STATUS_NOTIFY,	
	MSG_M2A_RF_INFO_NOTIFY,	
	MSG_M2A_EM_HAC_ACK,

	MSG_M2A_VIBSPK_PARAMETER_ACK = CCCIMSG_M2A_BASE + 0x80,
	MSG_M2A_NXP_SMARTPA_PARAMETER_ACK,
	
} AUD_CCCI_MSG_T;

typedef enum
{
    AUD_CCCI_STRMBUF_TYPE_PCM_FillSE = 0,
    AUD_CCCI_STRMBUF_TYPE_PCM_FillSpk,
    AUD_CCCI_STRMBUF_TYPE_PCM_GetFromMic,
    AUD_CCCI_STRMBUF_TYPE_PCM_GetfromSD,
    AUD_CCCI_STRMBUF_TYPE_VM_TYPE,
    AUD_CCCI_STRMBUF_TYPE_PCM_TYPE,
    AUD_CCCI_STRMBUF_TYPE_BGS_TYPE,
    AUD_CCCI_STRMBUF_TYPE_EM_PARAM, //  7
    // AUD_CCCI_STRMBUF_TYPE_HD_RECORD_PARAM = 0x17,     

	 AUD_CCCI_STRMBUF_TYPE_CTM_UL_IN, // 8
    AUD_CCCI_STRMBUF_TYPE_CTM_DL_IN,
    AUD_CCCI_STRMBUF_TYPE_CTM_UL_OUT,
    AUD_CCCI_STRMBUF_TYPE_CTM_DL_OUT,
    AUD_CCCI_STRMBUF_TYPE_VIBSPK_PARAM, // 12, for viberation speaker 
    
	 AUD_CCCI_STRMBUF_TYPE_DACA_GetSpk, // 13
	 AUD_CCCI_STRMBUF_TYPE_DACA_FillMic,
    AUD_CCCI_STRMBUF_TYPE_NXP_SMARTPA_PARAM, // 15

	 AUD_CCCI_STRMBUF_TYPE_MAGI_CONFERENCE_PARAM, // 16
    AUD_CCCI_STRMBUF_TYPE_HAC_PARAM, 
    AUD_CCCI_STRMBUF_TYPE_RAW_PCM_TYPE, //18
    
    AUD_CCCI_STRMBUF_TYPE_MAX_TYPE=19
    
}AUD_CCCI_STRMBUF_TYPE_T;


#endif

#if defined(__DSP_FCORE4__)
#define MDCIMSG_L1AUDIO2FAS_SPEECH_BASE 0x1000
#define MDCIMSG_L1AUDIO2FAS_AUDIO_BASE  0x2000
#define MDCIMSG_L1D2FAS_COSIM_BASE      0x3000
#define MDCIMSG_L1AUDIO2FAS_HW_BASE     0x5000

typedef enum {
   // Speech Configuration
   MSG_L1AUDIO2FAS_QUERY_DSP_VERSION = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE,
   MSG_L1AUDIO2FAS_SET_M2D_MEM,
   MSG_L1AUDIO2FAS_SPEECH_GET_ID,
   MSG_L1AUDIO2FAS_SPEECH_FREE_ID,
    
   MSG_L1AUDIO2FAS_SPEECH_CONFIG = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x10,
   MSG_L1AUDIO2FAS_SPEECH_SET_MODE,
   MSG_L1AUDIO2FAS_SPEECH_ENHANCEMENT_SET_PAR,
   MSG_L1AUDIO2FAS_SPEECH_BT_CONFIG,
   MSG_L1AUDIO2FAS_SPEECH_ENABLE_SIDETONE,
   MSG_L1AUDIO2FAS_SPEECH_DISABLE_SIDETONE,
   MSG_L1AUDIO2FAS_SPEECH_SET_SIDETONE,
   MSG_L1AUDIO2FAS_SPEECH_SET_AGC,
   MSG_L1AUDIO2FAS_SPEECH_SET_UL_IIR,
   MSG_L1AUDIO2FAS_SPEECH_DMNR_SET_PAR,
   MSG_L1AUDIO2FAS_SPEECH_ENHANCEMENT_SET_SUB_FEATURE,
   
   MSG_L1AUDIO2FAS_SPEECH_2G_CALL_ON = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x20,
   MSG_L1AUDIO2FAS_SPEECH_2G_CALL_OFF,
   
   MSG_L1AUDIO2FAS_SPEECH_3G_CALL_ON = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x30,
   MSG_L1AUDIO2FAS_SPEECH_3G_CALL_OFF,
   MSG_L1AUDIO2FAS_SPEECH_3G_REQUEST_READ_UL_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_3G_REQUEST_WRITE_DL_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_HANDOVER,
   
   MSG_L1AUDIO2FAS_SPEECH_CALLPCM2WAY_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x40,
   MSG_L1AUDIO2FAS_SPEECH_CALLPCM2WAY_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_IDLEPCM2WAY_START,
   MSG_L1AUDIO2FAS_SPEECH_IDLEPCM2WAY_STOP,
   MSG_L1AUDIO2FAS_SPEECH_PCM2WAY_REQUEST_EXCHANGE_UL_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_PCM2WAY_REQUEST_EXCHANGE_DL_DATA_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_CALLPCM4WAY_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x50,
   MSG_L1AUDIO2FAS_SPEECH_CALLPCM4WAY_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_IDLEPCM4WAY_START,
   MSG_L1AUDIO2FAS_SPEECH_IDLEPCM4WAY_STOP,
   MSG_L1AUDIO2FAS_SPEECH_PCM4WAY_REQUEST_EXCHANGE_UL_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_PCM4WAY_REQUEST_EXCHANGE_DL_DATA_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_BT_CORDLESS_ON = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x60,
   MSG_L1AUDIO2FAS_SPEECH_BT_CORDLESS_OFF,
   
   MSG_L1AUDIO2FAS_SPEECH_ACOUSTIC_TEST_START = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x70,
   MSG_L1AUDIO2FAS_SPEECH_ACOUSTIC_TEST_STOP,
   MSG_L1AUDIO2FAS_SPEECH_ECHO_LOOP_TEST_START,
   MSG_L1AUDIO2FAS_SPEECH_ECHO_LOOP_TEST_STOP,
   
   MSG_L1AUDIO2FAS_SPEECH_BKG_SOUND_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x80,
   MSG_L1AUDIO2FAS_SPEECH_BKG_SOUND_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_BKG_REQUEST_WRITE_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_TONE_EFFECT_OPEN,
   MSG_L1AUDIO2FAS_SPEECH_TONE_EFFECT_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_BKG_SOUND_SET_DLGAIN,
   MSG_L1AUDIO2FAS_SPEECH_BKG_SOUND_SET_ULGAIN,
   
   MSG_L1AUDIO2FAS_SPEECH_DAI_ASSERTION = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x90,
   MSG_L1AUDIO2FAS_SPEECH_DAI_NEGATION,
   
   MSG_L1AUDIO2FAS_SPEECH_ENABLE_DTX = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xa0,
   MSG_L1AUDIO2FAS_SPEECH_DISABLE_DTX,
   MSG_L1AUDIO2FAS_SPEECH_UPDATE_UL_CODEC_RATE,
   MSG_L1AUDIO2FAS_SPEECH_UPDATE_DL_CODEC_RATE,
   MSG_L1AUDIO2FAS_SPEECH_SET_BFI,
   MSG_L1AUDIO2FAS_SPEECH_DL_GAIN,
   MSG_L1AUDIO2FAS_SPEECH_UL_GAIN,
   
   MSG_L1AUDIO2FAS_SPEECH_SET_UL_VOLUME = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xb0,
   MSG_L1AUDIO2FAS_SPEECH_SET_DL_VOLUME,
   MSG_L1AUDIO2FAS_SPEECH_MUTE,
   MSG_L1AUDIO2FAS_SPEECH_UNMUTE,
   MSG_L1AUDIO2FAS_SPEECH_SET_UL_DEVICE,
   MSG_L1AUDIO2FAS_SPEECH_SET_DL_DEVICE,
   MSG_L1AUDIO2FAS_SPEECH_MUTE_UPLINK_BY_FRAME,
   
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_PCM_START = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xc0,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_PCM_STOP,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_VM_START,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_VM_STOP,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_COD_START,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_COD_STOP,
   
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_PCM_START = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xd0,
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_PCM_STOP,
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_VM_START,
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_VM_STOP,
   
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_PCM_REQUEST_READ_DATA_ACK = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xe0,
   MSG_L1AUDIO2FAS_SPEECH_CALL_RECORD_VM_REQUEST_READ_DATA_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_PCM_REQUEST_READ_DATA_ACK= MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0xf0,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_VM_REQUEST_READ_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_RECORD_COD_REQUEST_READ_DATA_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_IDLE_PLAY_START = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x100,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_PLAY_STOP,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_PLAY_REQUEST_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_IDLE_PLAY_VM_FAIL_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_FWLA_START = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x110,
   MSG_L1AUDIO2FAS_SPEECH_FWLA_STOP,
   MSG_L1AUDIO2FAS_SPEECH_FWLA_UPDATA_PAR,
   
   MSG_L1AUDIO2FAS_SPEECH_MLBK_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x120,
   MSG_L1AUDIO2FAS_SPEECH_MLBK_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_MLBK_RESULT_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_SLBK_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x130,
   MSG_L1AUDIO2FAS_SPEECH_SLBK_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_CODEC_LBK_OPEN,
   MSG_L1AUDIO2FAS_SPEECH_CODEC_LBK_CLOSE,
   
   MSG_L1AUDIO2FAS_SPEECH_SPUT_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x140,
   MSG_L1AUDIO2FAS_SPEECH_SPUT_CLOSE,  
   MSG_L1AUDIO2FAS_SPEECH_SPUT_REQUEST_DATA_ACK,
   
   MSG_L1AUDIO2FAS_SPEECH_CTM_NOTIFY_ON = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x150,
   MSG_L1AUDIO2FAS_SPEECH_CTM_NOTIFY_OFF,
   MSG_L1AUDIO2FAS_SPEECH_CTM_CONFIG,
   
   MSG_L1AUDIO2FAS_SPEECH_GET_TIME_ON = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x160,
   MSG_L1AUDIO2FAS_SPEECH_GET_TIME_OFF,
   
   MSG_L1AUDIO2FAS_SPEECH_DATACARD_OPEN = MDCIMSG_L1AUDIO2FAS_SPEECH_BASE + 0x170,
   MSG_L1AUDIO2FAS_SPEECH_DATACARD_CLOSE,
   MSG_L1AUDIO2FAS_SPEECH_DATACARD_REQUEST_EXCHANGE_UL_DATA_ACK,
   MSG_L1AUDIO2FAS_SPEECH_DATACARD_REQUEST_EXCHANGE_DL_DATA_ACK,
   
   /*===========================================================*/
   // Flow Control
   MSG_L1AUDIO2FAS_AUDIO_GET_ID = MDCIMSG_L1AUDIO2FAS_AUDIO_BASE,
   MSG_L1AUDIO2FAS_AUDIO_FREE_ID,
   MSG_L1AUDIO2FAS_AUDIO_PLAYBACK_ON,
   MSG_L1AUDIO2FAS_AUDIO_PLAYBACK_OFF,
   MSG_L1AUDIO2FAS_AUDIO_RECORD_ON,
   MSG_L1AUDIO2FAS_AUDIO_RECORD_OFF,
   MSG_L1AUDIO2FAS_AUDIO_TONE_PLAYBACK_ON,
   MSG_L1AUDIO2FAS_AUDIO_SET_PLAY_RATE,

   // Data transmission
   MSG_L1AUDIO2FAS_AUDIO_WRITE_DATA,
   MSG_L1AUDIO2FAS_AUDIO_DATA_REQUEST_ACK,
   MSG_L1AUDIO2FAS_AUDIO_DATA_NOTIFICATION_ACK,
   MSG_L1AUDIO2FAS_AUDIO_SECURITY,

   // Path and volume
   MSG_L1AUDIO2FAS_AUDIO_SET_OUTPUT_DEVICE,
   MSG_L1AUDIO2FAS_AUDIO_SET_OUTPUT_VOLUME,
   MSG_L1AUDIO2FAS_AUDIO_SET_INPUT_DEVICE,
   MSG_L1AUDIO2FAS_AUDIO_SET_INPUT_VOLUME,
   MSG_L1AUDIO2FAS_AUDIO_SET_STEREO2MONO,
   MSG_L1AUDIO2FAS_AUDIO_SET_TONE_VOLUME, 
   MSG_L1AUDIO2FAS_AUDIO_AVSYNC_INITIALIZE,
   MSG_L1AUDIO2FAS_AUDIO_AVSYNC_SET_INTERVAL,
   MSG_L1AUDIO2FAS_AUDIO_AVSYNC_NOTIFY_ACK,
   
   /*===================MDCIMSG_L1D2FAS_COSIM_BASE==============*/
   MDCIMSG_L1D2FAS_COSIM_IRQ_TEST = MDCIMSG_L1D2FAS_COSIM_BASE,
   MDCIMSG_L1D2FAS_COSIM_MEMIF_TEST,
   MDCIMSG_L1D2FAS_COSIM_DLSRC_TEST,
   MDCIMSG_L1D2FAS_COSIM_ULSRC_TEST,
   
   /*===================MDCIMSG_L1AUDIO2FAS_HW_BASE=============*/
   MSG_L1AUDIO2FAS_HW_BLUETOOTH_SYNC_TYPE = MDCIMSG_L1AUDIO2FAS_HW_BASE,
   MSG_L1AUDIO2FAS_HW_BLUETOOTH_FRAME_SYNC_LENGTH,
   MSG_L1AUDIO2FAS_HW_BLUETOOTH_WORD_SELECTION,
   MSG_L1AUDIO2FAS_HW_BLUETOOTH_DATA_RATE_MODE,

   MSG_L1AUDIO2FAS_HW_DIGITAL_MIC_CLOCK_PHASE_CH1 = MDCIMSG_L1AUDIO2FAS_HW_BASE + 0x10,
   MSG_L1AUDIO2FAS_HW_DIGITAL_MIC_CLOCK_PHASE_CH2,
   MSG_L1AUDIO2FAS_HW_DIGITAL_MIC_INPUT_SAMPLING_RATE, 

   MSG_L1AUDIO2FAS_HW_I2S_IN_CLOCK_MODE = MDCIMSG_L1AUDIO2FAS_HW_BASE + 0x20,
   
   MSG_L1AUDIO2FAS_HW_DAC_LBUF_RATIO = MDCIMSG_L1AUDIO2FAS_HW_BASE + 0x30,
   MSG_L1AUDIO2FAS_HW_DAC_RBUF_RATIO,
   MSG_L1AUDIO2FAS_HW_DAC_MONO_RATIO,

} L1AUDIO2FAS_AUDIO_MSG;

#define MDCIMSG_SAC2L1AUDIO_SPEECH_BASE 0x9000
#define MDCIMSG_SAC2L1AUDIO_AUDIO_BASE  0xA000
#define MDCIMSG_FAS2L1D_COSIM_BASE      0xB000
#define MDCIMSG_SAC2L1AUDIO_HW_BASE     0xD000

typedef enum {
   // Speech Configuration
   MSG_SAC2L1AUDIO_QUERY_DSP_VERSION_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE,
   MSG_SAC2L1AUDIO_SET_M2D_MEM_ACK,
   MSG_SAC2L1AUDIO_SPEECH_GET_ID_ACK,
   MSG_SAC2L1AUDIO_SPEECH_FREE_ID_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_CONFIG_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x10,
   MSG_SAC2L1AUDIO_SPEECH_SET_MODE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_ENHANCEMENT_SET_PAR_ACK,
   MSG_SAC2L1AUDIO_SPEECH_BT_CONFIG_ACK,
   MSG_SAC2L1AUDIO_SPEECH_ENABLE_SIDETONE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_DISABLE_SIDETONE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_SIDETONE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_AGC_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_UL_IIR_ACK,
   MSG_SAC2L1AUDIO_SPEECH_DMNR_SET_PAR_ACK,
   MSG_SAC2L1AUDIO_SPEECH_ENHANCEMENT_SET_SUB_FEATURE_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_2G_CALL_ON_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x20,
   MSG_SAC2L1AUDIO_SPEECH_2G_CALL_OFF_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_3G_CALL_ON_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x30,
   MSG_SAC2L1AUDIO_SPEECH_3G_CALL_OFF_ACK,
   MSG_SAC2L1AUDIO_SPEECH_3G_REQUEST_READ_UL_DATA,
   MSG_SAC2L1AUDIO_SPEECH_3G_REQUEST_WRITE_DL_DATA,
   MSG_SAC2L1AUDIO_SPEECH_HANDOVER_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_CALLPCM2WAY_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x40,
   MSG_SAC2L1AUDIO_SPEECH_CALLPCM2WAY_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLEPCM2WAY_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLEPCM2WAY_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_PCM2WAY_REQUEST_EXCHANGE_UL_DATA,
   MSG_SAC2L1AUDIO_SPEECH_PCM2WAY_REQUEST_EXCHANGE_DL_DATA,
   
   MSG_SAC2L1AUDIO_SPEECH_CALLPCM4WAY_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x50,
   MSG_SAC2L1AUDIO_SPEECH_CALLPCM4WAY_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLEPCM4WAY_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLEPCM4WAY_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_PCM4WAY_REQUEST_EXCHANGE_UL_DATA,
   MSG_SAC2L1AUDIO_SPEECH_PCM4WAY_REQUEST_EXCHANGE_DL_DATA,
   
   MSG_SAC2L1AUDIO_SPEECH_BT_CORDLESS_ON_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x60,
   MSG_SAC2L1AUDIO_SPEECH_BT_CORDLESS_OFF_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_ACOUSTIC_TEST_START_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x70,
   MSG_SAC2L1AUDIO_SPEECH_ACOUSTIC_TEST_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_ECHO_LOOP_TEST_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_ECHO_LOOP_TEST_STOP_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_BKG_SOUND_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x80,
   MSG_SAC2L1AUDIO_SPEECH_BKG_SOUND_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_BKG_REQUEST_WRITE_DATA,
   MSG_SAC2L1AUDIO_SPEECH_TONE_EFFECT_OPEN_ACK,
   MSG_SAC2L1AUDIO_SPEECH_TONE_EFFECT_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_BKG_SOUND_SET_DLGAIN_ACK,
   MSG_SAC2L1AUDIO_SPEECH_BKG_SOUND_SET_ULGAIN_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_DAI_ASSERTION_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x90,
   MSG_SAC2L1AUDIO_SPEECH_DAI_NEGATION_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_ENABLE_DTX_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xa0,
   MSG_SAC2L1AUDIO_SPEECH_DISABLE_DTX_ACK,
   MSG_SAC2L1AUDIO_SPEECH_UPDATE_UL_CODEC_RATE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_UPDATE_DL_CODEC_RATE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_BFI_ACK,
   MSG_SAC2L1AUDIO_SPEECH_DL_GAIN_ACK,
   MSG_SAC2L1AUDIO_SPEECH_UL_GAIN_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_SET_UL_VOLUME_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xb0,
   MSG_SAC2L1AUDIO_SPEECH_SET_DL_VOLUME_ACK,
   MSG_SAC2L1AUDIO_SPEECH_MUTE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_UNMUTE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_UL_DEVICE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SET_DL_DEVICE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_MUTE_UPLINK_BY_FRAME_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_PCM_START_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xc0,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_PCM_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_VM_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_VM_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_COD_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_COD_STOP_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_PCM_START_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xd0,
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_PCM_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_VM_START_ACK,
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_VM_STOP_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_PCM_REQUEST_READ_DATA = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xe0,
   MSG_SAC2L1AUDIO_SPEECH_CALL_RECORD_VM_REQUEST_READ_DATA,
   
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_PCM_REQUEST_READ_DATA = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0xf0,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_VM_REQUEST_READ_DATA,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_RECORD_COD_REQUEST_READ_DATA,
   
   MSG_SAC2L1AUDIO_SPEECH_IDLE_PLAY_START_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x100,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_PLAY_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_PLAY_REQUEST_WRITE_DATA,
   MSG_SAC2L1AUDIO_SPEECH_IDLE_PLAY_VM_FAIL,
   
   MSG_SAC2L1AUDIO_SPEECH_FWLA_START_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x110,
   MSG_SAC2L1AUDIO_SPEECH_FWLA_STOP_ACK,
   MSG_SAC2L1AUDIO_SPEECH_FWLA_UPDATA_PAR_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_MLBK_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x120,
   MSG_SAC2L1AUDIO_SPEECH_MLBK_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_MLBK_RESULT,
   
   MSG_SAC2L1AUDIO_SPEECH_SLBK_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x130,
   MSG_SAC2L1AUDIO_SPEECH_SLBK_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_CODEC_LBK_OPEN_ACK,
   MSG_SAC2L1AUDIO_SPEECH_CODEC_LBK_CLOSE_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_SPUT_OPEN_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x140,
   MSG_SAC2L1AUDIO_SPEECH_SPUT_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_SPUT_REQUEST_DATA, 
   
   MSG_SAC2L1AUDIO_SPEECH_CTM_NOTIFY_ON_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x150,
   MSG_SAC2L1AUDIO_SPEECH_CTM_NOTIFY_OFF_ACK,
   MSG_SAC2L1AUDIO_SPEECH_CTM_CONFIG_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_GET_TIME_ON_ACK = MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x160,
   MSG_SAC2L1AUDIO_SPEECH_GET_TIME_OFF_ACK,
   
   MSG_SAC2L1AUDIO_SPEECH_DATACARD_OPEN_ACK= MDCIMSG_SAC2L1AUDIO_SPEECH_BASE + 0x170,
   MSG_SAC2L1AUDIO_SPEECH_DATACARD_CLOSE_ACK,
   MSG_SAC2L1AUDIO_SPEECH_DATACARD_REQUEST_EXCHANGE_UL_DATA,
   MSG_SAC2L1AUDIO_SPEECH_DATACARD_REQUEST_EXCHANGE_DL_DATA,

   /*===============================================================*/
   // Flow Control
   MSG_SAC2L1AUDIO_AUDIO_GET_ID_ACK = MDCIMSG_SAC2L1AUDIO_AUDIO_BASE,
   MSG_SAC2L1AUDIO_AUDIO_FREE_ID_ACK,
   MSG_SAC2L1AUDIO_AUDIO_PLAYBACK_ON_ACK,
   MSG_SAC2L1AUDIO_AUDIO_PLAYBACK_OFF_ACK,
   MSG_SAC2L1AUDIO_AUDIO_RECORD_ON_ACK,
   MSG_SAC2L1AUDIO_AUDIO_RECORD_OFF_ACK,
   MSG_SAC2L1AUDIO_AUDIO_TONE_PLAYBACK_ON_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_PLAY_RATE_ACK,
   MSG_SAC2L1AUDIO_AUDIO_MELODY_PLAYBACK_OFF,

   // Data transmission
   MSG_SAC2L1AUDIO_AUDIO_WRITE_DATA_ACK,
   MSG_SAC2L1AUDIO_AUDIO_DATA_REQUEST,
   MSG_SAC2L1AUDIO_AUDIO_DATA_NOTIFICATION,
   MSG_SAC2L1AUDIO_AUDIO_SECURITY_ACK,

   // Path and volume. Currently, we don¡¦t need to acknowledge this kind of message.
   MSG_SAC2L1AUDIO_AUDIO_SET_OUTPUT_DEVICE_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_OUTPUT_VOLUME_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_INPUT_DEVICE_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_INPUT_VOLUME_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_STEREO2MONO_ACK,
   MSG_SAC2L1AUDIO_AUDIO_SET_TONE_VOLUME_ACK, 
   MSG_SAC2L1AUDIO_AUDIO_AVSYNC_INITIALIZE_ACK,
   MSG_SAC2L1AUDIO_AUDIO_AVSYNC_SET_INTERVAL_ACK,
   MSG_SAC2L1AUDIO_AUDIO_AVSYNC_NOTIFY,
   
   /*===================MDCIMSG_FAS2L1D_COSIM_BASE==============*/
   MDCIMSG_FAS2L1D_COSIM_IRQ_TEST_ACK = MDCIMSG_FAS2L1D_COSIM_BASE,
   MDCIMSG_FAS2L1D_COSIM_MEMIF_TEST_ACK,
   MDCIMSG_FAS2L1D_COSIM_DLSRC_TEST_ACK,
   MDCIMSG_FAS2L1D_COSIM_ULSRC_TEST_ACK,
   
   /*===================MDCIMSG_SAC2L1AUDIO_HW_BASE=============*/
   MSG_SAC2L1AUDIO_HW_BLUETOOTH_SYNC_TYPE_ACK = MDCIMSG_SAC2L1AUDIO_HW_BASE,
   MSG_SAC2L1AUDIO_HW_BLUETOOTH_FRAME_SYNC_LENGTH_ACK,
   MSG_SAC2L1AUDIO_HW_BLUETOOTH_WORD_SELECTION_ACK,
   MSG_SAC2L1AUDIO_HW_BLUETOOTH_DATA_RATE_MODE_ACK,

   MSG_SAC2L1AUDIO_HW_DIGITAL_MIC_CLOCK_PHASE_CH1_ACK = MDCIMSG_SAC2L1AUDIO_HW_BASE + 0x10,
   MSG_SAC2L1AUDIO_HW_DIGITAL_MIC_CLOCK_PHASE_CH2_ACK,
   MSG_SAC2L1AUDIO_HW_DIGITAL_MIC_INPUT_SAMPLING_RATE_ACK,

   MSG_SAC2L1AUDIO_HW_I2S_IN_CLOCK_MODE_ACK = MDCIMSG_SAC2L1AUDIO_HW_BASE + 0x20,
   
   MSG_SAC2L1AUDIO_HW_DAC_LBUF_RATIO_ACK = MDCIMSG_SAC2L1AUDIO_HW_BASE + 0x30,
   MSG_SAC2L1AUDIO_HW_DAC_RBUF_RATIO_ACK,
   MSG_SAC2L1AUDIO_HW_DAC_MONO_RATIO_ACK,

} SAC2L1AUDIO_AUDIO_MSG;
#endif //defined(__DSP_FCORE4__)

#endif
