
#ifndef __AUDIO_LP_EXPORT__
#define __AUDIO_LP_EXPORT__


typedef enum {
   AUDLP_OK = 0,
   AUDLP_WARN_LAST_SEVERAL_PST,
   AUDLP_ERR_NO_ENOUGH_PST,
   AUDLP_ERR_FS_GET_DEVICEID,
   AUDLP_ERR_FS_PST_API,
   AUDLP_ERR_FS_PST_VALIDENTRY_NOTENOUGH,
   AUDLP_ERR_XXX1
} AUDLP_STATUS;

typedef enum {
   AUDMA_ID_MED = 0,
   AUDMA_ID_FS = 1,
   AUDMA_ID_NFI = 2,
   AUDMA_ID_ECC = 3,
   AUDMA_ID_MSDC = 4,
   AUDMA_ID_RESERVED = 5
} AUDMA_USER_ID;

AUDLP_STATUS AUDMA_LOCK( AUDMA_USER_ID register_id);
AUDLP_STATUS AUDMA_UNLOCK( AUDMA_USER_ID register_id);


#endif //__AUDIO_LP_EXPORT__
