
#undef L2TPS_RB_CFG_BEGIN
#undef L2TPS_RB_CFG_START

#undef L2TPS_RB_DIRECTION

#undef L2TPS_RB_RLC_MODE
#undef L2TPS_RB_RLC_SN_LEN
#undef L2TPS_RB_RLC_INI_SN
#undef L2TPS_RB_RLC_POLL_PDU
#undef L2TPS_RB_RLC_POLL_BYTE 
#undef L2TPS_RB_RLC_UL_RETX_MAX
#undef L2TPS_RB_RLC_POLL_RETX_TMR
#undef L2TPS_RB_RLC_T_REODER_TMR
#undef L2TPS_RB_RLC_STUS_PROH_TMR

#undef L2TPS_RB_PDCP_SN_SZ
#undef L2TPS_RB_PDCP_ROHC
#undef L2TPS_RB_PDCP_DISC_TMR

#undef L2TPS_RB_MAC_PRI
#undef L2TPS_RB_MAC_PBR
#undef L2TPS_RB_MAC_LCG
#undef L2TPS_RB_MAC_BSD

#undef L2TPS_RB_CFG_END
#undef L2TPS_RB_CFG_FINISH

