/*****************************************************************************
 *
 * Filename:
 * ---------
 *   emm_msgid.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *   LTE NAS EMM (EPS Mobility Management) related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 *
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _EMM_MSGID_H
#define _EMM_MSGID_H

MODULE_MSG_BEGIN( MSG_ID_EMM_CODE_BEGIN )

/****************************************************************************
 *                          Destination: EMM (EVAL to EMM) 
 ****************************************************************************/
MSG_ID_EVAL_EMM_SET_RAT_MODE_REQ  = MSG_ID_EMM_CODE_BEGIN,
MSG_ID_EVAL_EMM_ATTACH_REQ,
MSG_ID_EVAL_EMM_DETACH_REQ,
MSG_ID_EVAL_EMM_EMC_ATTACH_REQ, // for IMS
MSG_ID_EVAL_EMM_INIT_REQ,
MSG_ID_EVAL_EMM_RFOFF_REQ,
MSG_ID_EVAL_EMM_UEMODE_PARAM_UPDATE_REQ,
MSG_ID_EVAL_EMM_SET_PREFERRED_BAND_REQ,
MSG_ID_EVAL_EMM_PLMN_SEARCH_REQ,
MSG_ID_EVAL_EMM_DEACTIVATE_REQ,
MSG_ID_EVAL_EMM_NAS_CTXT_TRANSFER_REQ,
MSG_ID_EVAL_EMM_SEARCH_STATUS_UPDATE_REQ,
MSG_ID_EVAL_EMM_SYS_INFO_UPDATE_REQ,
MSG_ID_EVAL_EMM_REGN_STATUS_UPDATE_REQ,
MSG_ID_EVAL_EMM_PLMN_LIST_REQ,
MSG_ID_EVAL_EMM_PLMN_LIST_STOP_REQ,
MSG_ID_EVAL_EMM_CSG_LIST_REQ,
MSG_ID_EVAL_EMM_CSG_LIST_STOP_REQ,
MSG_ID_EVAL_EMM_EMC_FPLMN_LIST_UPDATE_REQ, // for IMS
MSG_ID_EVAL_EMM_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_EVAL_EMM_RPLMN_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_EVAL_EMM_HPLMN_INFO_UPDATE_REQ,
MSG_ID_EVAL_EMM_SMS_EST_REQ,
MSG_ID_EVAL_EMM_SMS_UNITDATA_REQ,
MSG_ID_EVAL_EMM_LCS_DATA_REQ, // for LPP
MSG_ID_EVAL_EMM_LPP_DATA_REQ, // for LPP
MSG_ID_EVAL_EMM_SIM_READY_REQ,
MSG_ID_EVAL_EMM_AUTHENTICATE_RSP,
MSG_ID_EVAL_EMM_SIM_ERROR_REQ,
MSG_ID_EVAL_EMM_SIM_FILE_UPDATE_REQ,
MSG_ID_EVAL_EMM_SEARCH_PREFERENCE_UPDATE_REQ, // for IMS
MSG_ID_EVAL_EMM_RESUME_REQ,
MSG_ID_EVAL_EMM_ACTIVE_SIM_INFO_REQ,
MSG_ID_EVAL_EMM_SET_IMS_VOICE_AVAILABILITY_REQ, // for IMS
MSG_ID_EVAL_EMM_SET_IMS_VOICE_TERMINATION_REQ, // for IMS

#ifdef __SGLTE__
MSG_ID_EVAL_EMM_PS_SWITCH_REQ, 
MSG_ID_EVAL_EMM_PS_SWITCH_SUSPEND_REQ, 
MSG_ID_EVAL_EMM_PS_SWITCH_RESUME_REQ, 
#endif /* __SGLTE__ */

/****************************************************************************
 *                          Destination: EMM (ESM to EMM) 
 ****************************************************************************/
/* From ESM */
MSG_ID_ESM_EMM_EST_REQ,
MSG_ID_ESM_EMM_GET_ESM_CAUSE_RSP,
MSG_ID_ESM_EMM_SYNC_EPSB_STATUS_REQ,
MSG_ID_ESM_EMM_GET_EPSB_STATUS_RSP,
MSG_ID_ESM_EMM_DETACH_REQ,
MSG_ID_ESM_EMM_ISR_DEACT_REQ,
MSG_ID_ESM_EMM_QOSLABEL_UPDATE_REQ,
MSG_ID_ESM_EMM_DATA_REQ,
MSG_ID_ESM_EMM_REEST_REQ,
MSG_ID_ESM_EMM_ABORT_REQ,
MSG_ID_ESM_EMM_RAT_CHANGE_RSP,
MSG_ID_ESM_EMM_RAT_CHANGE_REQ,
MSG_ID_ESM_EMM_RAT_CHANGE_EPSB_STATUS_REQ,
MSG_ID_ESM_EMM_EMC_BEARER_STATUS_REQ, // for IMS
MSG_ID_ESM_EMM_UPDATE_EPSB_STATUS_RSP, // for IMS
MSG_ID_ESM_EMM_ENTER_EMC_ATTACH_RSP,  // for IMS

#ifdef __SGLTE__
MSG_ID_ESM_EMM_PS_SWITCH_CONTEXT_TRANSFER_RSP, 
MSG_ID_ESM_EMM_PS_SWITCH_CONTEXT_TRANSFER_REQ,  
MSG_ID_ESM_EMM_PS_SWITCH_CONTEXT_TRANSFER_FINAL_RSP, 
#endif /* __SGLTE__ */
/****************************************************************************
 *                          Destination: EMM (ERRC to EMM) 
 ****************************************************************************/

/* From ERRC */ 
MSG_ID_EMM_ERRC_ACTIVATION_CNF,
MSG_ID_EMM_ERRC_RAT_BAND_CNF,
MSG_ID_EMM_ERRC_ESTABLISH_CNF,
MSG_ID_EMM_ERRC_RELEASE_CNF,
MSG_ID_EMM_ERRC_RELEASE_IND,
MSG_ID_EMM_ERRC_DATA_CNF,
MSG_ID_EMM_ERRC_DATA_IND,
MSG_ID_EMM_ERRC_EPSBEARER_DATA_IND,
MSG_ID_EMM_ERRC_AC_STATUS_IND,
MSG_ID_EMM_ERRC_KEY_UPDATE_CNF,
MSG_ID_EMM_ERRC_TEST_CNF,
MSG_ID_EMM_ERRC_OOS_IND,
MSG_ID_EMM_ERRC_CELLSELECT_CNF,
MSG_ID_EMM_ERRC_CELLSELECT_IND,
MSG_ID_EMM_ERRC_PLMNLIST_CNF,
MSG_ID_EMM_ERRC_RESUME_CNF,
MSG_ID_EMM_ERRC_PAGE_IND,
MSG_ID_EMM_ERRC_EXCLUSIVE_CONTROL_CNF,
MSG_ID_EMM_ERRC_RAT_CHANGE_CNF,
MSG_ID_EMM_ERRC_RAT_CHANGE_IND,
MSG_ID_EMM_ERRC_CSFB_FAILURE_IND,
MSG_ID_EMM_ERRC_STANDBY_CNF,
MSG_ID_EMM_ERRC_STANDBY_IND,
MSG_ID_EMM_ERRC_PARAM_UPDATE_CNF,
MSG_ID_EMM_ERRC_QOS_UPDATE_CNF,
MSG_ID_EMM_ERRC_SIGNAL_APPEAR_IND,
MSG_ID_EMM_ERRC_CSG_LIST_CNF,
MSG_ID_EMM_ERRC_CSG_LIST_STOP_CNF,
MSG_ID_EMM_ERRC_STATUS_UPDATE_CNF,
MSG_ID_EMM_ERRC_SKIP_IRCCO_STAGE2_IND,
MSG_ID_EMM_ERRC_CELL_CHANGE_IND,
MSG_ID_EMM_ERRC_GEMINI_SUSPEND_IND,

/****************************************************************************
 *                          Destination: EMM (MM to EMM) 
 ****************************************************************************/

/* From MM */
MSG_ID_MM_EMM_INIT_NAS_CTXT_RSP,
MSG_ID_MM_EMM_GMM_UPDATE_REGISTRATION_REQ,
MSG_ID_MM_EMM_GMM_UPDATE_DEREGISTRATION_REQ,
MSG_ID_MM_EMM_MM_UPDATE_REGISTRATION_REQ,
MSG_ID_MM_EMM_MM_UPDATE_DEREGISTRATION_REQ,
MSG_ID_MM_EMM_CSFB_REQ,
MSG_ID_MM_EMM_CSFB_STOP_REQ,
MSG_ID_MM_EMM_CSFB_PAGE_RSP,
MSG_ID_MM_EMM_ISR_UPDATE_REQ,
MSG_ID_MM_EMM_UPDATE_SECURITY_STATUS_IND,

#ifdef __SGLTE__
MSG_ID_MM_EMM_PEER_LR_HANDLE_PREPARATION_REQ,
MSG_ID_MM_EMM_PEER_LR_RESULT_REQ,
#endif /* __SGLTE__ */

/* To MM (move to mm_msgid.h) */
//MSG_ID_MM_EMM_INIT_NAS_CTXT_IND,
//MSG_ID_MM_EMM_EMM_UPDATE_REGISTRATION_IND,
//MSG_ID_MM_EMM_EMM_UPDATE_DEREGISTRATION_IND,
//MSG_ID_MM_EMM_CSFB_CNF,
//MSG_ID_MM_EMM_CSFB_PAGE_IND,
//MSG_ID_MM_EMM_ISR_UPDATE_IND,
//#ifdef __SGLTE__
//MSG_ID_MM_EMM_PEER_LR_HANDLE_PREPARATION_CNF,
//MSG_ID_MM_EMM_PEER_LR_RESULT_IND,
//#endif


/****************************************************************************
 *                          Destination: EMM_CALL
 ****************************************************************************/
MSG_ID_EMM_ESMIF_CALL_DATA_REQ,
MSG_ID_EMM_ESMIF_CALL_REEST_REQ,
MSG_ID_EMM_ESMIF_CALL_BEARER_IND,
MSG_ID_EMM_ESMIF_CALL_ABORT_REQ,
MSG_ID_EMM_ERRCIF_CALL_STMSI_PAGE_IND,
MSG_ID_EMM_ERRCIF_CALL_CS_PAGE_IND,
MSG_ID_EMM_ERRCIF_CALL_CSFB_FAILURE_IND,
MSG_ID_EMM_ERRCIF_CALL_RCV_EPSBEARER_IND,
MSG_ID_EMM_ERRCIF_CALL_SND_NASMSG_CNF,
MSG_ID_EMM_MMIF_CALL_CSFB_REQ,
MSG_ID_EMM_MMIF_CALL_CSFB_STOP_REQ,
MSG_ID_EMM_MMIF_CALL_CSFB_PAGE_RSP,
MSG_ID_EMM_EVALIF_CALL_SMS_EST_REQ,
MSG_ID_EMM_EVALIF_CALL_SMS_UNITDATA_REQ,
MSG_ID_EMM_EVALIF_CALL_LCS_DATA_REQ, // for LPP
MSG_ID_EMM_EVALIF_CALL_LPP_DATA_REQ, // for LPP
MSG_ID_EMM_TIMERIF_CALL_T3417EXT_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_CALL_T_CSFB_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_CALL_T3417_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_CALL_T3442_TIMEOUT_IND,
MSG_ID_EMM_REG_CALL_ATTACH_RESULT_IND,
MSG_ID_EMM_REG_CALL_CS_NW_DETACH_IND,
MSG_ID_EMM_REG_CALL_REL_EPSB_CTXT_IND,
MSG_ID_EMM_REG_CALL_SND_ESMMSG_CNF,
MSG_ID_EMM_REG_CALL_TAU_PENDING_IND,
MSG_ID_EMM_REG_CALL_SUSPEND_SR_REQ,
MSG_ID_EMM_REG_CALL_RESUME_SR_REQ,
MSG_ID_EMM_REG_CALL_UE_DETACH_IND,
MSG_ID_EMM_PLMNSEL_CALL_CONOOS_LEAVELTE_IND,
MSG_ID_EMM_PLMNSEL_CALL_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_CALL_NO_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_CALL_CAMPON_2G3G_IND,
MSG_ID_EMM_PLMNSEL_CALL_GEMINI_SUSPEND_IND,
MSG_ID_EMM_RATCHG_CALL_RAT_LTESBY_IND,      // need to remove
MSG_ID_EMM_RATCHG_CALL_RAT_E2UG_FAIL_IND,   // need to remove
MSG_ID_EMM_RATCHG_CALL_AS_CONTROL_CNF,      // need to remove
MSG_ID_EMM_PLMNSEL_CALL_EMC_STATUS_UPDATE_IND, // for IMS
MSG_ID_EMM_RATCHG_CALL_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_CALL_IRAT_E2UG_FAIL_IND,
MSG_ID_EMM_RATCHG_CALL_IRAT_UG2E_COMP_IND,
MSG_ID_EMM_CONN_CALL_REL_IND,
MSG_ID_EMM_CONN_CALL_EST_CNF,
MSG_ID_EMM_CONN_CALL_AC_STATUS_IND,
MSG_ID_EMM_NASMSG_CALL_RCV_CS_SERVICE_NOTIFICATION_IND,
MSG_ID_EMM_NASMSG_CALL_RCV_SERVICE_REJ_IND,
MSG_ID_EMM_EVTCTRL_CALL_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_CALL_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_CALL_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_CALL_CONTINUE_REQ,
MSG_ID_EMM_EVTCTRL_CALL_WDT_POLLING_REQ,
MSG_ID_EMM_CALL_UT_CFG_REQ,

/****************************************************************************
 *                          Destination: EMM_CMNPROC
 ****************************************************************************/
MSG_ID_EMM_ERRCIF_CMNPROC_SND_NASMSG_CNF,
MSG_ID_EMM_NASMSG_CMNPROC_RCV_IDENTITY_REQUEST_IND,
MSG_ID_EMM_NASMSG_CMNPROC_RCV_EMM_INFORMATION_IND,
MSG_ID_EMM_NASMSG_CMNPROC_RCV_EMM_STATUS_IND,
MSG_ID_EMM_NASMSG_CMNPROC_RCV_GUTI_REALLOC_CMD_IND,
MSG_ID_EMM_PLMNSEL_CMNPROC_CELL_INFO_IND,
MSG_ID_EMM_ANY_CMNPROC_UT_CONFIG_REQ,
/****************************************************************************
 *                          Destination: EMM_CONN
 ****************************************************************************/
MSG_ID_EMM_CALL_CONN_REL_REQ,
MSG_ID_EMM_CALL_CONN_EST_REQ,
MSG_ID_EMM_ERRCIF_CONN_ESTABLISH_CNF,
MSG_ID_EMM_ERRCIF_CONN_RELEASE_IND,
MSG_ID_EMM_ERRCIF_CONN_RELEASE_CNF,
MSG_ID_EMM_ERRCIF_CONN_AC_STATUS_IND,
MSG_ID_EMM_NASMSG_CONN_T3440_STOP_REQ,
MSG_ID_EMM_PLMNSEL_CONN_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_CONN_REL_REQ,
MSG_ID_EMM_PLMNSEL_CONN_GEMINI_SUSPEND_IND,
MSG_ID_EMM_RATCHG_CONN_EST_REQ,
MSG_ID_EMM_RATCHG_CONN_REL_REQ,
MSG_ID_EMM_RATCHG_CONN_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_CONN_STANDBY_IND,
MSG_ID_EMM_RATCHG_CONN_RAT_HO_U2E_COMP_IND,
MSG_ID_EMM_REG_CONN_REL_REQ,
MSG_ID_EMM_REG_CONN_EST_REQ,
MSG_ID_EMM_REG_CONN_REL_RSP,
MSG_ID_EMM_REG_CONN_T3440_STOP_REQ,
MSG_ID_EMM_REG_CONN_WAIT_REL_CON_REQ,
MSG_ID_EMM_SEC_CONN_REL_REQ,
MSG_ID_EMM_TIMERIF_CONN_T3440_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_CONN_DEREG_REL_TIMEOUT_IND,
MSG_ID_EMM_CONN_UT_SETTING_CHANGE_IND,

/****************************************************************************
 *                          Destination: EMM_ERRCIF
 ****************************************************************************/
MSG_ID_EMM_REG_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_REG_ERRCIF_CSG_WHITE_LIST_UPDT_REQ,
MSG_ID_EMM_REG_ERRCIF_GEMINI_LR_REQ,
MSG_ID_EMM_CALL_ERRCIF_CSG_WHITE_LIST_UPDT_REQ,
MSG_ID_EMM_CALL_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_CALL_ERRCIF_CSFB_NTF,
MSG_ID_EMM_PLMNSEL_ERRCIF_PLMNLIST_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_CSG_LIST_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_CSG_LIST_STOP_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_CELLSELECT_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_NWSEL_STATUS_UPDATE_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_PLMNSEL_ERRCIF_SEARCH_PREFERENCE_UPDATE_REQ, // for IMS
MSG_ID_EMM_PLMNSEL_ERRCIF_CSG_WHITE_LIST_UPDT_REQ, // modified with IMS
MSG_ID_EMM_PLMNSEL_ERRCIF_CHECK_SERVING_SUITABILITY_REQ, // for IMS
MSG_ID_EMM_RATCHG_ERRCIF_RAT_CHANGE_REQ,
MSG_ID_EMM_RATCHG_ERRCIF_RAT_CHANGE_RSP,
MSG_ID_EMM_RATCHG_ERRCIF_STANDBY_REQ,
MSG_ID_EMM_RATCHG_ERRCIF_RESUME_REQ,
MSG_ID_EMM_RATCHG_ERRCIF_REG_STATUS_UPDATE_REQ,
MSG_ID_EMM_RATCHG_ERRCIF_RAT_CHANGE_CAUSE_UPDATE_REQ,
MSG_ID_EMM_SEC_ERRCIF_KEY_UPDATE_REQ,
MSG_ID_EMM_SEC_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_SEC_ERRCIF_NULL_SECURITY_ACCEPT_REQ,
MSG_ID_EMM_CONN_ERRCIF_ESTABLISH_REQ,
MSG_ID_EMM_CONN_ERRCIF_RELEASE_REQ,
MSG_ID_EMM_CONN_ERRCIF_RELEASE_RSP,
MSG_ID_EMM_CONN_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_CMNPROC_ERRCIF_PARAM_UPDATE_REQ,
MSG_ID_EMM_NASMSG_ERRCIF_DATA_REQ,
MSG_ID_EMM_ESMIF_ERRCIF_QOSLABEL_UPDATE_REQ,
MSG_ID_EMM_SV_ERRCIF_ACTIVATION_REQ,
MSG_ID_EMM_SV_ERRCIF_REG_STATUS_UPDATE_REQ,
MSG_ID_EMM_SV_ERRCIF_CSG_WHITE_LIST_UPDT_REQ,
MSG_ID_EMM_SV_ERRCIF_SIM_FILE_UPDATE_REQ,
MSG_ID_EMM_RATBAND_ERRCIF_RAT_BAND_REQ,
MSG_ID_EMM_ETCIF_ERRCIF_TEST_REQ,
MSG_ID_EMM_CALL_ERRCIF_GEMINI_CSFB_STATUS_REQ,
MSG_ID_EMM_ERRCIF_UT_CONFIG_REQ,
MSG_ID_EMM_ERRCIF_UT_STATUS_IND,
     
/****************************************************************************
 *                          Destination: EMM_ESMIF
 ****************************************************************************/
MSG_ID_EMM_REG_ESMIF_GET_EPSB_STATUS_IND,
MSG_ID_EMM_REG_ESMIF_DATA_RESUME_IND,
MSG_ID_EMM_REG_ESMIF_DATA_SUSPEND_IND,
MSG_ID_EMM_REG_ESMIF_URGE_TO_EST_IND,
MSG_ID_EMM_REG_ESMIF_UPDATE_EPSB_STATUS_IND,
MSG_ID_EMM_REG_ESMIF_DEREG_IND,
MSG_ID_EMM_REG_ESMIF_GET_ESM_CAUSE_IND,
MSG_ID_EMM_REG_ESMIF_EMC_ATTACH_REJ_IND, // for IMS
MSG_ID_EMM_REG_ESMIF_URGE_TO_EMC_EST_IND, // for IMS
MSG_ID_EMM_REG_ESMIF_EMC_DATA_FAIL_IND, // for IMS
MSG_ID_EMM_CALL_ESMIF_DATA_CNF,
MSG_ID_EMM_CALL_ESMIF_DATA_SEND_IND,
MSG_ID_EMM_CALL_ESMIF_REEST_REJ,
MSG_ID_EMM_CALL_ESMIF_ABORT_CNF,
MSG_ID_EMM_RATCHG_ESMIF_RAT_CHANGE_IND,
MSG_ID_EMM_RATCHG_ESMIF_RAT_CHANGE_CNF,
MSG_ID_EMM_CONN_ESMIF_CONN_RELEASE_IND,
MSG_ID_EMM_NASMSG_ESMIF_EPSBEARER_DATA_IND,
MSG_ID_EMM_NASMSG_ESMIF_DATA_IND,
#ifdef __SGLTE__
MSG_ID_EMM_RATCHG_ESMIF_PS_SWITCH_CONTEXT_TRANSFER_IND,
MSG_ID_EMM_RATCHG_ESMIF_PS_SWITCH_CONTEXT_TRANSFER_CNF,
#endif /* __SGLTE__ */
MSG_ID_EMM_SEC_ESMIF_ENTER_EMC_ATTACH_IND, // for IMS
MSG_ID_EMM_PLMNSEL_ESMIF_GEMINI_SUSPEND_IND,
MSG_ID_EMM_PLMNSEL_ESMIF_GEMINI_RESUME_IND,

/****************************************************************************
 *                          Destination: EMM_ETCIF
 ****************************************************************************/
MSG_ID_EMM_ERRCIF_ETCIF_DATA_CNF,
MSG_ID_EMM_NASMSG_ETCIF_DATA_IND,
MSG_ID_EMM_ERRCIF_ETCIF_TEST_CNF,
MSG_ID_EMM_REG_ETCIF_DETACH_IND,
MSG_ID_EMM_CONN_ETCIF_REL_IND,
MSG_ID_EMM_SV_ETCIF_POWER_DOWN_IND,

/****************************************************************************
 *                          Destination: EMM_EVALIF
 ****************************************************************************/
MSG_ID_EMM_REG_EVALIF_DETACH_IND,
MSG_ID_EMM_REG_EVALIF_ATTACH_CNF,
MSG_ID_EMM_REG_EVALIF_NW_ECC_IND,
MSG_ID_EMM_REG_EVALIF_REGN_RESULT_IND,
MSG_ID_EMM_REG_EVALIF_NW_REJECT_IND,
MSG_ID_EMM_REG_EVALIF_NW_FEATURE_SUPPORT_IND, // for IMS
MSG_ID_EMM_REG_EVALIF_EMC_ATTACH_CNF, // for IMS
MSG_ID_EMM_REG_EVALIF_EMC_DETACH_IND, // for IMS
MSG_ID_EMM_CALL_EVALIF_SMS_EST_CNF,
MSG_ID_EMM_CALL_EVALIF_SMS_EST_REJ,
MSG_ID_EMM_CALL_EVALIF_SMS_ERR_IND,
MSG_ID_EMM_CALL_EVALIF_LCS_DATA_CNF, // for LPP
MSG_ID_EMM_CALL_EVALIF_LPP_DATA_CNF, // for LPP
MSG_ID_EMM_PLMNSEL_EVALIF_PLMN_LIST_CNF,
MSG_ID_EMM_PLMNSEL_EVALIF_PLMN_LIST_STOP_CNF,
MSG_ID_EMM_PLMNSEL_EVALIF_PLMN_SEARCH_CNF,
MSG_ID_EMM_PLMNSEL_EVALIF_PLMN_SEARCH_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_SYS_INFO_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_PLMN_LOSS_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_OUT_OF_SERVICE_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_NO_ACTION_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_CSG_LIST_CNF,
MSG_ID_EMM_PLMNSEL_EVALIF_CSG_LIST_STOP_CNF,
MSG_ID_EMM_PLMNSEL_EVALIF_SIGNAL_APPEAR_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_REGN_RESULT_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_CELL_INFO_UPDATE_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_DETACH_IND,
MSG_ID_EMM_PLMNSEL_EVALIF_EMERGENCY_STATUS_UPDATE_IND, // for IMS
MSG_ID_EMM_RATCHG_EVALIF_DEACTIVATE_CNF,
MSG_ID_EMM_RATCHG_EVALIF_NAS_CTXT_TRANSFER_CNF,
MSG_ID_EMM_RATCHG_EVALIF_SRVCC_STATUS_UPDATE_IND, // for IMS
MSG_ID_EMM_SEC_EVALIF_AUTHENTICATE_IND,
MSG_ID_EMM_CMNPROC_EVALIF_NW_INFO_IND,
MSG_ID_EMM_RATBAND_EVALIF_SET_RAT_MODE_CNF,
MSG_ID_EMM_RATBAND_EVALIF_RFOFF_CNF,
MSG_ID_EMM_RATBAND_EVALIF_SET_PREFERRED_BAND_REQ,
MSG_ID_EMM_NASMSG_EVALIF_SMS_UNITDATA_IND,
MSG_ID_EMM_NASMSG_EVALIF_LPP_DATA_IND, // for LPP
MSG_ID_EMM_NASMSG_EVALIF_LCS_DATA_IND, // for LPP

#ifdef __SGLTE__
MSG_ID_EMM_RATCHG_EVALIF_PS_SWITCH_CNF,
MSG_ID_EMM_RATCHG_EVALIF_PS_SWITCH_SUSPEND_CNF,
MSG_ID_EMM_RATCHG_EVALIF_PS_SWITCH_IND,
#endif /* __SGLTE__ */

 /****************************************************************************
 *                          Destination: EMM_EVTCTRL
 ****************************************************************************/
/* END_IND */
MSG_ID_EMM_SV_EVTCTRL_END_IND,
MSG_ID_EMM_RATBAND_EVTCTRL_END_IND,
MSG_ID_EMM_RATCHG_EVTCTRL_END_IND,
MSG_ID_EMM_REG_EVTCTRL_END_IND,
MSG_ID_EMM_CALL_EVTCTRL_END_IND,
MSG_ID_EMM_PLMNSEL_EVTCTRL_END_IND,
/* ABORT_CNF */
MSG_ID_EMM_SV_EVTCTRL_ABORT_CNF,
MSG_ID_EMM_RATBAND_EVTCTRL_ABORT_CNF,
MSG_ID_EMM_RATCHG_EVTCTRL_ABORT_CNF,
MSG_ID_EMM_REG_EVTCTRL_ABORT_CNF,
MSG_ID_EMM_CALL_EVTCTRL_ABORT_CNF,
MSG_ID_EMM_PLMNSEL_EVTCTRL_ABORT_CNF,
/* SUSPEND_CNF */
MSG_ID_EMM_SV_EVTCTRL_SUSPEND_CNF,
MSG_ID_EMM_RATBAND_EVTCTRL_SUSPEND_CNF,
MSG_ID_EMM_RATCHG_EVTCTRL_SUSPEND_CNF,
MSG_ID_EMM_REG_EVTCTRL_SUSPEND_CNF,
MSG_ID_EMM_CALL_EVTCTRL_SUSPEND_CNF,
MSG_ID_EMM_PLMNSEL_EVTCTRL_SUSPEND_CNF,
/* TIMERIF */
MSG_ID_EMM_TIMERIF_EVTCTRL_WDT_TIMEOUT_IND,
/* For UT */
MSG_ID_EMM_EVTCTRL_UT_START_REQ,
MSG_ID_EMM_EVTCTRL_UT_STOP_REQ,
MSG_ID_EMM_EVTCTRL_UT_STATE_SET_REQ,
MSG_ID_EMM_EVTCTRL_UT_EVENT_START_REQ,
MSG_ID_EMM_EVTCTRL_UT_PUBLIC_API_REQ,
MSG_ID_EMM_EVTCTRL_UT_PUBLIC_API_CNF,
 
/****************************************************************************
 *                          Destination: EMM_MMIF
 ****************************************************************************/
MSG_ID_EMM_REG_MMIF_ISR_UPDATE_IND,
MSG_ID_EMM_REG_MMIF_EMM_UPDATE_REGISTRATION_IND,
MSG_ID_EMM_REG_MMIF_EMM_UPDATE_DEREGISTRATION_IND,
#ifdef __SGLTE__
MSG_ID_EMM_REG_MMIF_PEER_LR_RESULT_IND,
MSG_ID_EMM_RATCHG_MMIF_PEER_LR_HANDLE_PREPARATION_CNF,
#endif /*__SGLTE__*/
MSG_ID_EMM_CALL_MMIF_CSFB_CNF,
MSG_ID_EMM_CALL_MMIF_CSFB_PAGE_IND,
MSG_ID_EMM_RATCHG_MMIF_INIT_NAS_CTXT_IND,
 
/****************************************************************************
 *                          Destination: EMM_NASMSG
 ****************************************************************************/
MSG_ID_EMM_CALL_NASMSG_SND_NASMSG_REQ,
MSG_ID_EMM_CALL_NASMSG_SND_SERV_REQ,
MSG_ID_EMM_REG_NASMSG_SND_NASMSG_REQ,
MSG_ID_EMM_REG_NASMSG_SND_ESM_MSG_REQ,
MSG_ID_EMM_REG_NASMSG_ACCEPT_FAILURE_IND,
MSG_ID_EMM_SEC_NASMSG_SND_NASMSG_REQ,
MSG_ID_EMM_SEC_NASMSG_EXCHG_REEST_CNF,
MSG_ID_EMM_CMNPROC_NASMSG_SND_NASMSG_REQ,
MSG_ID_EMM_ERRCIF_NASMSG_EPSBEARER_DATA_IND,
MSG_ID_EMM_ERRCIF_NASMSG_DATA_IND,
MSG_ID_EMM_NASMSG_UT_SETTING_CHANGE_IND,
MSG_ID_EMM_ETCIF_NASMSG_DATA_REQ,
MSG_ID_EMM_PLMNSEL_NASMSG_CELL_INFO_IND,
MSG_ID_EMM_ERRCIF_NASMSG_CELL_CHANGE_IND,
MSG_ID_EMM_CONN_NASMSG_REL_IND,

/****************************************************************************
 *                          Destination: EMM_PLMNSEL
 ****************************************************************************/
MSG_ID_EMM_EVALIF_PLMNSEL_PLMN_LIST_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_PLMN_LIST_STOP_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_PLMN_SEARCH_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_SYS_INFO_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_SEARCH_STATUS_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_CSG_LIST_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_CSG_LIST_STOP_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_EMC_FPLMN_LIST_UPDATE_REQ, // for IMS
MSG_ID_EMM_EVALIF_PLMNSEL_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_RPLMN_EQ_PLMN_LIST_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_HPLMN_INFO_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_REGN_STATUS_UPDATE_REQ,
MSG_ID_EMM_EVALIF_PLMNSEL_SEARCH_PREFERENCE_UPDATE_REQ, // for IMS
MSG_ID_EMM_EVALIF_PLMNSEL_RESUME_REQ,
MSG_ID_EMM_ERRCIF_PLMNSEL_PLMNLIST_CNF,
MSG_ID_EMM_ERRCIF_PLMNSEL_CSG_LIST_CNF,
MSG_ID_EMM_ERRCIF_PLMNSEL_CSG_LIST_STOP_CNF,
MSG_ID_EMM_ERRCIF_PLMNSEL_CELLSELECT_CNF,
MSG_ID_EMM_ERRCIF_PLMNSEL_CELLSELECT_IND,
MSG_ID_EMM_ERRCIF_PLMNSEL_OOS_IND,
MSG_ID_EMM_ERRCIF_PLMNSEL_SIGNAL_APPEAR_IND,
MSG_ID_EMM_ESMIF_PLMNSEL_EMC_BEARER_STATUS_REQ, // for IMS
MSG_ID_EMM_ERRCIF_PLMNSEL_GEMINI_SUSPEND_IND,
MSG_ID_EMM_RATCHG_PLMNSEL_AS_CONTROL_CNF,
MSG_ID_EMM_RATCHG_PLMNSEL_RAT_HO_E2U_IND,   // need to remove
MSG_ID_EMM_RATCHG_PLMNSEL_PROC_ASSBY_IND,   // need to remove
MSG_ID_EMM_RATCHG_PLMNSEL_IRAT_UG2E_IND,    // need to remove
MSG_ID_EMM_RATCHG_PLMNSEL_REDIR_E2UG_FAIL_IND,  // need to remove
MSG_ID_EMM_RATCHG_PLMNSEL_RAT_LTESBY_IND,       // need to remove
MSG_ID_EMM_RATCHG_PLMNSEL_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_PLMNSEL_STANDBY_IND,
MSG_ID_EMM_RATCHG_PLMNSEL_NO_ACTION_IND,
MSG_ID_EMM_CALL_PLMNSEL_SEARCH_2G3G_REQ,
MSG_ID_EMM_CALL_PLMNSEL_SR_END_IND,
MSG_ID_EMM_CALL_PLMNSEL_SR_CAUSE_IND, // modified with IMS
MSG_ID_EMM_REG_PLMNSEL_REGISTRATION_END_IND,
MSG_ID_EMM_REG_PLMNSEL_REGISTRATION_SUCCESS_IND,
MSG_ID_EMM_REG_PLMNSEL_ATTACH_TYPE_UPDATE_IND, // for IMS
MSG_ID_EMM_REG_PLMNSEL_REGISTRATION_CAUSE_IND, // modified with IMS
MSG_ID_EMM_REG_PLMNSEL_RESELECT_SHARED_NW_REQ, // for IMS
MSG_ID_EMM_CONN_PLMNSEL_REL_IND,
MSG_ID_EMM_EVTCTRL_PLMNSEL_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_PLMNSEL_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_PLMNSEL_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_PLMNSEL_CONTINUE_REQ,
MSG_ID_EMM_EVTCTRL_PLMNSEL_WDT_POLLING_REQ,
MSG_ID_EMM_TIMERIF_PLMNSEL_FTAI_TIMEOUT_IND,
MSG_ID_EMM_SV_PLMNSEL_SIM_ERROR_IND,
MSG_ID_EMM_SV_PLMNSEL_POWEROFF_IND,
MSG_ID_EMM_SV_PLMNSEL_SIM_READY_IND,
MSG_ID_EMM_SV_PLMNSEL_SIM_READY_CANCELED_IND,
MSG_ID_EMM_PLMNSEL_UT_CONFIG_REQ,
MSG_ID_EMM_PLMNSEL_UT_CHECK_PUBLIC_FUNCTION_REQ,
MSG_ID_EMM_PLMNSEL_UT_CHECK_PUBLIC_FUNCTION_CNF,
MSG_ID_EMM_PLMNSEL_SELF_UT_REQ, // modified with IMS

/****************************************************************************
 *                          Destination: EMM_RATBAND
 ****************************************************************************/
MSG_ID_EMM_EVTCTRL_RATBAND_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_RATBAND_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_RATBAND_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_RATBAND_CONTINUE_REQ,
MSG_ID_EMM_EVALIF_RATBAND_RFOFF_REQ,
MSG_ID_EMM_EVALIF_RATBAND_SET_PREFERRED_BAND_REQ,
MSG_ID_EMM_EVALIF_RATBAND_SET_RAT_MODE_REQ,
MSG_ID_EMM_ERRCIF_RATBAND_RAT_BAND_CNF,
MSG_ID_EMM_REG_RATBAND_DETACH_CNF,
MSG_ID_EMM_RATCHG_RATBAND_AS_CONTROL_CNF,
MSG_ID_EMM_ANY_RATBAND_UT_CONFIG_REQ,
MSG_ID_EMM_RATBAND_UT_STATUS_IND,
MSG_ID_EMM_EVTCTRL_RATBAND_WDT_POLLING_REQ,
MSG_ID_EMM_CONN_RATBAND_REL_IND,
MSG_ID_EMM_TIMERIF_RATBAND_REL_CONN_TIMEOUT_IND,

/****************************************************************************
 *                          Destination: EMM_RATCHG
 ****************************************************************************/ 
//MSG_ID_EMM_CALL_RATCHG_AS_CONTROL_REQ,
MSG_ID_EMM_PLMNSEL_RATCHG_AS_CONTROL_REQ,
MSG_ID_EMM_PLMNSEL_RATCHG_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_RATCHG_ABORT_NAS_CTXT_TRANSFER_REQ,
MSG_ID_EMM_CONN_RATCHG_EST_CNF,
MSG_ID_EMM_CONN_RATCHG_REDIRECTION_IND,
MSG_ID_EMM_CONN_RATCHG_REL_PEND_IND,
MSG_ID_EMM_CONN_RATCHG_REL_IND,
MSG_ID_EMM_ESMIF_RATCHG_RAT_CHANGE_REQ,
MSG_ID_EMM_ESMIF_RATCHG_RAT_CHANGE_RSP,
MSG_ID_EMM_EVALIF_RATCHG_NAS_CTXT_TRANSFER_REQ,
MSG_ID_EMM_EVALIF_RATCHG_DEACTIVATE_REQ,
MSG_ID_EMM_MMIF_RATCHG_INIT_NAS_CTXT_RSP,
MSG_ID_EMM_MMIF_RATCHG_UPDATE_SECURITY_STATUS_IND,
#ifdef __SGLTE__
MSG_ID_EMM_MMIF_RATCHG_PEER_LR_HANDLE_PREPARATION_REQ,
MSG_ID_EMM_ESMIF_RATCHG_PS_SWITCH_CONTEXT_TRANSFER_REQ,
MSG_ID_EMM_ESMIF_RATCHG_PS_SWITCH_CONTEXT_TRANSFER_RSP,
MSG_ID_EMM_EVALIF_RATCHG_PS_SWITCH_REQ,
MSG_ID_EMM_EVALIF_RATCHG_PS_SWITCH_SUSPEND_REQ,
MSG_ID_EMM_EVALIF_RATCHG_PS_SWITCH_RESUME_REQ,
#endif /*__SGLTE__*/
MSG_ID_EMM_ERRCIF_RATCHG_RAT_CHANGE_IND,
MSG_ID_EMM_ERRCIF_RATCHG_RAT_CHANGE_CNF,
MSG_ID_EMM_ERRCIF_RATCHG_STANDBY_CNF,
MSG_ID_EMM_ERRCIF_RATCHG_STANDBY_IND,
MSG_ID_EMM_ERRCIF_RATCHG_RESUME_CNF,
MSG_ID_EMM_ERRCIF_RATCHG_SKIP_IRCCO_STAGE2_IND,
MSG_ID_EMM_RATBAND_RATCHG_AS_CONTROL_REQ,
MSG_ID_EMM_REG_RATCHG_IRAT_E2UG_FAIL_RSP,
MSG_ID_EMM_REG_RATCHG_IRAT_UG2E_COMP_RSP,
MSG_ID_EMM_REG_RATCHG_POWER_DOWN_IND,
#ifdef __SGLTE__
MSG_ID_EMM_REG_RATCHG_RESUME_IRAT_REQ,
MSG_ID_EMM_REG_RATCHG_PS_SWITCH_RSP,
#endif /*__SGLTE__*/
MSG_ID_EMM_SV_RATCHG_SIM_READY_IND,
MSG_ID_EMM_SV_RATCHG_SIM_DETACH_IND,
MSG_ID_EMM_EVTCTRL_RATCHG_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_RATCHG_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_RATCHG_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_RATCHG_CONTINUE_REQ,
MSG_ID_EMM_EVTCTRL_RATCHG_WDT_POLLING_REQ,
MSG_ID_EMM_ANY_RATCHG_UT_CONFIG_REQ,
MSG_ID_EMM_RATCHG_UT_STATUS_IND,


/****************************************************************************
 *                          Destination: EMM_REG
 ****************************************************************************/ 
/* from CALL */
MSG_ID_EMM_CALL_REG_RCV_SERVICE_REJECT_IND,
MSG_ID_EMM_CALL_REG_TAU_INIT_REQ,
MSG_ID_EMM_CALL_REG_EXSR_SEND_IND,
MSG_ID_EMM_CALL_REG_SND_ESMMSG_REQ,
MSG_ID_EMM_CALL_REG_BEARER_IND,
MSG_ID_EMM_CALL_REG_WAITEPSINFO_START_REQ,
MSG_ID_EMM_CALL_REG_ATTACH_INIT_REQ,
MSG_ID_EMM_CALL_REG_SUSPEND_TAU_REQ,
MSG_ID_EMM_CALL_REG_RESUME_TAU_REQ,
MSG_ID_EMM_CALL_REG_SR_PENDING_IND,
MSG_ID_EMM_CALL_REG_SR_STATUS_IND, // for IMS
/* from PLMNSEL */
MSG_ID_EMM_PLMNSEL_REG_NO_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_REG_CELL_INFO_IND,
MSG_ID_EMM_PLMNSEL_REG_PLMNSEARCH_END_IND,
MSG_ID_EMM_PLMNSEL_REG_OOS_FIRST_ROUND_FAIL_IND,
MSG_ID_EMM_PLMNSEL_REG_EMC_STATUS_UPDATE_IND, // for IMS
MSG_ID_EMM_PLMNSEL_REG_RESELECT_SHARED_NW_CNF, // for IMS
MSG_ID_EMM_PLMNSEL_REG_PLMN_SEARCH_LIST_START_IND, // for IMS
MSG_ID_EMM_PLMNSEL_REG_GEMINI_SUSPEND_IND,
/* from CMNPROC */
MSG_ID_EMM_CMNPROC_REG_REG_REINIT_REQ,
/* from CONN */
MSG_ID_EMM_CONN_REG_EST_CNF,
MSG_ID_EMM_CONN_REG_REL_IND,
MSG_ID_EMM_CONN_REG_AC_STATUS_IND,
MSG_ID_EMM_CONN_REG_EST_IND,
MSG_ID_EMM_CONN_REG_T3440_STOP_CNF,
/* from ESMIF */
MSG_ID_EMM_ESMIF_REG_EST_REQ,
MSG_ID_EMM_ESMIF_REG_GET_EPSB_STATUS_RSP,
MSG_ID_EMM_ESMIF_REG_SYNC_EPSB_STATUS_REQ,
MSG_ID_EMM_ESMIF_REG_DETACH_REQ,
MSG_ID_EMM_ESMIF_REG_RAT_CHANGE_EPSB_STATUS_REQ,
MSG_ID_EMM_ESMIF_REG_ISR_DEACT_REQ,
MSG_ID_EMM_ESMIF_REG_GET_ESM_CAUSE_RSP,
MSG_ID_EMM_ESMIF_REG_UPDATE_EPSB_STATUS_RSP, // for IMS
#ifdef __SGLTE__
MSG_ID_EMM_ESMIF_REG_PS_SWITCH_CONTEXT_TRANSFER_FINAL_RSP,
#endif /*__SGLTE__*/
/* from EVALIF */
MSG_ID_EMM_EVALIF_REG_DETACH_REQ,
MSG_ID_EMM_EVALIF_REG_ATTACH_REQ,
MSG_ID_EMM_EVALIF_REG_UEMODE_PARAM_UPDATE_REQ,
MSG_ID_EMM_EVALIF_REG_EMC_ATTACH_REQ, // for IMS
MSG_ID_EMM_EVALIF_REG_ACTIVE_SIM_INFO_REQ,
MSG_ID_EMM_EVALIF_REG_SET_IMS_VOICE_AVAILABILITY_REQ, // for IMS
MSG_ID_EMM_EVALIF_REG_SET_IMS_VOICE_TERMINATION_REQ, // for IMS
/* from MMIF */
MSG_ID_EMM_MMIF_REG_GMM_UPDATE_REGISTRATION_REQ,
MSG_ID_EMM_MMIF_REG_GMM_UPDATE_DEREGISTRATION_REQ,
MSG_ID_EMM_MMIF_REG_MM_UPDATE_REGISTRATION_REQ,
MSG_ID_EMM_MMIF_REG_MM_UPDATE_DEREGISTRATION_REQ,
MSG_ID_EMM_MMIF_REG_ISR_UPDATE_REQ,
#ifdef __SGLTE__
MSG_ID_EMM_MMIF_REG_PEER_LR_RESULT_REQ,
#endif /*__SGLTE__*/
/* from ERRCIF */
MSG_ID_EMM_ERRCIF_REG_SND_NASMSG_CNF,
MSG_ID_EMM_ERRCIF_REG_IMSI_PAGE_IND,
/* from EVTCTRL */
MSG_ID_EMM_EVTCTRL_REG_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_REG_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_REG_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_REG_CONTINUE_REQ,
MSG_ID_EMM_EVTCTRL_REG_WDT_POLLING_REQ,
/* from NASMSG */
MSG_ID_EMM_NASMSG_REG_RCV_ATTACH_ACCEPT_IND,
MSG_ID_EMM_NASMSG_REG_RCV_ATTACH_REJECT_IND,
MSG_ID_EMM_NASMSG_REG_RCV_TAU_ACCEPT_IND,
MSG_ID_EMM_NASMSG_REG_RCV_TAU_REJECT_IND,
MSG_ID_EMM_NASMSG_REG_RCV_DETACH_REQUEST_IND,
MSG_ID_EMM_NASMSG_REG_RCV_DETACH_ACCEPT_IND,
MSG_ID_EMM_RATCHG_REG_RAT_LTESBY_IND,
MSG_ID_EMM_RATCHG_REG_IRAT_UG2E_IND,
MSG_ID_EMM_RATCHG_REG_ISR_RESUME_IND,
MSG_ID_EMM_RATCHG_REG_IRAT_E2UG_FAIL_IND,
MSG_ID_EMM_RATCHG_REG_REDIR_E2UG_FAIL_IND,
MSG_ID_EMM_RATCHG_REG_IRAT_UG2E_FAIL_IND,
MSG_ID_EMM_RATCHG_REG_IRAT_E2UG_INIT_IND,
/* from SEC */
MSG_ID_EMM_SEC_REG_REG_REINIT_REQ,
MSG_ID_EMM_SEC_REG_ATTACH_TRIGGER_IND,
MSG_ID_EMM_SEC_REG_RCV_AUTH_REJECT_IND,
/* from TIMERIF */
MSG_ID_EMM_TIMERIF_REG_T3402_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3411_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3412_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3430_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3410_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3421_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T_DETACH_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_REG_T3423_TIMEOUT_IND,
/* from SV */
MSG_ID_EMM_SV_REG_SIM_READY_IND,
MSG_ID_EMM_SV_REG_DETACH_REQ,
MSG_ID_EMM_SV_REG_SIM_READY_CANCELED_IND,
/* from RATBAND */
MSG_ID_EMM_RATBAND_REG_DETACH_REQ,
/* from RATCHG */
MSG_ID_EMM_RATCHG_REG_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_REG_IRAT_UG2E_COMP_IND,
#ifdef __SGLTE__
MSG_ID_EMM_RATCHG_REG_PS_SWITCH_IND,
#endif /*__SGLTE__*/
/* for UT*/
MSG_ID_EMM_REG_UT_CONFIG_REQ,

/****************************************************************************
 *                          Destination: EMM_SEC
 ****************************************************************************/
MSG_ID_EMM_PLMNSEL_SEC_CAMPON_PLMN_CHG_IND,
MSG_ID_EMM_PLMNSEL_SEC_CELL_INFO_IND,
MSG_ID_EMM_CALL_SEC_AUTH_DATA_DEL_REQ,
MSG_ID_EMM_CALL_SEC_DELETE_KSI_REQ,
MSG_ID_EMM_REG_SEC_DELETE_KSI_REQ,
MSG_ID_EMM_REG_SEC_AUTH_DATA_DEL_REQ,
MSG_ID_EMM_REG_SEC_REG_INIT_IND,
MSG_ID_EMM_REG_SEC_DEREG_COMP_IND,
MSG_ID_EMM_RATCHG_SEC_RATLTESBY_IND,    // need to remove
MSG_ID_EMM_RATCHG_SEC_RAT_HO_U2E_IND,   // need to remove
MSG_ID_EMM_RATCHG_SEC_RAT_IDLE_U2E_IND, // need to remove 
MSG_ID_EMM_RATCHG_SEC_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_SEC_RAT_IDLE_UG2E_COMP_IND,
MSG_ID_EMM_RATCHG_SEC_RAT_HO_U2E_COMP_IND,
MSG_ID_EMM_RATCHG_SEC_RAT_HO_U2E_FAIL_IND,
MSG_ID_EMM_RATCHG_SEC_WRAP_AROUND_IND,
MSG_ID_EMM_CONN_SEC_REL_IND,
MSG_ID_EMM_CONN_SEC_EST_IND,
MSG_ID_EMM_EVALIF_SEC_AUTHENTICATE_RSP,
MSG_ID_EMM_NASMSG_SEC_RCV_AUTH_REQ_IND,
MSG_ID_EMM_NASMSG_SEC_RCV_AUTH_REJ_IND,
MSG_ID_EMM_NASMSG_SEC_RCV_SECURITY_CMD_IND,
MSG_ID_EMM_NASMSG_SEC_WRAP_AROUND_IND,
MSG_ID_EMM_NASMSG_SEC_EXCHG_REEST_REQ,
MSG_ID_EMM_ERRCIF_SEC_SND_NASMSG_CNF,
MSG_ID_EMM_ERRCIF_SEC_RCV_EPSBEARER_IND,
MSG_ID_EMM_ESMIF_SEC_ENTER_EMC_ATTACH_RSP, // for IMS
MSG_ID_EMM_TIMERIF_SEC_T3416_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_SEC_T3418_TIMEOUT_IND,
MSG_ID_EMM_TIMERIF_SEC_T3420_TIMEOUT_IND,
MSG_ID_EMM_SV_SEC_SIM_READY_IND,
MSG_ID_EMM_SV_SEC_SIM_DETACH_IND,
MSG_ID_EMM_SV_SEC_DELETE_KSI_REQ,
MSG_ID_EMM_ANY_SEC_UT_CONFIG_REQ,

/****************************************************************************
 *                          Destination: EMM_SV
 ****************************************************************************/
MSG_ID_EMM_EVALIF_SV_INIT_REQ,
MSG_ID_EMM_EVALIF_SV_SIM_READY_REQ,
MSG_ID_EMM_EVALIF_SV_SIM_ERROR_REQ,
MSG_ID_EMM_EVALIF_SV_DETACH_REQ,
MSG_ID_EMM_EVALIF_SV_SIM_FILE_UPDATE_REQ,
MSG_ID_EMM_ERRCIF_SV_ACTIVATION_CNF,
MSG_ID_EMM_REG_SV_SIM_INVALID_IND,
MSG_ID_EMM_REG_SV_DETACH_CNF,
MSG_ID_EMM_CALL_SV_SIM_INVALID_IND,
MSG_ID_EMM_SEC_SV_SIM_INVALID_IND,
MSG_ID_EMM_EVTCTRL_SV_ABORT_REQ,
MSG_ID_EMM_EVTCTRL_SV_SUSPEND_REQ,
MSG_ID_EMM_EVTCTRL_SV_RESUME_REQ,
MSG_ID_EMM_EVTCTRL_SV_CONTINUE_REQ,
MSG_ID_EMM_EVTCTRL_SV_WDT_POLLING_REQ,
MSG_ID_EMM_ANY_SV_UT_CONFIG_REQ,
MSG_ID_EMM_SV_UT_STATUS_IND,
MSG_ID_EMM_RATBAND_SV_SET_RAT_MODE_IND,

/****************************************************************************
 *                          Destination: EMM_TIMERIF
 ****************************************************************************/
MSG_ID_EMM_RATCHG_TIMERIF_IRAT_E2UG_INIT_IND,
MSG_ID_EMM_RATCHG_TIMERIF_IRAT_E2UG_COMP_IND,
MSG_ID_EMM_RATCHG_TIMERIF_IRAT_E2UG_FAIL_IND,
MSG_ID_EMM_SV_TIMERIF_POWER_DOWN_IND,
/* For TimerSrv/TimerIf UT */
MSG_ID_EMM_TIMERSRV_UT_REQ,

/* Special Usage: Set current test mode for EMM */
MSG_ID_EMM_MOD_GLOBAL_VAR_REQ,

/* Engineer Mode Config Message */
MSG_ID_EMM_EM_CONFIG_REQ,

MSG_ID_EMM_CODE_END,

MODULE_MSG_END( MSG_ID_EMM_CODE_TAIL )

#endif /* _EMM_SAP_H */

