/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   errc_msgid.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *   LTE Layer 1 and Protocol Stack related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * Merging
 *  	
 * 	//MOLY_CBr/peter.chien/MOLY_CBr/mcu/interface/sap/md/errc_msgid.h
 *  	
 * 	to //MOLY/BRANCHES_LR9/LR9.W1423.MD.LWTG.MP/mcu/interface/sap/md/errc_msgid.h
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * specific measurement sap
 *
 * removed!
 * removed!
 * ERRC Check in - 0514 - OA
 *
 * removed!
 * removed!
 * New interface:
 * MSG_ID_GAS_EAS_BACKGROUND_SEARCH_START_REQ
 * MSG_ID_GAS_EAS_BACKGROUND_SEARCH_STOP_REQ
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * 	Check in ECID ERRC modifications (OA domain)
 *
 * removed!
 * removed!
 * Add PLMN SEARCH Abort Interface:
 * 1.MSG_ID_EVAL_ERRC_PLMN_SEARCH_ABORT_REQ
 * 2.MSG_ID_NWSEL_EVAL_PLMN_SEARCH_ABORT_REQ
 *
 * removed!
 * removed!
 * Merging
 *  	
 * 	//MOLY_CBr/cookie.chen/MOLY_W14.09.LTE.p1/mcu/interface/sap/md/errc_msgid.h
 *  	
 * 	to //MOLY/TRUNK/MOLY/mcu/interface/sap/md/errc_msgid.h
 *
 * removed!
 * removed!
 * reaname ERRC_ERLCUL_STATUS_IND to ERRC_ERLC_RLF_IND
 *
 * removed!
 * removed!
 * . Check-in Interface part of LTE GEMINI
 *
 * removed!
 * removed!
 * Add ERRC Interface.
 *
 * removed!
 * removed!
 * Add Stored cell info related NVRAM context
 *
 * removed!
 * removed!
 * 	add nvram file for learned mcc info
 *
 * 11 13 2013 jed.lee
 * removed!
 * B3&B39 conn part.
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * remove leave_4g.
 *
 * removed!
 * removed!
 * inject message(new message:MSG_ID_ERRC_CEL_INJECT_LEAVE_LTE_IND)
 *
 * removed!
 * removed!
 * .Add interface
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * merge GAS_EAS_EARFCN_LIST_UPDATE_REQ
 *
 * removed!
 * removed!
 * Add ERRC_EMAC_TA_INFO_INVALID_IND
 *
 * removed!
 * removed!
 * TA_INFO and NBR_CELL_INFO interfaces for LPP feature
 *
 * 05 27 2013 jed.lee
 * removed!
 * .
 *
 * removed!
 * removed!
 * merge mrs
 *
 * removed!
 * removed!
 * .asn1 replacement
 *
 * removed!
 * removed!
 * .Merge from MM preIT CBr
 *
 * removed!
 * removed!
 * LTE multimode merge back to moly
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _ERRC_MSGID_H
#define _ERRC_MSGID_H


MODULE_MSG_BEGIN( MSG_ID_ERRC_CODE_BEGIN )


MSG_ID_EXEVT_RCV_BEGIN = MSG_ID_ERRC_CODE_BEGIN,
MSG_ID_EMM_ERRC_ACTIVATION_REQ,
MSG_ID_EMM_ERRC_RAT_BAND_REQ,
MSG_ID_EMM_ERRC_ESTABLISH_REQ,
MSG_ID_EMM_ERRC_RELEASE_REQ,
MSG_ID_EMM_ERRC_RELEASE_RSP,
MSG_ID_EMM_ERRC_DATA_REQ,
MSG_ID_EMM_ERRC_KEY_UPDATE_REQ,
MSG_ID_EMM_ERRC_TEST_REQ,
MSG_ID_EMM_ERRC_CELLSELECT_REQ,
MSG_ID_EMM_ERRC_PLMNLIST_REQ,
MSG_ID_EMM_ERRC_RESUME_REQ,
MSG_ID_EMM_ERRC_NWSEL_STATUS_UPDATE_REQ,
MSG_ID_EMM_ERRC_REG_STATUS_UPDATE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_RSP,
MSG_ID_EMM_ERRC_STANDBY_REQ,
MSG_ID_EMM_ERRC_PARAM_UPDATE_REQ,
MSG_ID_EMM_ERRC_QOS_UPDATE_REQ,
MSG_ID_EMM_ERRC_CSG_LIST_REQ,
MSG_ID_EMM_ERRC_CSG_LIST_STOP_REQ,
MSG_ID_EMM_ERRC_NULL_SECURITY_ACCEPT_REQ,
MSG_ID_EMM_ERRC_CSG_WHITE_LIST_UPDT_REQ,
MSG_ID_EMM_ERRC_SIM_FILE_UPDATE_REQ,
MSG_ID_EMM_ERRC_CSFB_NTF,
MSG_ID_EMM_ERRC_GEMINI_CSFB_STATUS_REQ,
MSG_ID_EMM_ERRC_CHECK_SERVING_SUITABILITY_REQ,
MSG_ID_EMM_ERRC_SEARCH_PREFERENCE_UPDATE_REQ,
MSG_ID_EMM_ERRC_RAT_CHANGE_CAUSE_UPDATE_REQ,
MSG_ID_EMM_ERRC_GEMINI_LR_REQ,
MSG_ID_EVAL_ERRC_ADJUST_MEAS_REQ,
MSG_ID_EVAL_ERRC_ETWS_SETTING_REQ,
MSG_ID_EVAL_ERRC_CBCH_REQ,
MSG_ID_EVAL_ERRC_CB_UPDATE_REQ,
MSG_ID_EVAL_ERRC_HPLMN_INFO_UPDATE_REQ,
MSG_ID_EVAL_ERRC_MMDC_MODE_UPDATE_REQ,
MSG_ID_EVAL_ERRC_LTE_NEIGHBOR_CELL_INFO_REQ,
MSG_ID_EVAL_ERRC_NBR_CELL_INFO_START_REQ,
MSG_ID_EVAL_ERRC_NBR_CELL_INFO_STOP_REQ,
MSG_ID_EVAL_ERRC_GET_SSAC_PARAM_REQ,
MSG_ID_EVAL_ERRC_VDM_VOICE_STATUS_REQ,
MSG_ID_EVAL_ERRC_PLMN_SEARCH_ABORT_REQ,
MSG_ID_EVAL_ERRC_CB_MSG_REMOVAL_REQ,
MSG_ID_ERRC_SIM_PROTECT_REQ,
MSG_ID_SAT_EAS_NMR_REQ,
MSG_ID_ERRC_EL1_SET_RAT_CNF,
MSG_ID_ERRC_EL1_CARRIER_SEARCH_CNF,
MSG_ID_ERRC_EL1_CARRIER_SEARCH_IND,
MSG_ID_ERRC_EL1_SPECIFIC_MEASURE_IND,
MSG_ID_ERRC_EL1_RADIO_MEASURE_CNF,
MSG_ID_ERRC_EL1_RADIO_MEASURE_IND,
MSG_ID_ERRC_EL1_CPHY_CFG_CNF,
MSG_ID_ERRC_EL1_RL_MONITOR_CNF,
MSG_ID_ERRC_EL1_RLF_IND,
MSG_ID_ERRC_EL1_BCCH_IND,
MSG_ID_ERRC_EL1_NBR_BCCH_MEAS_IND,
MSG_ID_ERRC_EL1_SPECIFIC_CELL_SEARCH_CNF,
MSG_ID_ERRC_CEL_SPECIFIC_CELL_SRCH_CNF,
MSG_ID_ERRC_CONN_SPECIFIC_CELL_SRCH_CNF,
MSG_ID_ERRC_EL1_SPECIFIC_CELL_SEARCH_IND,
MSG_ID_ERRC_CEL_SPECIFIC_CELL_SRCH_IND,
MSG_ID_ERRC_CONN_SPECIFIC_CELL_SRCH_IND,
MSG_ID_ERRC_EL1_RSSI_SNIFFER_CNF,
MSG_ID_ERRC_EL1_RSSI_SNIFFER_IND,
MSG_ID_ERRC_EL1_PCH_CRCNG_IND,
MSG_ID_ERRC_EL1_AUTO_GAP_ON_CNF,
MSG_ID_ERRC_EL1_AUTO_GAP_OFF_CNF,
MSG_ID_ERRC_EL1_ACTIVE_AFC_IND,
MSG_ID_ERRC_EMAC_CONTENTION_IND,
MSG_ID_ERRC_EMAC_RA_ERROR_IND,
MSG_ID_ERRC_CONN_RRC_TRIGER_RAERR,
MSG_ID_ERRC_EVTH_CHM_NON_RRC_TRIGER_RAERR,
MSG_ID_ERRC_EMAC_CONFIG_CNF,
MSG_ID_ERRC_EMAC_L1_UL_REL_IND,
MSG_ID_ERRC_EMAC_RA_INFO_IND,
MSG_ID_ERRC_EMAC_SI_IND,
MSG_ID_ERRC_EMAC_TA_INFO_CNF,
MSG_ID_ERRC_EMAC_TA_INFO_IND,
MSG_ID_ERRC_EMAC_TA_INFO_INVALID_IND,
MSG_ID_LPP_ERRC_ECID_MEAS_REQ,
MSG_ID_LPP_ERRC_ECID_MEAS_ABORT_REQ,
MSG_ID_ERRC_EVTH_SYS_SI,
MSG_ID_ERRC_EVTH_SYS_SIB1,
MSG_ID_ERRC_EVTH_SYS_BCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_SYS_BCCH_UNDEFINE,
MSG_ID_ERRC_EMAC_PAGING_IND,
MSG_ID_ERRC_EVTH_CEL_PAGING,
MSG_ID_ERRC_EVTH_CEL_PCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CEL_PCCH_UNDEFINE,
MSG_ID_ERRC_EMAC_CCCH_DATA_IND,
MSG_ID_ERRC_EVTH_CONN_CONN_REEST,
MSG_ID_ERRC_EVTH_CONN_CONN_REEST_REJ,
MSG_ID_ERRC_EVTH_CONN_CONN_REJ,
MSG_ID_ERRC_EVTH_CONN_CONN_SETUP,
MSG_ID_ERRC_EVTH_CONN_CCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_CCCH_UNDEFINE,
MSG_ID_ERRC_ERLCUL_CONFIG_CNF,
MSG_ID_ERRC_ERLCDL_CONFIG_CNF,
MSG_ID_ERRC_ERLC_RLF_IND,
MSG_ID_ERRC_ERLCUL_SRB1_ACK_CNF,
MSG_ID_ERRC_EPDCP_CONFIG_CNF,
MSG_ID_ERRC_EPDCP_DCCH_DATA_CNF,
MSG_ID_ERRC_EPDCP_RLC_ACK_IND,
MSG_ID_ERRC_EPDCP_DCCH_DATA_IND,
MSG_ID_ERRC_EVTH_CONN_DL_INFO_TRANS,
MSG_ID_ERRC_EVTH_CONN_MOB_FROM_EUTRA_CMD,
MSG_ID_ERRC_EVTH_CONN_CONN_RECONF,
MSG_ID_ERRC_EVTH_CONN_CONN_REL,
MSG_ID_ERRC_EVTH_CONN_SECURITY_MODE_CMD,
MSG_ID_ERRC_EVTH_RCM_UE_CAPA_ENQ,
MSG_ID_ERRC_EVTH_CONN_COUNTER_CHECK,
MSG_ID_ERRC_EVTH_CONN_UE_INFO_REQ,
MSG_ID_ERRC_EVTH_CONN_DCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_IRAT_DCCH_ASN1_DEC_ERR,
MSG_ID_ERRC_EVTH_CONN_DCCH_INTG_CHK_ERR,
MSG_ID_ERRC_EVTH_CONN_DCCH_UNDEFINE,
MSG_ID_ERRC_EPDCP_TEST_CNF,
MSG_ID_ERRC_EPDCP_CNTINFO_CNF,
MSG_ID_ERRC_TIMER_TRIG_TIMEOUT_REQ,
MSG_ID_ERRC_EVTH_RCM_CSG_WHITE_LIST_UPDATE_IND,
MSG_ID_ERRC_EVTH_RCM_NVRAM_READ_CNF,
MSG_ID_ERRC_EVTH_RCM_NVRAM_WRITE_CNF,
MSG_ID_ERRC_EVTH_RCM_BAND_UPDATE_IND,
MSG_ID_ERRC_EVTH_CEL_LOWER_LAYER_AVAILABILITY_UPDATE_IND,
MSG_ID_ERRC_EVTH_RCM_DISABLE_B39_IND,
MSG_ID_ERRC_EVTH_RCM_ENABLE_B39_IND,
MSG_ID_UAS_EAS_HANDOVER_ECELL_REQ,
MSG_ID_ERRC_EVTH_CONN_IRAT_RECONF,
MSG_ID_UAS_EAS_ABORT_HO_ECELL_REQ,
MSG_ID_MRS_EAS_UMTS_HO_INFO_IND,
MSG_ID_EAS_UAS_HANDOVER_UCELL_CNF,
MSG_ID_EAS_GAS_HANDOVER_GCELL_CNF,
MSG_ID_EAS_UAS_HO_ACTIVATE_UCELL_CNF,
MSG_ID_EAS_GAS_HO_ACTIVATE_GCELL_CNF,
MSG_ID_GAS_EAS_EVALUATE_ECELL_REQ,
MSG_ID_UAS_EAS_EVALUATE_ECELL_REQ,
MSG_ID_GAS_EAS_EVALUATE_ECELL_STOP_REQ,
MSG_ID_UAS_EAS_EVALUATE_ECELL_STOP_REQ,
MSG_ID_EAS_GAS_EVALUATE_GCELL_CNF,
MSG_ID_EAS_UAS_EVALUATE_UCELL_CNF,
MSG_ID_EAS_GAS_EVALUATE_GCELL_STOP_CNF,
MSG_ID_EAS_UAS_EVALUATE_UCELL_STOP_CNF,
MSG_ID_EAS_GAS_ACTIVATE_GCELL_CNF,
MSG_ID_EAS_UAS_ACTIVATE_UCELL_CNF,
MSG_ID_GAS_EAS_READY_TIMER_STATUS_IND,
MSG_ID_GAS_EAS_EVALUATE_CSG_ECELL_REQ,
MSG_ID_UAS_EAS_EVALUATE_CSG_ECELL_REQ,
MSG_ID_GAS_EAS_SEARCH_CSG_ECELL_REQ,
MSG_ID_UAS_EAS_SEARCH_CSG_ECELL_REQ,
MSG_ID_EAS_UAS_EVALUATE_CSG_UCELL_CNF,
MSG_ID_EAS_UAS_SEARCH_CSG_UCELL_CNF,
MSG_ID_UAS_EAS_LTE_MEASUREMENT_REQ,
MSG_ID_GAS_EAS_LTE_MEASUREMENT_REQ,
MSG_ID_UAS_EAS_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_GAS_EAS_LTE_HPS_QUALIFY_CELL_IND,
MSG_ID_EAS_UAS_CONFIG_UCELL_MEAS_CNF,
MSG_ID_EAS_GAS_CONFIG_GCELL_MEAS_CNF,
MSG_ID_EAS_UAS_CONFIG_UCELL_PRIO_MEAS_CNF,
MSG_ID_EAS_GAS_CONFIG_GCELL_PRIO_MEAS_CNF,
MSG_ID_EAS_UAS_UCELL_MEAS_IND,
MSG_ID_EAS_GAS_GCELL_MEAS_IND,
MSG_ID_EAS_GAS_GCELL_BSIC_IND,
MSG_ID_EAS_UAS_REPORT_CGI_CNF,
MSG_ID_EAS_GAS_REPORT_CGI_CNF,
MSG_ID_UAS_EAS_BACKGROUND_SEARCH_START_REQ,
MSG_ID_UAS_EAS_BACKGROUND_SEARCH_STOP_REQ,
MSG_ID_GAS_EAS_BACKGROUND_SEARCH_START_REQ,
MSG_ID_GAS_EAS_BACKGROUND_SEARCH_STOP_REQ,
MSG_ID_GAS_EAS_EARFCN_LIST_UPDATE_REQ,
MSG_ID_RSVAS_EAS_SERVICE_RES_OCCUPY_IND,
MSG_ID_RSVAS_EAS_SUSPEND_SERVICE_REQ,
MSG_ID_RSVAS_EAS_RESUME_SERVICE_REQ,
MSG_ID_RSVAS_EAS_ABORT_SERVICE_REQ,
MSG_ID_RSVAS_EAS_ABORT_SERVICE_COMPLETE_IND,
MSG_ID_RSVAS_EAS_VIRTUAL_SUSPEND_SERVICE_REQ,
MSG_ID_RSVAS_EAS_VIRTUAL_SUSPEND_SERVICE_COMPLETE_IND,
MSG_ID_RSVAS_EAS_VIRTUAL_RESUME_SERVICE_REQ,
MSG_ID_RSVAE_EAS_FREQUENCY_SCAN_ACCEPT_IND,
MSG_ID_RSVAE_EAS_FREQUENCY_SCAN_PREEMPT_IND,
MSG_ID_EXEVT_RCV_END,
MSG_ID_INEVT_BEGIN,
MSG_ID_ERRC_SPV_RCM_INIT_REQ,
MSG_ID_ERRC_SPV_RCM_INIT_CNF,
MSG_ID_ERRC_SPV_RCM_RAT_BAND_REQ,
MSG_ID_ERRC_SPV_RCM_RAT_BAND_CNF,
MSG_ID_ERRC_SPV_RCM_USIM_REQ,
MSG_ID_ERRC_SPV_RCM_USIM_CNF,
MSG_ID_ERRC_ANY_RCM_CONTEXT_WRITE_IND,
MSG_ID_ERRC_ANY_SPV_CHANGE_STATE_REQ,
MSG_ID_ERRC_ANY_SPV_CHANGE_STATE_CNF,
MSG_ID_ERRC_SPV_RCM_PARAM_REQ,
MSG_ID_ERRC_SPV_RCM_PARAM_CNF,
MSG_ID_ERRC_SPV_CEL_PARAM_REQ,
MSG_ID_ERRC_SPV_CEL_PARAM_CNF,
MSG_ID_ERRC_SPV_CONN_KEY_UPDT_REQ,
MSG_ID_ERRC_SPV_CONN_KEY_UPDT_CNF,
MSG_ID_ERRC_SPV_CONN_STATUS_UPDATE_REQ,
MSG_ID_ERRC_SPV_ANY_STBY_REQ,
MSG_ID_ERRC_SPV_ANY_STBY_CNF,
MSG_ID_ERRC_SPV_ANY_STANDBY_CMPL_IND,
MSG_ID_ERRC_SPV_ANY_RAT_CHANGE_REQ,
MSG_ID_ERRC_SPV_ANY_RAT_CHANGE_CNF,
MSG_ID_ERRC_ANY_SPV_RAT_CHANGE_IND,
MSG_ID_ERRC_ANY_SPV_RAT_CHANGE_RES,
MSG_ID_ERRC_SPV_ANY_FLIGHT_MODE_REQ,
MSG_ID_ERRC_SPV_ANY_FLIGHT_MODE_CNF,
MSG_ID_ERRC_SPV_ANY_IRTOLTE_SUCCESS_IND,
MSG_ID_ERRC_SPV_CONN_SERVICE_RES_OCCUPY_IND,
MSG_ID_ERRC_SPV_ANY_GEMINI_SUSPEND_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_SUSPEND_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_RESUME_REQ,
MSG_ID_ERRC_SPV_CEL_GEMINI_VIRTUAL_SUSPEND_REQ,
MSG_ID_ERRC_SPV_CEL_GEMINI_VIRTUAL_SUSPEND_CNF,
MSG_ID_ERRC_SPV_CEL_GEMINI_VIRTUAL_RESUME_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_REQ,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_CNF,
MSG_ID_ERRC_SPV_ANY_GEMINI_ABORT_COMPLETE_IND,
MSG_ID_ERRC_CEL_SYS_BCCH_ACT_REQ,
MSG_ID_ERRC_CEL_SYS_BCCH_ACT_CNF,
MSG_ID_ERRC_CEL_SYS_BCCH_DEACT_IND,
MSG_ID_ERRC_SYS_CEL_BCCH_RCVD_IND,
MSG_ID_ERRC_CEL_SYS_DB_UPDT_IND,
MSG_ID_ERRC_CEL_SYS_SOFT_IDX_CHG_IND,
MSG_ID_ERRC_CEL_SYS_PWS_ACT_IND,
MSG_ID_ERRC_CEL_SYS_PWS_DEACT_IND,
MSG_ID_ERRC_SYS_CEL_PWS_RCVD_IND,
MSG_ID_ERRC_SYS_CEL_BCCH_EXPR_IND,
MSG_ID_ERRC_CEL_CONN_IDLE_IND,
MSG_ID_ERRC_CONN_CEL_RRC_CONNECTED_REQ,
MSG_ID_ERRC_CONN_CEL_RRC_CONNECTED_CNF,
MSG_ID_ERRC_CONN_CEL_IDLE_REQ,
MSG_ID_ERRC_CEL_CONN_CH_STATUS_IND,
MSG_ID_ERRC_CONN_CEL_REEST_REQ,
MSG_ID_ERRC_CONN_CEL_REEST_CNF,
MSG_ID_ERRC_CONN_CEL_HO_UPDATE_CELL_IND,
MSG_ID_ERRC_CEL_CONN_UPDT_MIB_IND,
MSG_ID_ERRC_CEL_CONN_UPDT_SIB_IND,
MSG_ID_ERRC_CONN_CEL_CNCT_NG_IND,
MSG_ID_ERRC_CEL_CONN_CELL_NO_SUITABLE_IND,
MSG_ID_ERRC_CONN_CEL_REEST_CMPL_REQ,
MSG_ID_ERRC_CONN_CEL_REEST_CMPL_CNF,
MSG_ID_ERRC_CONN_CEL_EST_JDG_REQ,
MSG_ID_ERRC_CONN_CEL_EST_JDG_CNF,
MSG_ID_ERRC_CONN_CEL_CCO_RESULT_IND,
MSG_ID_ERRC_CEL_CONN_IRCCO_ABORT_EST_IND,
MSG_ID_ERRC_CEL_MOB_KCELLS_REQ,
MSG_ID_ERRC_CEL_MOB_KCELLS_CNF,
MSG_ID_ERRC_MOB_CEL_RESEL_IND,
MSG_ID_ERRC_MOB_CEL_OOS_IND,
MSG_ID_ERRC_CEL_MOB_CELL_REJ_IND,
MSG_ID_ERRC_CEL_MOB_CELL_RJCT_CLR_IND,
MSG_ID_ERRC_MOB_CEL_REST_LIST_IND,
MSG_ID_ERRC_CEL_MOB_UPDATE_CAUSE_IND,
MSG_ID_ERRC_RCM_MOB_USIM_IND,
MSG_ID_ERRC_MOB_CEL_SI_MEAS_IND,
MSG_ID_ERRC_ANY_MOB_MEAS_PRE_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_MEAS_PRE_CTRL_CNF,
MSG_ID_ERRC_ANY_MOB_MEAS_POST_CTRL_REQ,
MSG_ID_ERRC_ANY_MOB_MEAS_POST_CTRL_CNF,
MSG_ID_ERRC_CEL_MOB_MEAS_REQ,
MSG_ID_ERRC_CEL_MOB_MEAS_CNF,
MSG_ID_ERRC_MOB_CEL_RPT_CGI_REQ,
MSG_ID_ERRC_MOB_CEL_RPT_CGI_CNF,
MSG_ID_ERRC_CEL_MOB_CSG_STATUS_IND,
MSG_ID_ERRC_CEL_MOB_EMERGENCY_STATUS_IND,
MSG_ID_ERRC_CEL_MOB_IR_MEAS_CTRL_REQ,
MSG_ID_ERRC_CEL_MOB_IR_REDIRECT_TO_LTE_IND,
MSG_ID_ERRC_ANY_CHM_CH_CTRL_REQ,
MSG_ID_ERRC_ANY_CHM_CH_CTRL_CNF,
MSG_ID_ERRC_CHM_CONN_L1_CTRLING_IND,
MSG_ID_ERRC_CHM_CONN_RLF_IND,
MSG_ID_ERRC_CHM_SYS_BCCH_DL_SYNC_FAIL_IND,
MSG_ID_ERRC_CONN_CHM_LPBK_REQ,
MSG_ID_ERRC_CONN_CHM_LPBK_CNF,
MSG_ID_ERRC_CONN_ANY_SUS_REQ,
MSG_ID_ERRC_CONN_ANY_SUS_CNF,
MSG_ID_ERRC_CONN_ANY_RSM_REQ,
MSG_ID_ERRC_CONN_ANY_RSM_CNF,
MSG_ID_ERRC_ANY_CONN_REEST_IND,
MSG_ID_ERRC_TIMER_EXPR_IND,
MSG_ID_ERRC_TIMER_START_IND,
MSG_ID_ERRC_TIMER_STOP_IND,
MSG_ID_ERRC_RCM_CONN_PWS_CAPA_UPDT_IND,
MSG_ID_ERRC_RCM_ANY_CSG_WHITELIST_UPDATE_IND,
MSG_ID_ERRC_RCM_ANY_ACC_UPDATE_IND,
MSG_ID_ERRC_RCM_ANY_DISABLE_B39_IND,
MSG_ID_ERRC_RCM_ANY_ENABLE_B39_IND,
MSG_ID_ERRC_MOD_GLOBAL_VAR,
MSG_ID_ERRC_GET_VAR_ADDR,
MSG_ID_ERRC_RETURN_VAR_ADDR,
MSG_ID_ERRC_BCCH_SIB_PTR,
MSG_ID_ERRC_MIB_DATA,
MSG_ID_ERRC_SIB1_DATA,
MSG_ID_ERRC_SIB2_DATA,
MSG_ID_ERRC_SIB3_DATA,
MSG_ID_ERRC_SIB4_DATA,
MSG_ID_ERRC_SIB4_CSG_DATA,
MSG_ID_ERRC_SIB5_DATA,
MSG_ID_ERRC_SIB6_DATA,
MSG_ID_ERRC_SIB7_DATA,
MSG_ID_ERRC_SIB8_DATA,
MSG_ID_ERRC_SIB9_DATA,
MSG_ID_ERRC_SIB10_DATA,
MSG_ID_ERRC_SIB11_DATA,
MSG_ID_ERRC_SIB12_DATA,
MSG_ID_ERRC_SYS_STS_TBL,
MSG_ID_ERRC_SYS_BCCH_TBL_CTRL_INF,
MSG_ID_ERRC_SYS_PWS_RECEPTION_TBL,
MSG_ID_ERRC_SYS_STORED_INF,
MSG_ID_ERRC_SYS_DLIST_HEAD_INF,
MSG_ID_ERRC_NVM_TBL,
MSG_ID_ERRC_SIM_INFO,
MSG_ID_ERRC_UE_CAPA_MNG_TBL,
MSG_ID_ERRC_PWS_SETTING_TBL,
MSG_ID_ERRC_SPV_TBL,
MSG_ID_ERRC_CHM_CTRL_TBL,
MSG_ID_ERRC_CHM_L1_TABLE,
MSG_ID_ERRC_CHM_L2_TABLE,
MSG_ID_ERRC_FINGERPRINT_RECORD,
MSG_ID_ERRC_LEARNED_MCC_RECORD,
MSG_ID_ERRC_STORED_CELL_INF,
MSG_ID_ERRC_STORED_CARR_DATA,
MSG_ID_ERRC_RCM_TEST,
MSG_ID_ERRC_MRS_API_RESULT,
MSG_ID_ERRC_CHM_API_RESULT,
MSG_ID_ERRC_CONN_LEAVE_CONNECTED_MODE_IND,
MSG_ID_ERRC_MOB_CONN_FAKE_IRCCO_GCELL_IND,
MSG_ID_INEVT_END,

MODULE_MSG_END( MSG_ID_ERRC_CODE_TAIL )

#endif /* _ERRC_MSGID_H */
