/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2012
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   tftlib_msgid.h
 *
 * Project:
 * --------
 *   MOLY
 *
 * Description:
 * ------------
 *   TFT library related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 * ==========================================================================
 * $Log$
 *
 * removed!
 * removed!
 * Check-in TFTLIB part
 *
 * removed!
 * removed!
 * check in TFTLIB related change
 *
 * removed!
 * removed!
 * TFTLIB modification for AT+CGTFT interpretation (support both difference set & full set)
 *
 * removed!
 * removed!
 * TFTLIB part check-in
 *
 * removed!
 * removed!
 * [Joe] TFTLIB part is check in done.
 ****************************************************************************/

#ifndef TFTLIB_MSGID_H_
#define TFTLIB_MSGID_H_

#include "module_msg_range.h"

/*---------------TFTLIB_MSG_CODE_BEGIN---------------*/

MODULE_MSG_BEGIN( MSG_ID_TFTLIB_CODE_BEGIN )

MSG_ID_TFTLIB_MSG_BEGIN = MSG_ID_TFTLIB_CODE_BEGIN,

#ifdef __TFTLIB_UT__

MSG_ID_TFTLIB_TFT_DECODE,
MSG_ID_TFTLIB_TFT_ENCODE,
MSG_ID_TFTLIB_TFT_VALIDATE,
MSG_ID_TFTLIB_TFT_DIR_EXTRACT,

MSG_ID_TFTLIB_SET_APPLIED_TFT,
MSG_ID_TFTLIB_COMPOSE_TFT_TO_NW,
MSG_ID_TFTLIB_DEL_TFT,

MSG_ID_TFTLIB_GET_USER_DEFINED_TFT,
MSG_ID_TFTLIB_GET_APPLIED_TFT,
MSG_ID_TFTLIB_SET_USER_DEFINED_TFT,

MSG_ID_TFTLIB_SET_USR_DELPF,
MSG_ID_TFTLIB_GET_USR_DELPF,
MSG_ID_TFTLIB_CLEAR_USR_DELPF,

MSG_ID_TFTLIB_SET_USR_LNKPF,
MSG_ID_TFTLIB_GET_USR_LNKPF,
MSG_ID_TFTLIB_CLEAR_USR_LNKPF,

MSG_ID_TFTLIB_DEFINE_EPSB_CONTEXT,
MSG_ID_TFTLIB_ACT_EPSB_CONTEXT,

#endif // __TFTLIB_UT__


MSG_ID_TFTLIB_TFT_DECODE_EXEC_RESULT,
MSG_ID_TFTLIB_TFT_ENCODE_EXEC_RESULT,

MSG_ID_TFTLIB_SET_APPLIED_TFT_EXEC_RESULT,
MSG_ID_TFTLIB_COMPOSE_TFT_TO_NW_EXEC_RESULT,

MSG_ID_TFTLIB_CURRENT_TFT_CONTEXT_STATUS,

MSG_ID_TFTLIB_SET_USER_DEFINED_TFT_EXEC_RESULT,


/* Set TFTLIB context message id */

MSG_ID_TFTLIB_SET_MTK_AP_STATUS_REQ,


/* EM message id */

MSG_ID_TFTLIB_ENABLE_EM_INFO_REQ,

MSG_ID_EM_TFTLIB_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI5_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI6_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI7_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI8_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI9_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI10_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI11_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI12_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI13_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI14_APPLIED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI15_APPLIED_TFT_UPDATE_IND,


MSG_ID_EM_TFTLIB_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID0_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID1_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID2_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID3_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID4_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID5_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID6_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID7_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID8_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID9_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID10_USER_DEFINED_TFT_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID11_USER_DEFINED_TFT_UPDATE_IND,


MSG_ID_EM_TFTLIB_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI5_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI6_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI7_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI8_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI9_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI10_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI11_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI12_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI13_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI14_NW_ASSIGNED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_EBI15_NW_ASSIGNED_TAD_UPDATE_IND,


MSG_ID_EM_TFTLIB_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID0_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID1_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID2_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID3_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID4_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID5_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID6_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID7_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID8_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID9_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID10_UE_COMPOSED_TAD_UPDATE_IND,
MSG_ID_EM_TFTLIB_CID11_UE_COMPOSED_TAD_UPDATE_IND,



MSG_ID_TFTLIB_MSG_END,

MODULE_MSG_END( MSG_ID_TFTLIB_CODE_TAIL )


#endif /* TFTLIB_MSGID_H_ */
