/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2009
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/******************************************************************************
 * Filename:
 * --------------------------------------------------------
 *   tl1_sap.h
 *
 * Project:
 * --------------------------------------------------------
 *   
 *
 * Description:
 * --------------------------------------------------------
 *   
 *
 * Author:
 * --------------------------------------------------------
 * -------
 *
 * --------------------------------------------------------
 * $Log$
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * Check in MMDC Band3 Band39 co-exist feature.
 *
 * removed!
 * removed!
 * for ESL
 *
 * removed!
 * removed!
 * [TL1] Merge lastes WR8 + R9 + MM code to MOLY..
 *
 * removed!
 * removed!
 * EM tx test tl1 part.
 * 
 * removed!
 * removed!
 * TDD_R9_DEV patch back to MOLY
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 * (TL1 SAP)
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * 
 * removed!
 *
 * removed!
 * removed!
 * TL1 code interface fta merge in MAUI.
 *
 * removed!
 * 
 * removed!
 * <saved by Perforce>
 *
 * removed!
 * removed!
 * merge code from daily LOAD to MAUI 10A.
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * 1. Add ul_mac_event to cphy_dch_setup/modify/release_req
 * 2. Add two ticks and structs for mac-tl1 interface.
 * 3. Add two simulation structs according to MAC's requeset.
 *
 * removed!
 * removed!
 * 1.SLCE-TL1 SAP Modify for R7
 * 2. MAC-TL1 SAP Modify for UPA
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * 1.Add MSG_ID_PHY_END_EDCH_TX_IND
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 1.Add MSG_ID_CPHY_EDCH_SETUP/MODIFY/RELEASE_REQ
 *
 * removed!
 * removed!
 * 1.Delete pre-declare check of __UMTS_TDD128_MODE__
 *
 * removed!
 * removed!
 * 1.Add pre-declare check of __UMTS_TDD128_MODE__
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * Rename the msg code begin from UL1 to TL1
 *
 * removed!
 * removed!
 * Rename __UMTS_TDD128_RAT__ to __UMTS_TDD128_MODE__
 *
 * removed!
 * removed!
 * add log section for tl1interface header files
 *
*******************************************************************************/
#include "module_msg_range.h"

#ifndef _TL1_MSG_H
#define _TL1_MSG_H

#if defined(__UMTS_RAT__) && defined(__UMTS_TDD128_MODE__)
/* Request for CPHY */
#ifdef _Test_Hdr_On_PC
enum {
#endif

MODULE_MSG_BEGIN( MSG_ID_TL1_MSG_CODE_BEGIN )
/* RELEASE REQ should be put before SETUP/MODIFY REQ */
/* MSG_ID_CPHY_BCH_RELEASE_REQ to MSG_ID_CPHY_DCH_MODIFY_REQ must be continuous */
MSG_ID_TL1_MSG_CODE_REQ_BEGIN = MSG_ID_TL1_MSG_CODE_BEGIN,
MSG_ID_CPHY_BCH_RELEASE_REQ,
MSG_ID_CPHY_BCH_MODIFY_REQ,
MSG_ID_CPHY_BCH_SETUP_REQ,
MSG_ID_CPHY_PCH_RELEASE_REQ,
MSG_ID_CPHY_PCH_SETUP_REQ,
MSG_ID_CPHY_PCH_MODIFY_REQ,
MSG_ID_CPHY_FACH_RELEASE_REQ,
MSG_ID_CPHY_FACH_SETUP_REQ,
/*MSG_ID_CPHY_FACH_MODIFY_REQ,*/    /*MSG_ID_CPHY_FACH_MODIFY_REQ is not used in TDD128 */
MSG_ID_CPHY_RACH_RELEASE_REQ,
MSG_ID_CPHY_RACH_SETUP_REQ,
MSG_ID_CPHY_DCH_RELEASE_REQ,
MSG_ID_CPHY_DCH_SETUP_REQ,
MSG_ID_CPHY_DCH_MODIFY_REQ,
MSG_ID_CPHY_FREQUENCY_SCAN_REQ,
MSG_ID_CPHY_FREQUENCY_SCAN_CONTINUE_REQ,
MSG_ID_CPHY_FREQUENCY_SCAN_SUSPEND_REQ,
/*MSG_ID_CPHY_FREQUENCY_SCAN_STOP_REQ,*/  /*MSG_ID_CPHY_FREQUENCY_SCAN_STOP_REQ is not used in TDD128 */
MSG_ID_CPHY_RSSI_SNIFFER_START_REQ,          /*keep their space for future use */
MSG_ID_CPHY_RSSI_SNIFFER_STOP_REQ,          /*keep their space for future use */
MSG_ID_CPHY_MEASUREMENT_CONFIG_CELL_REQ,

MSG_ID_CPHY_MEASUREMENT_INTERNAL_CONFIG_REQ,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_STOP_REQ,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_RESULT_REQ,
MSG_ID_CPHY_SPECIFIC_CELL_SEARCH_REQ,
MSG_ID_CPHY_SPECIFIC_CELL_SEARCH_STOP_REQ,
MSG_ID_CPHY_RESET_REQ,
MSG_ID_CPHY_RF_ON_REQ,
MSG_ID_CPHY_RF_OFF_REQ,
MSG_ID_CPHY_SET_ACTIVE_RAT_REQ,

MSG_ID_CPHY_HSDSCH_SETUP_REQ,
MSG_ID_CPHY_HSDSCH_MODIFY_REQ,
MSG_ID_CPHY_HSDSCH_RELEASE_REQ,

#ifdef __HSUPA_SUPPORT__
MSG_ID_CPHY_EDCH_SETUP_REQ,
MSG_ID_CPHY_EDCH_MODIFY_REQ,
MSG_ID_CPHY_EDCH_RELEASE_REQ,
#ifdef __SIMULATION_PS_TL1_BOTH__
MSG_ID_CPHY_SIMULATE_DPA_ONLY_SUB_FRAME_ENTRY_REQ, /*By sub-frame. tl1data_ast_msgid.h has the same def for dsp resp logging.*/
MSG_ID_CPHY_SIMULATE_UPA_ONLY_SUB_FRAME_ENTRY_REQ, /*By sub-frame*/
#endif /*__SIMULATION_PS_TL1_BOTH__*/
#endif

//#if defined( __UMTS_R9__ ) && defined ( __AST3002__ )
MSG_ID_CPHY_MEASUREMENT_CONFIG_DMO_REQ,
//#endif
MSG_ID_CPHY_MEASUREMENT_CONFIG_IDLE_INTERVAL_REQ,	/*Interface for idle interval*/

MSG_ID_CPHY_MSG_CONTAINER_REQ,
MSG_ID_CPHY_ABORT_REQ,
MSG_ID_CPHY_ABORT_BCH_SETUP_REQ,

#ifdef __SGLTE__
//GSM B3 && TDS B39 Co-existence
MSG_ID_GAS_TL1_ENABLE_B39_TX_REQ,
MSG_ID_GAS_TL1_DISABLE_B39_TX_REQ,
#endif

/* Request from PHY */
MSG_ID_PHY_RACH_DATA_REQ,
#if defined( __GEMINI_GSM__ ) && defined ( __UMTS_RAT__ )  
MSG_ID_RSVAS_TL1_SUSPEND_REQ,
MSG_ID_RSVAS_TL1_RESUME_REQ,
#endif
MSG_ID_PHY_ACCESS_REQ,
MSG_ID_L4CTL1_EM_TST_CONTROL_REQ,

MSG_ID_TL1_MSG_CODE_REQ_END,

/*MSG_ID_UL1C_UL1A_UREPORT,
MSG_ID_UL1D_UL1C_UREPORT,*/

/* Confirm & Indication for CPHY */
MSG_ID_CPHY_BCH_SETUP_CNF,
MSG_ID_CPHY_BCH_SETUP_IND,
MSG_ID_CPHY_BCH_MODIFY_CNF,
MSG_ID_CPHY_BCH_MODIFY_IND,
MSG_ID_CPHY_BCH_RELEASE_CNF,
MSG_ID_CPHY_BCH_RELEASE_IND,
MSG_ID_CPHY_SFN_IND,


MSG_ID_CPHY_T312_EXPIRY_IND,
MSG_ID_CPHY_DL_INIT_SYNC_IND,
MSG_ID_CPHY_RL_FAILURE_IND,

MSG_ID_CPHY_FREQUENCY_SCAN_CNF,
MSG_ID_CPHY_FREQUENCY_SCAN_IND,
MSG_ID_CPHY_FREQUENCY_SCAN_CONTINUE_CNF,
MSG_ID_CPHY_FREQUENCY_SCAN_SUSPEND_CNF,
MSG_ID_CPHY_FREQUENCY_SCAN_SUSPEND_IND,

MSG_ID_CPHY_RSSI_SNIFFER_START_CNF, 
MSG_ID_CPHY_RSSI_SNIFFER_STOP_CNF,  
MSG_ID_CPHY_RSSI_SNIFFER_SIGNAL_APPEAR_IND,  
MSG_ID_CPHY_MEASUREMENT_CONFIG_CELL_CNF,
MSG_ID_CPHY_MEASUREMENT_CELL_IND,

MSG_ID_CPHY_MEASUREMENT_INTERNAL_CONFIG_CNF,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_EVENT_IND,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_PERIODIC_IND,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_RESULT_IND,
MSG_ID_CPHY_MEASUREMENT_INTERNAL_STOP_CNF,

MSG_ID_CPHY_SPECIFIC_CELL_SEARCH_IND,
MSG_ID_CPHY_SPECIFIC_CELL_SEARCH_STOP_IND,
MSG_ID_CPHY_RESET_CNF,
MSG_ID_CPHY_RF_ON_CNF,
MSG_ID_CPHY_RF_OFF_CNF,
MSG_ID_CPHY_SET_ACTIVE_RAT_CNF,

MSG_ID_CPHY_MSG_CONTAINER_CNF,
MSG_ID_CPHY_MSG_CONTAINER_IND,
MSG_ID_CPHY_ABORT_CNF,
MSG_ID_CPHY_TX_STATUS_IND,
#ifdef __TDD_DM_GAP_OPTIMIZATION__
MSG_ID_CPHY_GSM_GAP_STATUS_IND,
#endif
/* Confirm & Indication for PHY */
MSG_ID_PHY_PCH_SETUP_IND,
/*MSG_ID_PHY_PCH_MODIFY_IND,*/  /* MSG_ID_PHY_PCH_MODIFY_IND is not used in TDD128 */
MSG_ID_PHY_PCH_RELEASE_IND,
MSG_ID_PHY_FACH_SETUP_IND,
/*MSG_ID_PHY_FACH_MODIFY_IND,*/ /* MSG_ID_PHY_FACH_MODIFY_IND is not used in TDD128 */
MSG_ID_PHY_FACH_RELEASE_IND,
MSG_ID_PHY_RACH_SETUP_IND,
MSG_ID_PHY_RACH_RELEASE_IND,
MSG_ID_PHY_DCH_SETUP_IND,
MSG_ID_PHY_DCH_MODIFY_IND,
MSG_ID_PHY_DCH_RELEASE_IND,
MSG_ID_PHY_CONFIG_ABORT_IND,
MSG_ID_PHY_DL_INIT_SYNC_IND,
MSG_ID_PHY_BCH_DATA_IND,
MSG_ID_PHY_DATA_IND,
MSG_ID_PHY_ACCESS_IND,
MSG_ID_PHY_POST_TX_IND,
MSG_ID_PHY_END_DCH_TX_IND,
MSG_ID_PHY_HSDSCH_DATA_IND,

#ifdef __HSUPA_SUPPORT__
MSG_ID_PHY_END_EDCH_TX_IND,
#endif

MSG_ID_CPHY_MEASUREMENT_CONFIG_IDLE_INTERVAL_CNF,	/*Interface for idle interval*/

/*New-Added message for HSPA+ */
//#ifdef __TDD128_HSPA_PLUS__
/*MSG_ID_CPHY_ULSYNC_ORDER_IND,*/
MSG_ID_PHY_ERUCCH_ACCESS_IND,
MSG_ID_PHY_CEDCH_SETUP_IND,
MSG_ID_PHY_CEDCH_RELEASE_IND,
MSG_ID_PHY_CEDCH_MODIFY_IND,
MSG_ID_PHY_CEDCH_TERMINATION_IND,
MSG_ID_PHY_CEDCH_TERMINATION_REQ,
//#endif
/*New-Added message for HSPA+ */

/*========== UMAC UT SIMULATE MESSAGE   ==========*/
//#ifdef  __MNT_UT_UMAC_ALONE_WITHOUT_L1__  /* UMAC UT */
MSG_ID_PHY_SIMULATE_DCH_UL_CCTRCH_TASK, 
MSG_ID_PHY_SIMULATE_DCH_UL_CCTRCH_HISR,
MSG_ID_PHY_SIMULATE_DCH_UL_CCTRCH_HISR_RSP,

MSG_ID_PHY_SIMULATE_DCH_UL_CCTRCH_LISR,
MSG_ID_PHY_SIMULATE_DCH_UL_CCTRCH_LISR_RSP,

MSG_ID_PHY_SIMULATE_DCH_UL_CALLBACK_CCTRCH, 
MSG_ID_PHY_SIMULATE_DCH_UL_CALLBACK_CCTRCH_RSP,
MSG_ID_PHY_SIMULATE_DCH_UL_CALLBACK_POWER,
MSG_ID_PHY_SIMULATE_END_DCH_TX_IND, 

MSG_ID_PHY_SIMULATE_UMAC_UL_DCH_TICK,
MSG_ID_PHY_SIMULATE_UMAC_UL_DCH_TICK_END,
#ifdef __HSUPA_SUPPORT__
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_1,
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_1_RSP,
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_2,
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_2_RSP,
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_3,
MSG_ID_PHY_SIMULATE_UMAC_E_DCH_TICK_4,
MSG_ID_PHY_SIMULATE_INVOKE_UL_INFORM_EDCH_MAC,
//MSG_ID_PHY_SIMULATE_END_EDCH_TX_IND,
#endif
//#endif  /* __MNT_UT_UMAC_ALONE_WITHOUT_L1__ */
/*========== END UMAC UT SIMULATE MESSAGE   ==========*/

MSG_ID_CPHY_MSG_CONTAINER_REQ_UNPACK,
MSG_ID_CPHY_CHANNEL_QUALITY_STATUS_IND,
#if defined( __GEMINI_GSM__ ) && defined ( __UMTS_RAT__ )  
MSG_ID_RSVAS_TL1_SUSPEND_CNF,
#endif
#ifdef __GEMINI_MONITOR_PAGE_DURING_TRANSFER__
MSG_ID_CPHY_CHANNEL_PRIORITY_ADJUSTMENT_REQ,
MSG_ID_URR_TL1_SWITCH_GEMINI_MODE_REQ,
MSG_ID_RSVAS_TL1_VIRTUAL_RESUME_REQ,
MSG_ID_PHY_CHANNEL_PRIORITY_ADJUSTMENT_REQ,
#endif

#if 1//__TDD_TX_PWR_REDUCE__
MSG_ID_TL1_UMTS_MAX_TX_PWR_RED_REQ,
#endif

MODULE_MSG_END( MSG_ID_TL1_MSG_CODE_TAIL )

#ifdef _Test_Hdr_On_PC
};
#endif
#endif

#endif  //_TL1_MSG_H
