/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   ul2d_sap.h
 *
 * Project:
 * --------
 *   MONZA
 *
 * Description:
 * ------------
 *
 *
 * Author:
 * -------
 * -------
 *
 *===========================================================================
 * $Log:$
 *
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * 	Interface update .
 *
 * removed!
 * removed!
 * .
 * 
 * removed!
 * removed!
 * .
 * 
 * removed!
 * removed!
 * modem related option move to modem internal
 *
 * removed!
 * removed!
 * Diff PDCP&RABM MSG ID for TDD.
 *
 * removed!
 * removed!
 * <saved by Perforce>
 *
 * removed!
 * removed!
 * Differ CSR Messages between TDD & FDD.
 *
 * removed!
 * removed!
 * Differ URLC, DRLC Messages between TDD & FDD.
 *
 * removed!
 * removed!
 * 1) confirm all _msgid.h is same as old (exclude fold ../delete/);
 * 2) fix range error in module_msg_range.h.
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * Qinghua Yu check in global enum (MSG & SAP) at modem_dev.
 *
 * removed!
 * removed!
 * <saved by Perforce>
 *
 * removed!
 * removed!
 * Integration change.
 *
 * 01 20 2012 ij.liao
 * removed!
 * .
 *
 * removed!
 * removed!
 * Integration change.
 *
 * 01 13 2012 ij.liao
 * removed!
 * .
 *
 * removed!
 * removed!
 * <saved by Perforce>
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * merge MSBB.
 *
 * removed!
#include "module_msg_range.h"

MODULE_MSG_BEGIN()
 * removed!
 * Remove CCSR_RB_RELEASE_IND
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * MAUI
 *
 * removed!
 * removed!
 * .
 *
 * 01 21 2011 max.yin
 * removed!
 * .
 *
 * removed!
 * removed!
 * PS HAL UL2 SAP Header files move 
 *
 * removed!
 * removed!
 * Merge TDD128 backto MAUI, based on 10AW1032MP_ASTRO w10.48 Tue. P1
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * add to source control recursely
 *===========================================================================
 ****************************************************************************/
#include "module_msg_range.h"

#ifndef _UL2D_MSG_H
#define _UL2D_MSG_H

#ifdef __SOURCE_INSIGHT_PARSE__
typedef enum {
#endif


/* mtk80197, merge TDD128 back to MAUI */
#if defined(__UMTS_FDD_MODE__)
MODULE_MSG_BEGIN( MSG_ID_BMC_CODE_BEGIN )
/***** BMC - start *****/
/* BMC - RATCM */
MSG_ID_RATCM_BMC_CBCH_REQ = MSG_ID_BMC_CODE_BEGIN,
MSG_ID_RATCM_BMC_UPDATE_REQ,
MSG_ID_RATCM_BMC_CB_LOC_UPDATE_REQ,
MSG_ID_RATCM_BMC_CB_MSG_REMOVAL_REQ,

/* BMC - SLCE */
MSG_ID_CBMC_CONFIG_REQ,
/* BMC - DRLC */
MSG_ID_RLC_BMC_DATA_IND,
MSG_ID_BMC_CODE_END = MSG_ID_RLC_BMC_DATA_IND,
/***** BMC - end *****/
MODULE_MSG_END( MSG_ID_BMC_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_CSR_CODE_BEGIN )
//MSG_ID_CSR_CODE_BEGIN,
//UMAC
MSG_ID_CSR_UMAC_STATUS_IND = MSG_ID_CSR_CODE_BEGIN,
MSG_ID_CSR_UMAC_TFC_IND,
MSG_ID_CCSR_RAB_ESTABLISH_IND,
MSG_ID_CCSR_RAB_RELEASE_IND,
MSG_ID_CCSR_RAB_MODIFY_IND,
MSG_ID_CCSR_RB_RELEASE_IND,
MSG_ID_CSR_CODE_END = MSG_ID_CCSR_RB_RELEASE_IND,
//MSG_ID_CSR_CODE_END,
MODULE_MSG_END( MSG_ID_CSR_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_DRLC_CODE_BEGIN )
/***** DRLC - start *****/
/* DRLC - URLC */
MSG_ID_DRLC_URLC_REASSEMBLE_REQ = MSG_ID_DRLC_CODE_BEGIN,
MSG_ID_DRLC_URLC_INIT_REQ,	
MSG_ID_DRLC_URLC_DEINIT_REQ,
MSG_ID_DRLC_URLC_ENTER_PCH_REQ,

/* DRLC - RRCE */
MSG_ID_RRCE_DRLC_FLUSH_DATA_REQ,
/* DRLC - URR */
MSG_ID_URR_DRLC_SRB_SDU_CONTINUE_REQ,
/* DRLC - ADR */
MSG_ID_RLC_TM_DATA_REQ,
MSG_ID_RLC_UM_DATA_REQ,
MSG_ID_RLC_AM_DATA_REQ,
MSG_ID_DRLC_CODE_END = MSG_ID_RLC_AM_DATA_REQ,
/***** DRLC - end *****/
MODULE_MSG_END( MSG_ID_DRLC_CODE_TAIL )


MODULE_MSG_BEGIN( MSG_ID_PDCP_CODE_BEGIN )
//MSG_ID_PDCP_CODE_BEGIN,
MSG_ID_CPDCP_CONFIG_REQ = MSG_ID_PDCP_CODE_BEGIN,
MSG_ID_CPDCP_RELOC_REQ,
MSG_ID_CPDCP_RELEASE_REQ,
MSG_ID_PDCP_URLC_RESET_IND,
MSG_ID_PDCP_URLC_REESTABLISH_IND,
#ifdef UNIT_TEST
MSG_ID_PDCP_CSR_DATA_IND,
MSG_ID_PDCP_CSR_BUILDAMR_REQ,
MSG_ID_PDCP_CSR_BUILDAMR_RSP,
#endif
MSG_ID_PDCP_FLC_RESUME_UL_TRANSFER,
MSG_ID_PDCP_FLC_RESUME_DL_TRANSFER,
MSG_ID_RATDM_PDCP_RESET_STATISTICS_REQ,
MSG_ID_PDCP_CODE_END = MSG_ID_RATDM_PDCP_RESET_STATISTICS_REQ,
//MSG_ID_PDCP_CODE_END,
MODULE_MSG_END( MSG_ID_PDCP_CODE_TAIL )

MODULE_MSG_BEGIN( MSG_ID_RABM_CODE_BEGIN )
//MSG_ID_RABM_CODE_BEGIN,
/* RATDM - RABM */
MSG_ID_RATDM_RABM_ACTIVATE_REQ = MSG_ID_RABM_CODE_BEGIN,
MSG_ID_RATDM_RABM_ACTIVATE_RSP,
MSG_ID_RATDM_RABM_DEACTIVATE_REQ,
MSG_ID_RATDM_RABM_MODIFY_REQ,
MSG_ID_RATDM_RABM_REESTABLISH_RSP,
MSG_ID_RATDM_RABM_RESUME_REQ,
MSG_ID_RATDM_RABM_DATA_REQ,

MSG_ID_RATDM_RABM_REESTABLISH_RAB_READY_IND,

/* UL data path optimization: Share Uplink Queue */
MSG_ID_RATDM_SHAQ_KICK_UL2,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_0,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_1,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_2,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_3,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_4,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_5,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_6,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_7,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_8,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_9,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_10,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_11,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_12,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_13,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_14,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_15,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_16,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_17,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_18,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_19,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_20,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_21,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_22,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_23,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_24,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_25,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_26,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_27,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_28,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_29,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_30,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_31,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_32,

/* SLCE - RABM */
MSG_ID_CRABM_RAB_ESTABLISH_IND,
MSG_ID_CRABM_RAB_RELEASE_IND,

/* RRCE - RABM */
MSG_ID_CRABM_PS_RAB_CAPABILITY_IND,

MSG_ID_RABM_CODE_END = MSG_ID_CRABM_PS_RAB_CAPABILITY_IND,
//MSG_ID_RABM_CODE_END,
MODULE_MSG_END( MSG_ID_RABM_CODE_TAIL )

#endif /* __UMTS_FDD_MODE__ */

/* mtk80197, merge TDD128 back to MAUI */
#if defined(__UMTS_TDD128_MODE__)
MODULE_MSG_BEGIN( MSG_ID_BMC_TDD_CODE_BEGIN )
/***** BMC - start *****/
/* BMC - RATCM */
MSG_ID_RATCM_BMC_CBCH_REQ = MSG_ID_BMC_TDD_CODE_BEGIN,
MSG_ID_RATCM_BMC_UPDATE_REQ,
MSG_ID_RATCM_BMC_CB_LOC_UPDATE_REQ,
MSG_ID_RATCM_BMC_CB_MSG_REMOVAL_REQ,

/* BMC - SLCE */
MSG_ID_CBMC_CONFIG_REQ,
/* BMC - DRLC */
MSG_ID_RLC_BMC_DATA_IND,
MSG_ID_BMC_CODE_END = MSG_ID_RLC_BMC_DATA_IND,
/***** BMC - end *****/
MODULE_MSG_END( MSG_ID_BMC_TDD_CODE_TAIL )


MODULE_MSG_BEGIN( MSG_ID_CSR_TDD_CODE_BEGIN )
//MSG_ID_CSR_CODE_BEGIN,
//UMAC
MSG_ID_CSR_UMAC_STATUS_IND = MSG_ID_CSR_TDD_CODE_BEGIN,
MSG_ID_CSR_UMAC_TFC_IND,
MSG_ID_CCSR_RAB_ESTABLISH_IND,
MSG_ID_CCSR_RAB_RELEASE_IND,
MSG_ID_CCSR_RAB_MODIFY_IND,
MSG_ID_CCSR_RB_RELEASE_IND,
MSG_ID_CSR_CODE_END = MSG_ID_CCSR_RB_RELEASE_IND,
//MSG_ID_CSR_CODE_END,
MODULE_MSG_END( MSG_ID_CSR_TDD_CODE_TAIL )


MODULE_MSG_BEGIN( MSG_ID_DRLC_TDD_CODE_BEGIN )
/***** DRLC - start *****/
/* DRLC - URLC */
MSG_ID_DRLC_URLC_REASSEMBLE_REQ = MSG_ID_DRLC_TDD_CODE_BEGIN,
/* DRLC - RRCE */
MSG_ID_RRCE_DRLC_FLUSH_DATA_REQ,
/* DRLC - URR */
MSG_ID_URR_DRLC_SRB_SDU_CONTINUE_REQ,
/* DRLC - ADR */
MSG_ID_RLC_TM_DATA_REQ,
MSG_ID_RLC_UM_DATA_REQ,
MSG_ID_RLC_AM_DATA_REQ,
MSG_ID_DRLC_CODE_END = MSG_ID_RLC_AM_DATA_REQ,
MODULE_MSG_END( MSG_ID_DRLC_TDD_CODE_TAIL )
/***** DRLC - end *****/

MODULE_MSG_BEGIN( MSG_ID_PDCP_TDD_CODE_BEGIN )
//MSG_ID_PDCP_CODE_BEGIN,
MSG_ID_CPDCP_CONFIG_REQ = MSG_ID_PDCP_TDD_CODE_BEGIN,
MSG_ID_CPDCP_RELOC_REQ,
MSG_ID_CPDCP_RELEASE_REQ,
MSG_ID_PDCP_URLC_RESET_IND,
MSG_ID_PDCP_URLC_REESTABLISH_IND,
MSG_ID_PDCP_FLC_RESUME_UL_TRANSFER,
MSG_ID_PDCP_FLC_RESUME_DL_TRANSFER,
MSG_ID_PDCP_CODE_END = MSG_ID_PDCP_FLC_RESUME_DL_TRANSFER,
MODULE_MSG_END( MSG_ID_PDCP_TDD_CODE_TAIL )
//MSG_ID_PDCP_CODE_END,

//MSG_ID_RABM_CODE_BEGIN,
/* RATDM - RABM */
MODULE_MSG_BEGIN( MSG_ID_RABM_TDD_CODE_BEGIN )
MSG_ID_RATDM_RABM_ACTIVATE_REQ = MSG_ID_RABM_TDD_CODE_BEGIN,
MSG_ID_RATDM_RABM_ACTIVATE_RSP,
MSG_ID_RATDM_RABM_DEACTIVATE_REQ,
MSG_ID_RATDM_RABM_MODIFY_REQ,
MSG_ID_RATDM_RABM_REESTABLISH_RSP,
MSG_ID_RATDM_RABM_RESUME_REQ,
MSG_ID_RATDM_RABM_DATA_REQ,

/*RATDM - PDCP*/
MSG_ID_RATDM_PDCP_RESET_STATISTICS_REQ,

/* UL data path optimization: Share Uplink Queue */
MSG_ID_RATDM_SHAQ_KICK_UL2,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_0,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_1,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_2,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_3,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_4,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_5,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_6,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_7,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_8,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_9,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_10,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_11,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_12,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_13,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_14,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_15,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_16,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_17,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_18,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_19,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_20,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_21,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_22,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_23,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_24,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_25,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_26,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_27,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_28,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_29,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_30,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_31,
MSG_ID_REALTIME_SHAQ_KICK_URLC_PS_RBID_32,


/* SLCE - RABM */
MSG_ID_CRABM_RAB_ESTABLISH_IND,
MSG_ID_CRABM_RAB_RELEASE_IND,

/* RRCE - RABM */
MSG_ID_CRABM_PS_RAB_CAPABILITY_IND,

    
#ifdef __REL7__
    MSG_ID_RATDM_RABM_REESTABLISH_RAB_READY_IND,
#endif

MSG_ID_RABM_CODE_END,
MODULE_MSG_END( MSG_ID_RABM_TDD_CODE_TAIL )

#endif /* __UMTS_TDD128_MODE__ */

#ifdef __SOURCE_INSIGHT_PARSE__
};
#endif

#endif   //_UL2D_MSG_H
