/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2013
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 * Filename:
 * ------------
 *   vdm_msgid.h
 *
 * Project:
 * ------------
 *   MOLY
 *
 * Description:
 * ------------
 *   This file defines the identities of the messages received by VDM and the identities of
 *   VDM internal messages.
 *
 * Author:
 * -----------
 * -------
 *
 *===========================================================
 * $Log$
 *
 * removed!
 * removed!
 * VDM part
 *
 * removed!
 * removed!
 * Check in VoLTE+Gemini related interfaces for VDM, IMSP, L4C, EVAL, and ERRC
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * .
 *
 * removed!
 * removed!
 * check in VDM_VCC implementation for Rel-10 SRVCC
 *
 * removed!
 * removed!
 * +CRING
 *
 * removed!
 * removed!
 * Check in VDM code to enable IMS test mode (AUTO or IMS_ALWAYS)
 *
 * removed!
 * removed!
 * Add ads_ctrl message to VDM for Test Mode
 *
 * removed!
 * IMSP.
 *****************************************************************************/

#ifndef _VDM_MSGID_H_
#define _VDM_MSGID_H_

#include "module_msg_range.h"


MODULE_MSG_BEGIN( MSG_ID_VDM_CODE_BEGIN )

/****************************************************************************
 *                       <1> Desitnation: VDM
 ****************************************************************************/

// <1.1> From IMSP

// for VDM TRK
MSG_ID_VDM_IMSP_CMD_DIAL_IND                    = MSG_ID_VDM_CODE_BEGIN,
MSG_ID_VDM_IMSP_CMD_DIAL_URI_IND,
MSG_ID_VDM_IMSP_CMD_DIAL_EMERG_IND,
MSG_ID_VDM_IMSP_CMD_STK_CALL_IND,
MSG_ID_VDM_IMSP_CMD_MT_CALL_APPROVE_IND,
MSG_ID_VDM_IMSP_CMD_MT_CALL_ACCEPT_IND,
MSG_ID_VDM_IMSP_CMD_HANGUP_ALL_IND,
MSG_ID_VDM_IMSP_CMD_FORCE_HANGUP_IND,
MSG_ID_VDM_IMSP_CMD_CALL_RELATED_SS_IND,
MSG_ID_VDM_IMSP_CMD_DTMF_IND,
MSG_ID_VDM_IMSP_CMD_EXT_DTMF_IND,
MSG_ID_VDM_IMSP_CMD_EXT_ERROR_REPORT_IND,
MSG_ID_VDM_IMSP_CMD_LIST_CURRENT_CALLS_IND,

MSG_ID_VDM_IMSP_STK_CALL_NUM_IND,

MSG_ID_VDM_IMSP_CS_CC_MO_CALL_CNF,
MSG_ID_VDM_IMSP_CS_CC_EMERG_CALL_CNF,
MSG_ID_VDM_IMSP_CS_CC_STK_CALL_CNF,
MSG_ID_VDM_IMSP_CS_CC_MO_CALL_ID_IND,
MSG_ID_VDM_IMSP_CS_CC_MT_CALL_PRESENT_IND,
MSG_ID_VDM_IMSP_CS_CC_MT_CALL_SETUP_IND,
MSG_ID_VDM_IMSP_CS_CC_MT_CALL_ACCEPT_CNF,
MSG_ID_VDM_IMSP_CS_CC_HANGUP_ALL_CNF,
MSG_ID_VDM_IMSP_CS_CC_FORCE_HANGUP_CNF,
MSG_ID_VDM_IMSP_CS_CC_CALL_DISCONNECT_IND,
MSG_ID_VDM_IMSP_CS_CC_CALL_RELATED_SS_CNF,
MSG_ID_VDM_IMSP_CS_CC_EXT_ERROR_REPORT_CNF,
MSG_ID_VDM_IMSP_CS_CC_SEND_DIGIT_CNF,
MSG_ID_VDM_IMSP_CS_CC_START_SEND_DIGIT_CNF,
MSG_ID_VDM_IMSP_CS_CC_STOP_SEND_DIGIT_CNF,
MSG_ID_VDM_IMSP_CS_CC_LIST_CURRENT_CALLS_CNF,
MSG_ID_VDM_IMSP_CS_CC_ECPI_TRANSLATE_IND,

// for VDM ADS
MSG_ID_VDM_IMSP_FDN_ECC_CHECK_CNF,
MSG_ID_VDM_IMSP_GET_SSAC_PARAM_CNF,
MSG_ID_VDM_IMSP_IMS_VOPS_SUPP_IND,
MSG_ID_VDM_IMSP_EMB_S1_SUPP_IND,
MSG_ID_VDM_IMSP_VOICE_MODE_IND,
MSG_ID_VDM_IMSP_EUTRAN_VDP_IND,
MSG_ID_VDM_IMSP_UE_MODE_IND,
MSG_ID_VDM_IMSP_NAS_REG_STATUS_IND,
MSG_ID_VDM_IMSP_CELL_INFO_UPDATE_IND,
MSG_ID_VDM_IMSP_RAT_MODE_IND,
MSG_ID_VDM_IMSP_INTER_RAT_STATUS_IND,
MSG_ID_VDM_IMSP_NW_SEARCH_STATUS_IND,
MSG_ID_VDM_IMSP_NW_SELECT_CNF,
MSG_ID_VDM_IMSP_ABORT_NW_SELECT_CNF,
MSG_ID_VDM_IMSP_OOS_START_IND,
MSG_ID_VDM_IMSP_OOS_END_IND,
MSG_ID_VDM_IMSP_IMS_REG_STATUS_IND,

// for VDM VCC
MSG_ID_VDM_IMSP_SRVCC_STATUS_UPDATE_IND,
MSG_ID_VDM_IMSP_SRVCC_CONTEXT_TRANSFER_CNF,

// for VDM CTRL
MSG_ID_VDM_IMSP_CS_CC_MT_CALL_RING_IND,


// <1.2> From IMC

// for VDM TRK
MSG_ID_VDM_IMC_IMS_CC_MO_CALL_CNF,
MSG_ID_VDM_IMC_IMS_CC_MT_CALL_PRESENT_IND,
MSG_ID_VDM_IMC_IMS_CC_MT_CALL_SETUP_IND,
MSG_ID_VDM_IMC_IMS_CC_MT_CALL_ABORT_IND,
MSG_ID_VDM_IMC_IMS_CC_MT_CALL_ACCEPT_CNF,
MSG_ID_VDM_IMC_IMS_CC_HANGUP_ALL_CNF,
MSG_ID_VDM_IMC_IMS_CC_FORCE_HANGUP_CNF,
MSG_ID_VDM_IMC_IMS_CC_CALL_DISCONNECT_IND,
MSG_ID_VDM_IMC_IMS_CC_CALL_RELATED_SS_CNF,
MSG_ID_VDM_IMC_IMS_CC_EXT_ERROR_REPORT_CNF,
MSG_ID_VDM_IMC_IMS_CC_SEND_DIGIT_CNF,
MSG_ID_VDM_IMC_IMS_CC_START_SEND_DIGIT_CNF,
MSG_ID_VDM_IMC_IMS_CC_STOP_SEND_DIGIT_CNF,
MSG_ID_VDM_IMC_IMS_CC_LIST_CURRENT_CALLS_CNF,
MSG_ID_VDM_IMC_IMS_CC_ALLOC_CONF_CALL_IND,

// for VDM ADS
MSG_ID_VDM_IMC_ADS_CTRL_IND,

// for VDM VCC
MSG_ID_VDM_IMC_SRVCC_CONTEXT_TRANSFER_IND,

// for VDM CTRL
MSG_ID_VDM_IMC_IMS_CC_MT_CALL_RING_IND,

/****************************************************************************
 *                   <2> Destination: VDM TRK
 ****************************************************************************/

// <2.1> From VDM CTRL
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_IND,
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_URI_IND,
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_EMERG_IND,
MSG_ID_VDM_CTRL_TRK_CMD_STK_CALL_IND,
MSG_ID_VDM_CTRL_TRK_CMD_MT_CALL_APPROVE_IND,
MSG_ID_VDM_CTRL_TRK_CMD_MT_CALL_ACCEPT_IND,
MSG_ID_VDM_CTRL_TRK_CMD_HANGUP_ALL_IND,
MSG_ID_VDM_CTRL_TRK_CMD_FORCE_HANGUP_IND,
MSG_ID_VDM_CTRL_TRK_CMD_CALL_RELATED_SS_IND,
MSG_ID_VDM_CTRL_TRK_CMD_DTMF_IND,
MSG_ID_VDM_CTRL_TRK_CMD_EXT_DTMF_IND,
MSG_ID_VDM_CTRL_TRK_CMD_EXT_ERROR_REPORT_IND,
MSG_ID_VDM_CTRL_TRK_CMD_LIST_CURRENT_CALLS_IND,

MSG_ID_VDM_CTRL_TRK_STK_CALL_NUM_IND,

MSG_ID_VDM_CTRL_TRK_CS_CC_MO_CALL_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_STK_CALL_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_EMERG_CALL_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_MO_CALL_ID_IND,
MSG_ID_VDM_CTRL_TRK_CS_CC_MT_CALL_PRESENT_IND,
MSG_ID_VDM_CTRL_TRK_CS_CC_MT_CALL_SETUP_IND,
MSG_ID_VDM_CTRL_TRK_CS_CC_MT_CALL_ACCEPT_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_HANGUP_ALL_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_FORCE_HANGUP_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_CALL_DISCONNECT_IND,
MSG_ID_VDM_CTRL_TRK_CS_CC_CALL_RELATED_SS_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_EXT_ERROR_REPORT_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_START_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_STOP_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_CS_CC_ECPI_TRANSLATE_IND,
MSG_ID_VDM_CTRL_TRK_CS_CC_LIST_CURRENT_CALLS_CNF,

MSG_ID_VDM_CTRL_TRK_IMS_CC_MO_CALL_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_PRESENT_IND,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_SETUP_IND,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_ABORT_IND,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_ACCEPT_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_HANGUP_ALL_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_FORCE_HANGUP_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_CALL_DISCONNECT_IND,
MSG_ID_VDM_CTRL_TRK_IMS_CC_CALL_RELATED_SS_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_EXT_ERROR_REPORT_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_START_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_STOP_SEND_DIGIT_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_LIST_CURRENT_CALLS_CNF,
MSG_ID_VDM_CTRL_TRK_IMS_CC_ALLOC_CONF_CALL_IND,

MSG_ID_VDM_CTRL_TRK_TIMER_EXPIRY_IND,

// <2.2> From VDM ADS
MSG_ID_VDM_TRK_ADS_INIT_CNF,
MSG_ID_VDM_TRK_ADS_SELECT_CNF,
MSG_ID_VDM_TRK_ADS_END_CNF,


// <2.3> From VDM VCC
MSG_ID_VDM_TRK_VCC_SRVCC_START_IND,
MSG_ID_VDM_TRK_VCC_SRVCC_END_IND,
MSG_ID_VDM_TRK_VCC_CONF_SRVCC_IND, // for R10 SRVCC


/****************************************************************************
 *                          <3> Destination: VDM ADS
 ****************************************************************************/

// <3.1> From VDM CTRL
MSG_ID_VDM_CTRL_ADS_FDN_ECC_CHECK_CNF,
MSG_ID_VDM_CTRL_ADS_GET_SSAC_PARAM_CNF,
MSG_ID_VDM_CTRL_ADS_IMS_VOPS_SUPP_IND,
MSG_ID_VDM_CTRL_ADS_EMB_S1_SUPP_IND,
MSG_ID_VDM_CTRL_ADS_VOICE_MODE_IND,
MSG_ID_VDM_CTRL_ADS_EUTRAN_VDP_IND,
MSG_ID_VDM_CTRL_ADS_UE_MODE_IND,
MSG_ID_VDM_CTRL_ADS_NAS_REG_STATUS_IND,
MSG_ID_VDM_CTRL_ADS_CELL_INFO_UPDATE_IND,
MSG_ID_VDM_CTRL_ADS_RAT_MODE_IND,
MSG_ID_VDM_CTRL_ADS_INTER_RAT_STATUS_IND,
MSG_ID_VDM_CTRL_ADS_NW_SEARCH_STATUS_IND,
MSG_ID_VDM_CTRL_ADS_NW_SELECT_CNF,
MSG_ID_VDM_CTRL_ADS_ABORT_NW_SELECT_CNF,
MSG_ID_VDM_CTRL_ADS_OOS_START_IND,
MSG_ID_VDM_CTRL_ADS_OOS_END_IND,
MSG_ID_VDM_CTRL_ADS_IMS_REG_STATUS_IND,
MSG_ID_VDM_CTRL_ADS_ADS_CTRL_IND,
MSG_ID_VDM_CTRL_ADS_TIMER_EXPIRY_IND,


// <3.2> From VDM TRK
MSG_ID_VDM_TRK_ADS_INIT_REQ,
MSG_ID_VDM_TRK_ADS_SELECT_REQ,
MSG_ID_VDM_TRK_ADS_END_REQ,


// <3.3> From VDM VCC
MSG_ID_VDM_ADS_VCC_SRVCC_START_IND,
MSG_ID_VDM_ADS_VCC_SRVCC_END_IND,


/****************************************************************************
 *                          <4> Destination: VDM VCC
 ****************************************************************************/

// <4.1> From VDM CTRL
MSG_ID_VDM_CTRL_VCC_SRVCC_STATUS_UPDATE_IND,
MSG_ID_VDM_CTRL_VCC_SRVCC_CONTEXT_TRANSFER_CNF,

MSG_ID_VDM_CTRL_VCC_SRVCC_CONTEXT_TRANSFER_IND,

MSG_ID_VDM_CTRL_VCC_TIMER_EXPIRY_IND,


// <4.2> From VDM TRK
MSG_ID_VDM_TRK_VCC_CONF_SRVCC_RSP, // for R10 SRVCC


// <4.3> From VDM ADS


/****************************************************************************
 *                          <5> Destination: VDM CTRL
 ****************************************************************************/

// <5.1> From VDM TRK
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_URI_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_DIAL_EMERG_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_STK_CALL_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_MT_CALL_APPROVE_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_MT_CALL_ACCEPT_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_HANGUP_ALL_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_FORCE_HANGUP_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_CALL_RELATED_SS_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_DTMF_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_EXT_DTMF_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_EXT_ERROR_REPORT_RSP,
MSG_ID_VDM_CTRL_TRK_CMD_LIST_CURRENT_CALLS_RSP,
MSG_ID_VDM_CTRL_TRK_SND_ECPI_MO_CALL_ID_ALLOC_REQ,
MSG_ID_VDM_CTRL_TRK_SND_ECPI_MT_CALL_SETUP_REQ,
MSG_ID_VDM_CTRL_TRK_SND_ECPI_CALL_RELEASE_REQ,
MSG_ID_VDM_CTRL_TRK_SND_MT_CALL_APPROVE_REQ,
MSG_ID_VDM_CTRL_TRK_SND_STK_CALL_TR_REQ,
MSG_ID_VDM_CTRL_TRK_VDM_VOICE_STATUS_REQ,

MSG_ID_VDM_CTRL_TRK_CS_CC_MO_CALL_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_EMERG_CALL_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_STK_CALL_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_MT_CALL_PRESENT_RSP,
MSG_ID_VDM_CTRL_TRK_CS_CC_MT_CALL_ACCEPT_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_HANGUP_ALL_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_FORCE_HANGUP_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_CALL_RELATED_SS_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_EXT_ERROR_REPORT_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_START_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_STOP_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_CS_CC_ECPI_TRANSLATE_RSP,
MSG_ID_VDM_CTRL_TRK_CS_CC_LIST_CURRENT_CALLS_REQ,

MSG_ID_VDM_CTRL_TRK_IMS_CC_MO_CALL_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_PRESENT_RSP,
MSG_ID_VDM_CTRL_TRK_IMS_CC_MT_CALL_ACCEPT_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_HANGUP_ALL_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_FORCE_HANGUP_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_CALL_RELATED_SS_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_EXT_ERROR_REPORT_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_START_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_STOP_SEND_DIGIT_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_LIST_CURRENT_CALLS_REQ,
MSG_ID_VDM_CTRL_TRK_IMS_CC_ALLOC_CONF_CALL_RSP,


// <5.2> From VDM ADS
MSG_ID_VDM_CTRL_ADS_SND_ADS_ATTEMPT_NOTIFICATION_REQ,
MSG_ID_VDM_CTRL_ADS_SND_ADS_END_NOTIFICATION_REQ,
MSG_ID_VDM_CTRL_ADS_FDN_ECC_CHECK_REQ,
MSG_ID_VDM_CTRL_ADS_GET_SSAC_PARAM_REQ,
MSG_ID_VDM_CTRL_ADS_NW_SELECT_REQ,
MSG_ID_VDM_CTRL_ADS_ABORT_NW_SELECT_REQ,

// <5.3> From VDM VCC
MSG_ID_VDM_CTRL_VCC_SRVCC_STATUS_UPDATE_REQ,
MSG_ID_VDM_CTRL_VCC_SRVCC_CONTEXT_TRANSFER_REQ,
MSG_ID_VDM_CTRL_VCC_SND_SRVCC_CONF_CALL_ID_REQ,

/****************************************************************************
 *                   <6> For UT
 ****************************************************************************/
// For VDM UT
MSG_ID_VDM_UT_CONFIG,
MSG_ID_VDM_UT_READ_STATUS,
MSG_ID_VDM_UT_STATUS_REPORT,

// For VDM TRK UT
MSG_ID_VDM_TRK_UT_CONFIG,
MSG_ID_VDM_TRK_UT_READ_STATUS,
MSG_ID_VDM_TRK_UT_STATUS_REPORT,

// For VDM ADS UT
MSG_ID_VDM_ADS_UT_CONFIG,
MSG_ID_VDM_ADS_UT_READ_STATUS,
MSG_ID_VDM_ADS_UT_STATUS_REPORT,

// For VDM VCC UT
MSG_ID_VDM_VCC_UT_CONFIG,
MSG_ID_VDM_VCC_UT_READ_STATUS,
MSG_ID_VDM_VCC_UT_STATUS_REPORT,

MSG_ID_VDM_CODE_END,

MODULE_MSG_END( MSG_ID_VDM_CODE_TAIL )


#endif // _VDM_MSGID_H_

